-- Script path: ReplicatedStorage.Content.Gamemodes.PVP.Difficulties.PVP.SpawnableEnemies
-- Decompile time: 0.58 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
require(ReplicatedStorage.Shared.Types.PVPConstantTypes)
return {
    Normal = {
        Cost = 40,
        Eco = 4,
        PurchaseAmount = 3,
        SpawnTimer = 1,
        PurchaseDebounceTime = 0,
        PurchaseAmountEnd = 6,
        PurchaseAmountEndWave = 7,
        StartWave = 2,
        Icon = "rbxassetid://17514280373",
    },
    Quick = {
        Cost = 55,
        Eco = 6,
        PurchaseAmount = 2,
        SpawnTimer = 0.75,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280012",
        StartWave = 3,
        PurchaseAmountEnd = 4,
        PurchaseAmountEndWave = 10,
    },
    Heavy = {
        Cost = 75,
        Eco = 8,
        PurchaseAmount = 3,
        SpawnTimer = 1,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280271",
        StartWave = 5,
        PurchaseAmountEnd = 5,
        PurchaseAmountEndWave = 12,
    },
    Hidden = {
        Cost = 90,
        Eco = 12,
        PurchaseAmount = 3,
        SpawnTimer = 0.8,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280740",
        StartWave = 8,
        PurchaseAmountEnd = 6,
        PurchaseAmountEndWave = 15,
    },
    Breaker2 = {
        Cost = 120,
        Eco = 16,
        PurchaseAmount = 2,
        SpawnTimer = 1,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280886",
        StartWave = 10,
        PurchaseAmountEnd = 5,
        PurchaseAmountEndWave = 17,
    },
    Armored = {
        Cost = 155,
        Eco = 20,
        PurchaseAmount = 2,
        SpawnTimer = 0.75,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514281040",
        StartWave = 12,
        PurchaseAmountEnd = 6,
        PurchaseAmountEndWave = 20,
    },
    Enraged = {
        Cost = 210,
        Eco = 24,
        PurchaseAmount = 3,
        SpawnTimer = 0.5,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280956",
        StartWave = 15,
    },
    Necromancer = {
        Cost = 260,
        Eco = 0,
        PurchaseAmount = 1,
        SpawnTimer = 3,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280487",
        StartWave = 18,
    },
    ["Hidden Boss"] = {
        Cost = 480,
        Eco = 0,
        PurchaseAmount = 1,
        SpawnTimer = 2,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280635",
        StartWave = 20,
    },
    ["Slow Boss"] = {
        Cost = 660,
        Eco = -50,
        PurchaseAmount = 1,
        SpawnTimer = 3,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280160",
        StartWave = 22,
    },
    Breaker4 = {
        Cost = 750,
        Eco = -100,
        PurchaseAmount = 4,
        SpawnTimer = 2,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280804",
        StartWave = 24,
    },
    Tank = {
        Cost = 3000,
        Eco = -200,
        PurchaseAmount = 1,
        SpawnTimer = 10,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514279832",
        StartWave = 26,
    },
}