-- Script path: ReplicatedStorage.Content.Tower.Commander.Stats
-- Decompile time: 2.24 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TowerDPS = require(ReplicatedStorage.Shared.Modules.TowerDPS)
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    Stats = {
        Default = {
            Upgrades = {
                {
                    Image = 5525000768,
                    Title = "Leadership",
                    Cost = 400,
                    Stats = {Range = 10, Extras = {"Firerate Buff: 10 > 15%"}, Attributes = {FirerateBuff = 15}},
                },
                {
                    Image = 4594880289,
                    Title = "Call to Arms",
                    Cost = 2450,
                    Stats = {
                        Range = 13,
                        Damage = 15,
                        Cooldown = 0.6,
                        Extras = {"Call to Arms (30s Cooldown)", "Give surrounding towers +10% Firerate for 10s"},
                        Attributes = {CTABuff = 10},
                        Detections = {
                            [Enum.StatusEffect.LeadDetection] = true,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.FlyingDetection] = true,
                        },
                    },
                },
                {
                    Image = 5525002879,
                    Title = "Intense Training",
                    Cost = 4500,
                    Stats = {
                        Damage = 30,
                        Range = 15,
                        Extras = {"Firerate Buff: 15% > 17.5%", "Call to Arms (15% Firerate Buff)"},
                        Attributes = {FirerateBuff = 17.5, CTABuff = 15},
                    },
                },
                {
                    Image = 17512145719,
                    Title = "Strength in Numbers",
                    Cost = 14000,
                    Stats = {
                        Damage = 50,
                        Range = 17,
                        Extras = {
                            "Firerate Buff: 17.5% > 20%",
                            "Support Caravan (60 Seconds)",
                            "Call to Arms (20% Firerate Buff)",
                        },
                        Attributes = {FirerateBuff = 20, CTABuff = 20},
                    },
                },
            },
            Defaults = {
                Price = 650,
                Range = 10,
                Cooldown = 0,
                Damage = 0,
                Limit = 6,
                Abilities = {
                    {
                        Name = "Call Of Arms",
                        DisplayName = "Call to Arms",
                        Description = "Gives surrounding towers a temporary cooldown reduction for a short duration.",
                        Level = 2,
                        Icon = 4594880289,
                        Debounce = 30,
                    },
                    {
                        Name = "Support Caravan",
                        Description = "Summons support APCS that deal damage to enemies within range.",
                        Level = 4,
                        Icon = 17512145719,
                        Debounce = 60,
                        Price = 2000,
                        ExcludeModes = {"Adidas2026"},
                    },
                },
                Detections = {
                    [Enum.StatusEffect.FlyingDetection] = false,
                    [Enum.StatusEffect.HiddenDetection] = false,
                },
                Attributes = {FirerateBuff = 10, CTABuff = 30},
            },
        },
    },
    Properties = {
        Description = "A support tower that boosts the firerate of towers within its range.",
        Height = 0,
        Level = 5,
        BoundingSize = Vector3.new(0, 0, 0),
        DPS_Display = {DPS = TowerDPS.Default},
        Role = Enum.TowerRole.Support,
        Price = {Value = 4000, Type = Enum.CurrencyType.Coins},
        Class = Enum.TowerType.Ground,
        SkinData = {
            Patriotic = {Icon = 18323544710, Rarity = Enum.SkinRarity.Legendary},
            Maid = {Icon = 4863537631, Rarity = Enum.SkinRarity.Legendary},
            General = {Icon = 4592583610, Rarity = Enum.SkinRarity.Common},
            Bunny = {Icon = 4863537216, Rarity = Enum.SkinRarity.Event},
            Gargoyle = {Icon = 4592583506, Rarity = Enum.SkinRarity.Event},
            Eclipse = {Icon = 4088821168, Rarity = Enum.SkinRarity.Event},
            Bloxy = {Icon = 4863529214, Rarity = Enum.SkinRarity.Exclusive},
            ["Spring Time"] = {Icon = 4863537631, Rarity = Enum.SkinRarity.Exclusive},
            Ghost = {Icon = 4863529214, Rarity = Enum.SkinRarity.Event},
            Frost = {Icon = 4863529214, Rarity = Enum.SkinRarity.Event},
            Victorian = {Icon = 4592584296, Rarity = Enum.SkinRarity.Common},
            Green = {Icon = 4592583745, Rarity = Enum.SkinRarity.Common},
            ["War Lord"] = {Icon = 4592584419, Rarity = Enum.SkinRarity.Exclusive},
            Galactic = {Icon = 4592583367, Rarity = Enum.SkinRarity.Uncommon},
            Neko = {Icon = 4863537631, Rarity = Enum.SkinRarity.Rare},
            Red = {Icon = 4592583947, Rarity = Enum.SkinRarity.Common},
            Plushie = {Icon = 4343065951, Rarity = Enum.SkinRarity.Exclusive},
            Ducky = {Icon = 4343065951, Rarity = Enum.SkinRarity.Rare},
            Lifeguard = {Icon = 4343065951, Rarity = Enum.SkinRarity.Event},
            Holiday = {Icon = 4343065951, Rarity = Enum.SkinRarity.Event},
            Valentines = {Icon = 4343065951, Rarity = Enum.SkinRarity.Rare},
            Brisk = {Icon = 4343065951, Rarity = Enum.SkinRarity.Rare},
            Pirate = {Icon = 4088821168, Rarity = Enum.SkinRarity.Rare},
            Umbra = {Icon = 4088821168, Rarity = Enum.SkinRarity.Event},
            Phantom = {Icon = 4088821168, Rarity = Enum.SkinRarity.Legendary},
            Eggrypted = {Icon = 4343065951, Rarity = Enum.SkinRarity.Rare},
            Vigilante = {Icon = 17507649270, Rarity = Enum.SkinRarity.Rare},
            Pattern = {Icon = 17507648760, Rarity = Enum.SkinRarity.Uncommon},
            Fallen = {Icon = 80567934657980, Rarity = Enum.SkinRarity.Rare},
            Wasteland = {Icon = 93243165798255, Rarity = Enum.SkinRarity.Legendary},
            Santa = {Icon = 117501182181139, Rarity = Enum.SkinRarity.Rare},
            Aqua = {Icon = 89379123461384, Rarity = Enum.SkinRarity.Rare},
            Werewolf = {Icon = 0, Rarity = Enum.SkinRarity.Legendary},
            Wonderland = {Icon = 137228119208598, Rarity = Enum.SkinRarity.Legendary},
            ["Candy Cane"] = {Icon = 85504021601648, Rarity = Enum.SkinRarity.Uncommon},
            Director = {Icon = 111213172347168, Rarity = Enum.SkinRarity.Uncommon},
            Referee = {
                Icon = 89379123461384,
                Rarity = Enum.SkinRarity.Exclusive,
                AbilityIcons = {["Call Of Arms"] = 140727292388760},
            },
            Seal = {Icon = 89379123461384, Rarity = Enum.SkinRarity.Common},
        },
        Preview = {
            FieldOfView = 60,
            TowerOffset = Vector3.new(0, -0.5, 0),
            Icon = 6883276917,
            Thumbnail = 0,
            TowerRotation = CFrame.Angles(0, 3.9269908169872414, 0),
            CameraOffset = CFrame.new(0, 0, 6),
        },
        Category = Enum.TowerCategory.Advanced,
    },
}