-- Script path: ReplicatedStorage.Content.NewEnemies.Breaker2.Stats
-- Decompile time: 0.23 ms

return {
    Speed = 4.5,
    MaxHealth = 30,
    HealthPerDifficulty = {
        Baby = 20,
        Easy = 20,
        Casual = 30,
        Intermediate = 40,
        PizzaParty = 100,
        Badlands = 80,
        PollutedWasteland = 150,
        Molten = 80,
        Fallen = 100,
        Frost = 100,
        PVP = 30,
        PVP_lowRanks = 40,
        PVP_midRanks = 60,
        PVP_highRanks = 100,
        PlsDonateHard = 80,
        SummerEasy = 40,
        SummerMedium = 80,
        SummerHard = 100,
        SummerExperimental = 100,
        Trial = 150,
        Act1 = 120,
        NilZone = 80,
        Chapter1Mission6 = 50,
        Chapter1Mission7 = 50,
        Chapter1Mission8 = 35,
    },
    Reward = {
        Easy = 25,
        Casual = 20,
        Intermediate = 25,
        PizzaParty = 100,
        Badlands = 120,
        Molten = 25,
        Fallen = 120,
        Frost = 200,
        PVP = 25,
        PlsDonateHard = 25,
        PollutedWasteland = 200,
        Trial = 75,
        SummerEasy = 40,
        SummerMedium = 80,
        SummerHard = 100,
        SummerExperimental = 100,
        Act1 = 120,
        NilZone = 120,
        Chapter1Mission6 = 75,
        Chapter1Mission7 = 75,
        Chapter1Mission8 = 90,
    },
    Attributes = {},
}