-- Script path: ReplicatedStorage.Content.NewEnemies.Slow.Stats
-- Decompile time: 0.18 ms

return {
    Speed = 2.5,
    MaxHealth = 18,
    HealthPerDifficulty = {
        Baby = 14,
        Easy = 14,
        Normal = 14,
        Casual = 20,
        Tutorial = 8,
        Intermediate = 25,
        Insane = 18,
        PVP_lowRanks = 20,
        PVP_midRanks = 30,
        PVP_highRanks = 60,
        SummerEasy = 28,
        SummerMedium = 40,
        Chapter1Mission1 = 14,
        Chapter1Mission2 = 16,
        Chapter1Mission3 = 30,
        Chapter1Mission4 = 18,
        Chapter1Mission5 = 35,
        Chapter1Mission6 = 35,
        Chapter1Mission7 = 35,
        Chapter1Mission8 = 35,
    },
    Reward = {
        Easy = 10,
        Casual = 10,
        Intermediate = 10,
        PizzaParty = 10,
        Badlands = 10,
        Molten = 10,
        Fallen = 10,
        PVP_lowRanks = 10,
        PVP_midRanks = 10,
        PVP_highRanks = 10,
        PlsDonateHard = 10,
        PollutedWasteland = 10,
        SummerEasy = 20,
        SummerMedium = 30,
        Chapter1Mission1 = 25,
        Chapter1Mission2 = 30,
        Chapter1Mission3 = 40,
        Chapter1Mission4 = 40,
        Chapter1Mission5 = 40,
        Chapter1Mission6 = 50,
        Chapter1Mission7 = 50,
        Chapter1Mission8 = 50,
    },
    Attributes = {},
}