-- Script path: ReplicatedStorage.Content.Tower.Minigunner.Stats-PVP
-- Decompile time: 1.90 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TowerDPS = require(ReplicatedStorage.Shared.Modules.TowerDPS)
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    Stats = {
        Default = {
            Defaults = {
                Price = 2550,
                Range = 16,
                Cooldown = 0.18,
                Damage = 3,
                Limit = 12,
                Detections = {
                    [Enum.StatusEffect.FlyingDetection] = false,
                    [Enum.StatusEffect.HiddenDetection] = false,
                },
                Attributes = {RevTime = 1.4, SlowTime = 1},
            },
            Upgrades = {
                {
                    Image = 15184753790,
                    Title = "Improved Handling",
                    Cost = 850,
                    Stats = {
                        Range = 17,
                        Cooldown = 0.17,
                        Damage = 3,
                        Attributes = {RevTime = 1.2},
                        Extras = {"Faster Rev Time (1.2)"},
                    },
                },
                {
                    Image = 15184753514,
                    Title = "Specialized Tech",
                    Cost = 1550,
                    Stats = {
                        Range = 18.5,
                        Cooldown = 0.17,
                        Damage = 5,
                        Detections = {[Enum.StatusEffect.HiddenDetection] = true},
                    },
                },
                {
                    Image = 15184753289,
                    Title = "Geared Up",
                    Cost = 8500,
                    Stats = {
                        Damage = 13,
                        Cooldown = 0.15,
                        Range = 19,
                        Attributes = {RevTime = 1},
                        Extras = {"Faster Rev Time (1)"},
                    },
                },
                {
                    Image = 15184752970,
                    Title = "Futuristic Armory",
                    Cost = 18750,
                    Stats = {
                        Range = 20,
                        Damage = 20,
                        Cooldown = 0.1,
                        Attributes = {RevTime = 1},
                        Extras = {"Faster Rev Time (1)"},
                    },
                },
            },
        },
        Golden = {
            Defaults = {
                Price = 3000,
                Range = 15,
                Cooldown = 0.12,
                Damage = 2,
                Limit = 12,
                Detections = {
                    [Enum.StatusEffect.FlyingDetection] = false,
                    [Enum.StatusEffect.HiddenDetection] = false,
                },
                Attributes = {RevTime = 1.4, SlowTime = 1},
            },
            Upgrades = {
                {
                    Image = 15184753790,
                    Title = "Improved Handling",
                    Cost = 900,
                    Stats = {
                        Range = 15,
                        Cooldown = 0.12,
                        Damage = 3,
                        Attributes = {RevTime = 1.2},
                        Extras = {"Faster Rev Time (1.2)"},
                    },
                },
                {
                    Image = 15184753514,
                    Title = "Thermal Vision",
                    Cost = 2000,
                    Stats = {
                        Range = 18,
                        Damage = 4,
                        Cooldown = 0.12,
                        Detections = {[Enum.StatusEffect.HiddenDetection] = true},
                    },
                },
                {
                    Image = 15184753289,
                    Title = "High Tech Armory",
                    Cost = 8500,
                    Stats = {Cooldown = 0.1, Range = 18, Damage = 8, Attributes = {RevTime = 1}},
                },
                {
                    Image = 15184752970,
                    Title = "24 Karat Gatling Gun",
                    Cost = 30000,
                    Stats = {Damage = 22, Range = 20, Cooldown = 0.1, Attributes = {RevTime = 1}},
                },
            },
        },
    },
    Properties = {
        Description = "A high-firerate tower that carries a M61 Vulcan Gatling Gun",
        Height = 0,
        Level = 15,
        BoundingSize = Vector3.new(0, 0, 0),
        DPS_Display = {Default = TowerDPS.Default},
        Role = Enum.TowerRole.Offense,
        Price = {Value = 8000, Type = Enum.CurrencyType.Coins},
        Class = Enum.TowerType.Ground,
        SkinData = {
            ["Golden Plushie"] = {Icon = 18563673298, Rarity = Enum.SkinRarity.Exclusive},
            Ghost = {Icon = 4863529214, Rarity = Enum.SkinRarity.Event},
            Twitter = {Icon = 4676013057, Rarity = Enum.SkinRarity.Exclusive},
            Winter = {Icon = 4343076813, Rarity = Enum.SkinRarity.Event},
            ["Black Ops"] = {Icon = 3958845964, Rarity = Enum.SkinRarity.Common},
            Pumpkin = {Icon = 4125170145, Rarity = Enum.SkinRarity.Event},
            Party = {Icon = 3958840529, Rarity = Enum.SkinRarity.Exclusive},
            Xmas = {Icon = 4538504114, Rarity = Enum.SkinRarity.Event},
            Blue = {Icon = 3958831177, Rarity = Enum.SkinRarity.Common},
            Bunny = {Icon = 4863414906, Rarity = Enum.SkinRarity.Event},
            Heavy = {Icon = 4343076813, Rarity = Enum.SkinRarity.Common},
            Golden = {Icon = 3958844258, Rarity = Enum.SkinRarity.Golden},
            Hazmat = {Icon = 4961734585, Rarity = Enum.SkinRarity.Common},
            Wraith = {Icon = 4497119837, Rarity = Enum.SkinRarity.Rare},
            Green = {Icon = 3958838799, Rarity = Enum.SkinRarity.Common},
            Toy = {Icon = 4793469431, Rarity = Enum.SkinRarity.Uncommon},
            Frost = {Icon = 4863434919, Rarity = Enum.SkinRarity.Event},
            Crusader = {Icon = 4088821168, Rarity = Enum.SkinRarity.Event},
            Community = {Icon = 4863434919, Rarity = Enum.SkinRarity.Exclusive},
            Ducky = {Icon = 4863434919, Rarity = Enum.SkinRarity.Rare},
            Beach = {Icon = 4863434919, Rarity = Enum.SkinRarity.Event},
            Plushie = {Icon = 4863434919, Rarity = Enum.SkinRarity.Exclusive},
            Holiday = {Icon = 4863434919, Rarity = Enum.SkinRarity.Event},
            ["Space Elite"] = {Icon = 4793469431, Rarity = Enum.SkinRarity.Uncommon},
            Phantom = {Icon = 4793469431, Rarity = Enum.SkinRarity.Rare},
            Warlord = {Icon = 4793469431, Rarity = Enum.SkinRarity.Event},
            Trucker = {Icon = 3270010000, Rarity = Enum.SkinRarity.Legendary},
            Sweaking = {Icon = 4343065951, Rarity = Enum.SkinRarity.Rare},
            Chad = {Icon = 4343065951, Rarity = Enum.SkinRarity.Legendary},
            Fallen = {Icon = 18739982182, Rarity = Enum.SkinRarity.Rare},
            ["Road Rage"] = {Icon = 127265987839477, Rarity = Enum.SkinRarity.Rare},
            Nutcracker = {Icon = 123307115343441, Rarity = Enum.SkinRarity.Uncommon},
            Gardener = {Icon = 82544636570442, Rarity = Enum.SkinRarity.Rare},
            Cursed = {Icon = 0, Rarity = Enum.SkinRarity.Rare},
        },
        Preview = {
            FieldOfView = 60,
            TowerOffset = Vector3.new(0, 0, 0),
            Icon = 6883296891,
            Thumbnail = 0,
            TowerRotation = CFrame.Angles(0, 3.9269908169872414, 0),
            CameraOffset = CFrame.new(0, 0, 6),
        },
        Category = Enum.TowerCategory.Advanced,
    },
}