-- Script path: ReplicatedStorage.Packages.Sift.Array.slice.spec
-- Decompile time: 0.84 ms

return function() -- Line: 1
    local slice = require(script.Parent.slice)
    it("should return a slice of the given array", function() -- Line: 4 -- upvalues: slice (val)
        local v1 = slice({1, 2, 3}, 2, 3)
        expect(v1).to.be.a("table")
        expect(#v1).to.equal(2)
        expect(v1[1]).to.equal(2)
        expect(v1[2]).to.equal(3)
    end)
    it("should return a slice of the given array with a negative start index", function() -- Line: 15 -- upvalues: slice (val)
        local v1 = slice({1, 2, 3}, -1, 3)
        expect(v1).to.be.a("table")
        expect(#v1).to.equal(2)
        expect(v1[1]).to.equal(2)
        expect(v1[2]).to.equal(3)
    end)
    it("should return a slice of the given array with a negative end index", function() -- Line: 26 -- upvalues: slice (val)
        local v1 = slice({1, 2, 3}, 1, -1)
        expect(v1).to.be.a("table")
        expect(#v1).to.equal(2)
        expect(v1[1]).to.equal(1)
        expect(v1[2]).to.equal(2)
    end)
    it("should return a slice of the given array with a negative start and end index", function() -- Line: 37 -- upvalues: slice (val)
        local v1 = slice({1, 2, 3}, -2, -1)
        expect(v1).to.be.a("table")
        expect(#v1).to.equal(2)
        expect(v1[1]).to.equal(1)
        expect(v1[2]).to.equal(2)
    end)
end