-- Script path: ReplicatedStorage.Content.NewEnemies.Skeleton.Stats
-- Decompile time: 0.21 ms

return {
    Speed = 3,
    MaxHealth = 10,
    HealthPerDifficulty = {
        Easy = 10,
        Intermediate = 30,
        Casual = 50,
        Insane = 55,
        PVP_midRanks = 55,
        PlsDonate = 15,
        PlsDonateHard = 50,
        Badlands = 60,
        PollutedWasteland = 200,
        SummerEasy = 15,
        SummerMedium = 30,
        Trial = 25,
        NilZone = 150,
        NilZone2 = 150,
        Act3 = 250,
        Frost = 200,
        Act3Easy = 125,
        Chapter1Mission2 = 20,
        Chapter1Mission3 = 30,
        Chapter1Mission5 = 45,
        Chapter1Mission6 = 100,
        Chapter1Mission7 = 50,
        Chapter1Mission8 = 125,
    },
    Reward = {
        Easy = 60,
        Intermediate = 60,
        Casual = 15,
        Insane = 60,
        PVP_midRanks = 60,
        PlsDonate = 60,
        PlsDonateHard = 60,
        Badlands = 60,
        PollutedWasteland = 60,
        SummerEasy = 60,
        SummerMedium = 60,
        Trial = 60,
        NilZone = 60,
        Act3 = 1616,
        Act3Easy = 800,
        Chapter1Mission6 = 30,
        Chapter1Mission7 = 50,
        Chapter1Mission8 = 50,
    },
    Attributes = {},
}