-- Script path: ReplicatedStorage.Content.Tower.Pyromancer.Stats
-- Decompile time: 3.69 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TowerDPS = require(ReplicatedStorage.Shared.Modules.TowerDPS)
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    Stats = {
        Default = {
            Defaults = {
                Cooldown = 0.275,
                Damage = 1,
                Price = 900,
                Range = 9,
                Attributes = {
                    BurnDamage = 2,
                    BurnTick = 1,
                    BurnTime = 3,
                    DefenseMelt = 1,
                    EnemyBuff = 0,
                    TurningSpeed = 4,
                    Width = 1.25,
                    MaxHits = 3,
                    HitboxSpeed = 25,
                },
                Detections = {
                    [Enum.StatusEffect.FlyingDetection] = false,
                    [Enum.StatusEffect.HiddenDetection] = false,
                    [Enum.StatusEffect.LeadDetection] = true,
                },
            },
            Upgrades = {
                {
                    Cost = 325,
                    Image = 3280081327,
                    Title = "Improved Handling",
                    Stats = {
                        Cooldown = 0.175,
                        Damage = 1,
                        Range = 11,
                        Attributes = {
                            BurnDamage = 2,
                            BurnTick = 1,
                            BurnTime = 3,
                            DefenseMelt = 1,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 4,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {},
                    },
                    Tooltips = {
                        {
                            ButtonText = "Upgraded Flames",
                            Header = "Stats",
                            Content = {{Text = "Max Hits: 3 > 4"}, {Text = "Flame Size: 1.25 > 1.5"}},
                        },
                    },
                },
                {
                    Cost = 1000,
                    Image = 3304823121,
                    Title = "Fire Fighting",
                    Stats = {
                        Cooldown = 0.175,
                        Damage = 2,
                        Range = 11,
                        Attributes = {
                            BurnDamage = 2,
                            BurnTick = 1,
                            BurnTime = 3,
                            DefenseMelt = 1,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 5,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {},
                    },
                    Tooltips = {
                        {
                            ButtonText = "Upgraded Flames",
                            Header = "Stats",
                            Content = {{Text = "Max Hits: 4 > 5"}},
                        },
                    },
                },
                {
                    Cost = 2000,
                    Image = 3304823988,
                    Title = "Fire Hazard",
                    Stats = {
                        Cooldown = 0.175,
                        Damage = 3,
                        Range = 12.5,
                        Attributes = {
                            BurnDamage = 5,
                            BurnTick = 1,
                            BurnTime = 6,
                            DefenseMelt = 5,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 7,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {},
                    },
                    Tooltips = {
                        {
                            ButtonText = "Upgraded Flames",
                            Header = "Stats",
                            Content = {
                                {Text = "Max Hits: 5 > 7"},
                                {Text = "Burn Damage: 2 > 5"},
                                {Text = "Burn Time: 3s > 6s"},
                                {Text = "Defense Melt: 1 > 5"},
                            },
                        },
                    },
                },
                {
                    Cost = 3777,
                    Image = 3304824958,
                    Title = "Napalm Thrower",
                    Stats = {
                        Cooldown = 0.175,
                        Damage = 5,
                        Range = 12.5,
                        Attributes = {
                            BurnDamage = 10,
                            BurnTick = 1,
                            BurnTime = 10,
                            DefenseMelt = 10,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.75,
                            MaxHits = 7,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {},
                    },
                    Tooltips = {
                        {
                            ButtonText = "Upgraded Flames",
                            Header = "Stats",
                            Content = {
                                {Text = "Flame Size: 1.5 > 1.75"},
                                {Text = "Burn Damage: 5 > 10"},
                                {Text = "Burn Time: 6s > 10s"},
                                {Text = "Defense Melt: 5 > 10"},
                            },
                        },
                    },
                },
                {
                    Cost = 11111,
                    Image = 3304825822,
                    Title = "Pyromaniac",
                    Stats = {
                        Cooldown = 0.175,
                        Damage = 9,
                        Range = 14,
                        Attributes = {
                            BurnDamage = 25,
                            BurnTick = 1,
                            BurnTime = 10,
                            DefenseMelt = 10,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 2.5,
                            MaxHits = 10,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {},
                    },
                    Tooltips = {
                        {
                            ButtonText = "Upgraded Flames",
                            Header = "Stats",
                            Content = {
                                {Text = "Flame Size: 1.75 > 2.5"},
                                {Text = "Max Hits: 7 > 10"},
                                {Text = "Burn Damage: 10 > 25"},
                            },
                        },
                    },
                },
            },
        },
        Golden = {
            Defaults = {
                Cooldown = 0.275,
                Damage = 1,
                Price = 850,
                Range = 9,
                Attributes = {
                    BurnDamage = 2,
                    BurnTick = 1,
                    BurnTime = 4,
                    DefenseMelt = 2,
                    EnemyBuff = 0,
                    TurningSpeed = 4,
                    Width = 1.25,
                    MaxHits = 4,
                    HitboxSpeed = 25,
                },
                Detections = {
                    [Enum.StatusEffect.FlyingDetection] = false,
                    [Enum.StatusEffect.HiddenDetection] = true,
                    [Enum.StatusEffect.LeadDetection] = true,
                },
            },
            Upgrades = {
                {
                    Cost = 325,
                    Image = 3280081327,
                    Title = "Better Handling",
                    Stats = {
                        Cooldown = 0.175,
                        Damage = 1,
                        Range = 11,
                        Attributes = {
                            BurnDamage = 2,
                            BurnTick = 1,
                            BurnTime = 4,
                            DefenseMelt = 2,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 4,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {},
                    },
                    Tooltips = {
                        {
                            ButtonText = "Upgraded Flames",
                            Header = "Stats",
                            Content = {{Text = "Flame Size: 1.25 > 1.5"}},
                        },
                    },
                },
                {
                    Cost = 900,
                    Image = 3304823121,
                    Title = "Golden Flare",
                    Stats = {
                        Cooldown = 0.175,
                        Damage = 2,
                        Range = 11,
                        Attributes = {
                            BurnDamage = 2,
                            BurnTick = 1,
                            BurnTime = 4,
                            DefenseMelt = 2,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 6,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {},
                    },
                    Tooltips = {
                        {
                            ButtonText = "Upgraded Flames",
                            Header = "Stats",
                            Content = {{Text = "Max Hits: 4 > 6"}},
                        },
                    },
                },
                {
                    Cost = 2777,
                    Image = 3304823988,
                    Title = "Ring Of Fire",
                    Stats = {
                        Cooldown = 0.175,
                        Damage = 4,
                        Range = 13.5,
                        Attributes = {
                            BurnDamage = 5,
                            BurnTick = 1,
                            BurnTime = 7,
                            DefenseMelt = 7,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 8,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {},
                    },
                    Tooltips = {
                        {
                            ButtonText = "Upgraded Flames",
                            Header = "Stats",
                            Content = {
                                {Text = "Max Hits: 6 > 8"},
                                {Text = "Burn Damage: 2 > 5"},
                                {Text = "Burn Time: 4s > 7s"},
                                {Text = "Defense Melt: 2 > 7"},
                            },
                        },
                    },
                },
                {
                    Cost = 7500,
                    Image = 3304824958,
                    Title = "Eternal Ember",
                    Stats = {
                        Cooldown = 0.175,
                        Damage = 9,
                        Range = 13.5,
                        Attributes = {
                            BurnDamage = 12,
                            BurnTick = 1,
                            BurnTime = 360,
                            DefenseMelt = 10,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.75,
                            MaxHits = 8,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {},
                    },
                    Tooltips = {
                        {
                            ButtonText = "Upgraded Flames",
                            Header = "Stats",
                            Content = {
                                {Text = "Flame Size: 1.5 > 1.75"},
                                {Text = "Burn Damage: 5 > 12"},
                                {Text = "Burn Time: 7s > 360s"},
                                {Text = "Defense Melt: 7 > 10"},
                            },
                        },
                    },
                },
                {
                    Cost = 16000,
                    Image = 3304825822,
                    Title = "Kagutsuchi's Blood",
                    Stats = {
                        Cooldown = 0.175,
                        Damage = 12,
                        Range = 15,
                        Attributes = {
                            BurnDamage = 30,
                            BurnTick = 1,
                            BurnTime = 360,
                            DefenseMelt = 15,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 2.5,
                            MaxHits = 10,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {},
                    },
                    Tooltips = {
                        {
                            ButtonText = "Upgraded Flames",
                            Header = "Stats",
                            Content = {
                                {Text = "Flame Size: 1.75 > 2.5"},
                                {Text = "Max Hits: 8 > 10"},
                                {Text = "Burn Damage: 12 > 30"},
                                {Text = "Defense Melt: 10 > 15"},
                            },
                        },
                    },
                },
            },
        },
    },
    Properties = {
        Description = "Burn multiple enemies at once and chip away defense.",
        Height = 0,
        BoundingSize = Vector3.new(0, 0, 0),
        DPS_Display = {
            ["Normal DPS"] = TowerDPS.Default,
            ["Burn DPS"] = TowerDPS.Burn,
            ["Total DPS"] = TowerDPS.DamageOverTime,
        },
        Role = Enum.TowerRole.Offense,
        Price = {Value = 1250, Type = Enum.CurrencyType.Coins},
        Class = Enum.TowerType.Ground,
        SkinData = {
            Blue = {Icon = 4592601308, Rarity = Enum.SkinRarity.Common},
            Bunny = {Icon = 4863529214, Rarity = Enum.SkinRarity.Event},
            Scarecrow = {Icon = 4133666666, Rarity = Enum.SkinRarity.Event},
            Hazmat = {Icon = 3958491828, Rarity = Enum.SkinRarity.Common},
            Frost = {Icon = 4863434919, Rarity = Enum.SkinRarity.Event},
            Ghost = {Icon = 4863529214, Rarity = Enum.SkinRarity.Event},
            Golden = {Icon = 3958495139, Rarity = Enum.SkinRarity.Golden},
            Valentines = {Icon = 4690287263, Rarity = Enum.SkinRarity.Event},
            Acidic = {Icon = 4447248470, Rarity = Enum.SkinRarity.Uncommon},
            Barbecue = {Icon = 4447248470, Rarity = Enum.SkinRarity.Event},
            Mage = {Icon = 4447248470, Rarity = Enum.SkinRarity.Legendary},
            Vigilante = {Icon = 4088821168, Rarity = Enum.SkinRarity.Uncommon},
            Dwarf = {Icon = 4088821168, Rarity = Enum.SkinRarity.Event},
            Plushie = {Icon = 110949683234465, Rarity = Enum.SkinRarity.Exclusive},
            ["Pool Party"] = {Icon = 104604814725961, Rarity = Enum.SkinRarity.Rare},
            ["Hallow Punk"] = {Icon = 0, Rarity = Enum.SkinRarity.Rare},
            Reindeer = {Icon = 73700785908697, Rarity = Enum.SkinRarity.Rare},
            ["Fire Breather"] = {Icon = 118662716601914, Rarity = Enum.SkinRarity.Rare},
            ["Scuba Ops"] = {Icon = 0, Rarity = Enum.SkinRarity.Rare},
            Banned = {Icon = 0, Rarity = Enum.SkinRarity.Exclusive},
        },
        Preview = {
            FieldOfView = 60,
            TowerOffset = Vector3.new(0, 0, 0),
            Icon = 6883301271,
            Thumbnail = 0,
            TowerRotation = CFrame.Angles(0, 3.9269908169872414, 0),
            CameraOffset = CFrame.new(0, 0, 6),
        },
        Category = Enum.TowerCategory.Intermediate,
    },
}