-- Script path: ReplicatedStorage.Content.Tower.Pyromancer.Stats-PVP
-- Decompile time: 2.82 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TowerDPS = require(ReplicatedStorage.Shared.Modules.TowerDPS)
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    Stats = {
        Default = {
            Defaults = {
                Cooldown = 0.25,
                Damage = 1,
                Price = 850,
                Range = 7,
                Attributes = {
                    BurnDamage = 1,
                    BurnTick = 1,
                    BurnTime = 3,
                    DefenseMelt = 0,
                    EnemyBuff = 0,
                    TurningSpeed = 4,
                    Width = 1.25,
                    MaxHits = 3,
                    HitboxSpeed = 25,
                },
                Detections = {
                    [Enum.StatusEffect.FlyingDetection] = false,
                    [Enum.StatusEffect.HiddenDetection] = false,
                    [Enum.StatusEffect.LeadDetection] = true,
                },
            },
            Upgrades = {
                {
                    Cost = 350,
                    Image = 3280081327,
                    Title = "Improved Handling",
                    Stats = {
                        Cooldown = 0.25,
                        Damage = 1,
                        Range = 9,
                        Attributes = {
                            BurnDamage = 1,
                            BurnTick = 0.75,
                            BurnTime = 3,
                            DefenseMelt = 0,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 3,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = false,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {"More range", "Bigger flames"},
                    },
                },
                {
                    Cost = 950,
                    Image = 3304823121,
                    Title = "Fire Fighting",
                    Stats = {
                        Cooldown = 0.25,
                        Damage = 2,
                        Range = 9,
                        Attributes = {
                            BurnDamage = 2,
                            BurnTick = 0.75,
                            BurnTime = 3,
                            DefenseMelt = 0,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 5,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {},
                    },
                },
                {
                    Cost = 1500,
                    Image = 3304823988,
                    Title = "Fire Hazard",
                    Stats = {
                        Cooldown = 0.25,
                        Damage = 2,
                        Range = 10,
                        Attributes = {
                            BurnDamage = 3,
                            BurnTick = 0.5,
                            BurnTime = 5,
                            DefenseMelt = 5,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 5,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {"More burn damage", "Longer burn time", "Defense Melting"},
                    },
                },
                {
                    Cost = 3800,
                    Image = 3304824958,
                    Title = "Napalm Thrower",
                    Stats = {
                        Cooldown = 0.25,
                        Damage = 3,
                        Range = 10,
                        Attributes = {
                            BurnDamage = 4,
                            BurnTick = 0.5,
                            BurnTime = 7.5,
                            DefenseMelt = 5,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.75,
                            MaxHits = 5,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {"More fire damage", "Longer burn time"},
                    },
                },
                {
                    Cost = 9000,
                    Image = 3304825822,
                    Title = "Pyromaniac",
                    Stats = {
                        Cooldown = 0.25,
                        Damage = 6,
                        Range = 12,
                        Attributes = {
                            BurnDamage = 8,
                            BurnTick = 0.5,
                            BurnTime = 10,
                            DefenseMelt = 10,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 2.5,
                            MaxHits = 8,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {
                            "More burn damage",
                            "Longer burn time",
                            "More defense melting",
                            "Bigger flames",
                        },
                    },
                },
            },
        },
        Golden = {
            Defaults = {
                Cooldown = 0.25,
                Damage = 1,
                Price = 800,
                Range = 7.5,
                Attributes = {
                    BurnDamage = 1,
                    BurnTick = 1,
                    BurnTime = 3,
                    DefenseMelt = 0,
                    EnemyBuff = 0,
                    TurningSpeed = 4,
                    Width = 1.25,
                    MaxHits = 4,
                    HitboxSpeed = 25,
                },
                Detections = {
                    [Enum.StatusEffect.FlyingDetection] = false,
                    [Enum.StatusEffect.HiddenDetection] = true,
                    [Enum.StatusEffect.LeadDetection] = true,
                },
            },
            Upgrades = {
                {
                    Cost = 350,
                    Image = 3280081327,
                    Title = "Better Handling",
                    Stats = {
                        Cooldown = 0.25,
                        Damage = 1,
                        Range = 10,
                        Attributes = {
                            BurnDamage = 1,
                            BurnTick = 0.75,
                            BurnTime = 3,
                            DefenseMelt = 0,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 4,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {"More range", "Bigger flames"},
                    },
                },
                {
                    Cost = 750,
                    Image = 3304823121,
                    Title = "Golden Flare",
                    Stats = {
                        Cooldown = 0.25,
                        Damage = 2,
                        Range = 10,
                        Attributes = {
                            BurnDamage = 2,
                            BurnTick = 0.75,
                            BurnTime = 3,
                            DefenseMelt = 0,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 6,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {"Stronger Flames"},
                    },
                },
                {
                    Cost = 1750,
                    Image = 3304823988,
                    Title = "Ring Of Fire",
                    Stats = {
                        Cooldown = 0.25,
                        Damage = 3,
                        Range = 10,
                        Attributes = {
                            BurnDamage = 3,
                            BurnTick = 0.5,
                            BurnTime = 6,
                            DefenseMelt = 5,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.5,
                            MaxHits = 6,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {"More burn damage", "Longer burn time", "Defense Melting"},
                    },
                },
                {
                    Cost = 5750,
                    Image = 3304824958,
                    Title = "Gilded Arsonist",
                    Stats = {
                        Cooldown = 0.25,
                        Damage = 4,
                        Range = 10,
                        Attributes = {
                            BurnDamage = 6,
                            BurnTick = 0.5,
                            BurnTime = 12,
                            DefenseMelt = 10,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 1.75,
                            MaxHits = 6,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {
                            "More fire damage",
                            "Longer burn time",
                            "Better tick speed",
                            "More Defense Melting",
                        },
                    },
                },
                {
                    Cost = 9500,
                    Image = 3304825822,
                    Title = "Kagutsuchi's Fury",
                    Stats = {
                        Cooldown = 0.25,
                        Damage = 8,
                        Range = 12,
                        Attributes = {
                            BurnDamage = 8,
                            BurnTick = 0.5,
                            BurnTime = 20,
                            DefenseMelt = 10,
                            EnemyBuff = 0,
                            TurningSpeed = 4,
                            Width = 2.5,
                            MaxHits = 10,
                        },
                        Detections = {
                            [Enum.StatusEffect.FlyingDetection] = false,
                            [Enum.StatusEffect.HiddenDetection] = true,
                            [Enum.StatusEffect.LeadDetection] = true,
                        },
                        Extras = {"More burn damage", "Longer burn time", "Bigger flames"},
                    },
                },
            },
        },
    },
    Properties = {
        Description = "Burn multiple enemies at once and chip away defense.",
        Height = 0,
        BoundingSize = Vector3.new(0, 0, 0),
        DPS_Display = {
            ["Normal DPS"] = TowerDPS.Default,
            ["Burn DPS"] = TowerDPS.Burn,
            ["Total DPS"] = TowerDPS.DamageOverTime,
        },
        Role = Enum.TowerRole.Offense,
        Price = {Value = 1250, Type = Enum.CurrencyType.Coins},
        Class = Enum.TowerType.Ground,
        SkinData = {
            Blue = {Icon = 4592601308, Rarity = Enum.SkinRarity.Common},
            Bunny = {Icon = 4863529214, Rarity = Enum.SkinRarity.Event},
            Scarecrow = {Icon = 4133666666, Rarity = Enum.SkinRarity.Event},
            Hazmat = {Icon = 3958491828, Rarity = Enum.SkinRarity.Common},
            Frost = {Icon = 4863434919, Rarity = Enum.SkinRarity.Event},
            Ghost = {Icon = 4863529214, Rarity = Enum.SkinRarity.Event},
            Golden = {Icon = 3958495139, Rarity = Enum.SkinRarity.Golden},
            Valentines = {Icon = 4690287263, Rarity = Enum.SkinRarity.Event},
            Acidic = {Icon = 4447248470, Rarity = Enum.SkinRarity.Uncommon},
            Barbecue = {Icon = 4447248470, Rarity = Enum.SkinRarity.Event},
            Mage = {Icon = 4447248470, Rarity = Enum.SkinRarity.Legendary},
            Vigilante = {Icon = 4088821168, Rarity = Enum.SkinRarity.Uncommon},
            Dwarf = {Icon = 4088821168, Rarity = Enum.SkinRarity.Event},
            Plushie = {Icon = 110949683234465, Rarity = Enum.SkinRarity.Exclusive},
            ["Pool Party"] = {Icon = 104604814725961, Rarity = Enum.SkinRarity.Rare},
            ["Hallow Punk"] = {Icon = 0, Rarity = Enum.SkinRarity.Rare},
        },
        Preview = {
            FieldOfView = 60,
            TowerOffset = Vector3.new(0, 0, 0),
            Icon = 6883301271,
            Thumbnail = 0,
            TowerRotation = CFrame.Angles(0, 3.9269908169872414, 0),
            CameraOffset = CFrame.new(0, 0, 6),
        },
        Category = Enum.TowerCategory.Intermediate,
    },
}