-- Script path: ReplicatedStorage.Content.Tower.Biologist.Stats
-- Decompile time: 1.88 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
local BiologistTooltips = require(script.BiologistTooltips)
local plantTooltip = BiologistTooltips.plantTooltip
local newSlotTooltip = BiologistTooltips.newSlotTooltip
return {
    Stats = {
        Default = {
            Defaults = {
                Price = 750,
                Limit = 8,
                Damage = 0,
                Range = 4,
                Cooldown = 1,
                Attributes = {
                    ProjSpeed = 5,
                    Deadzone = 1.5,
                    SecondQueue = false,
                    ThirdQueue = false,
                    SunflowerLvl = 0,
                    SunflowerCD = 20,
                    IvyLvl = 0,
                    IvyCD = 20,
                    NightshadeLvl = 0,
                    NightshadeCD = 20,
                    TreeLvl = 0,
                    TreeCD = 30,
                },
            },
            Upgrades = {
                {
                    Title = "Bio Chemistry",
                    Image = 95317340543936,
                    Cost = 600,
                    Stats = {
                        Attributes = {
                            SecondQueue = false,
                            SunflowerLvl = 1,
                            IvyLvl = 0,
                            NightshadeLvl = 0,
                            TreeLvl = 0,
                        },
                    },
                    Tooltips = {
                        plantTooltip({
                            name = "Sunflower",
                            isUpgrade = true,
                            prevDmg = 6,
                            damage = 10,
                            range = 15,
                            prevCooldown = 1.1,
                            cooldown = 1.1,
                            prevHealth = 50,
                            health = 100,
                        }),
                        plantTooltip({
                            name = "Ivy",
                            damage = 8,
                            cooldown = 2,
                            range = 14,
                            health = 100,
                            radius = 3,
                            psnDamage = 1,
                            psnLen = 4.5,
                            psnTick = 0.75,
                            slowPerc = 5,
                            leadDet = true,
                        }),
                    },
                },
                {
                    Title = "Scientific Breakthrough",
                    Image = 91087216328467,
                    Cost = 1850,
                    Stats = {
                        Attributes = {
                            SecondQueue = true,
                            SunflowerLvl = 2,
                            IvyLvl = 1,
                            NightshadeLvl = 0,
                            TreeLvl = 0,
                        },
                    },
                    Tooltips = {
                        newSlotTooltip(),
                        plantTooltip({
                            name = "Sunflower",
                            isUpgrade = true,
                            prevDmg = 10,
                            damage = 12,
                            prevRange = 15,
                            range = 17,
                            prevCooldown = 1.1,
                            cooldown = 1.1,
                            prevHealth = 100,
                            health = 200,
                            hiddenDet = true,
                        }),
                        (plantTooltip({
                            name = "Ivy",
                            isUpgrade = true,
                            prevDmg = 8,
                            damage = 12,
                            prevRange = 14,
                            range = 15.5,
                            prevCooldown = 2,
                            cooldown = 1.8,
                            prevHealth = 100,
                            health = 200,
                            prevRadius = 3,
                            radius = 4,
                            prevSlowPerc = 5,
                            slowPerc = 7.5,
                            psnLen = 4.5,
                            psnTick = 0.75,
                            prevPsnDmg = 1,
                            psnDamage = 2,
                            leadDet = true,
                        })),
                    },
                },
                {
                    Title = "Flower Power",
                    Image = 101480107243808,
                    Cost = 4500,
                    Stats = {
                        Attributes = {SecondQueue = true, SunflowerLvl = 3, IvyLvl = 2, NightshadeLvl = 0},
                    },
                    Tooltips = {
                        plantTooltip({
                            name = "Sunflower",
                            isUpgrade = true,
                            prevDmg = 12,
                            damage = 28,
                            prevRange = 17,
                            range = 19.5,
                            cooldown = 1,
                            prevHealth = 200,
                            health = 400,
                            hiddenDet = true,
                        }),
                        plantTooltip({
                            name = "Ivy",
                            isUpgrade = true,
                            prevDmg = 12,
                            damage = 25,
                            cooldown = 1.8,
                            prevRange = 15.5,
                            range = 17,
                            prevHealth = 200,
                            health = 400,
                            prevRadius = 4,
                            radius = 4.5,
                            psnLen = 4.5,
                            prevPsnTick = 0.75,
                            psnTick = 0.6,
                            prevPsnDmg = 2,
                            psnDamage = 4,
                            prevSlowPerc = 7.5,
                            slowPerc = 7.5,
                            leadDet = true,
                        }),
                        (plantTooltip({
                            name = "Nightshade",
                            damage = 50,
                            range = 30,
                            cooldown = 35,
                            health = 400,
                            confDur = 1,
                            flyingDet = true,
                        })),
                    },
                },
                {
                    Title = "Botanical Berserker!",
                    Image = 121014188542772,
                    Cost = 20000,
                    Stats = {
                        Attributes = {
                            ThirdQueue = true,
                            SunflowerLvl = 4,
                            IvyLvl = 3,
                            NightshadeLvl = 1,
                            TreeLvl = 0,
                        },
                    },
                    Tooltips = {
                        newSlotTooltip(),
                        plantTooltip({
                            name = "Sunflower",
                            isUpgrade = true,
                            prevDmg = 28,
                            damage = 55,
                            prevRange = 19.5,
                            range = 22.5,
                            prevCooldown = 1,
                            cooldown = 0.8,
                            prevHealth = 400,
                            health = 800,
                            hiddenDet = true,
                        }),
                        plantTooltip({
                            name = "Ivy",
                            isUpgrade = true,
                            prevDmg = 25,
                            damage = 45,
                            prevCooldown = 1.8,
                            cooldown = 1.5,
                            prevRange = 17,
                            range = 18.5,
                            prevRadius = 4.5,
                            prevHealth = 400,
                            health = 800,
                            radius = 4.5,
                            prevSlowPerc = 7.5,
                            slowPerc = 12.5,
                            prevPsnLen = 4.5,
                            psnLen = 5.2,
                            prevPsnTick = 0.6,
                            psnTick = 0.65,
                            prevPsnDmg = 4,
                            psnDamage = 5,
                            leadDet = true,
                        }),
                        (plantTooltip({
                            name = "Nightshade",
                            isUpgrade = true,
                            prevDmg = 50,
                            damage = 135,
                            prevRange = 30,
                            range = 35,
                            prevCooldown = 3,
                            cooldown = 2.75,
                            prevHealth = 400,
                            health = 800,
                            prevConfDur = 1,
                            confDur = 1.25,
                        })),
                    },
                },
            },
        },
    },
    Properties = {
        Description = "There's a zombie on your lawn.. This calls for all out, plants versus zombies warfare!",
        BoundarySize = 1.5,
        Height = 0,
        BoundingSize = Vector3.new(0, 0, 0),
        Role = Enum.TowerRole.Support,
        Class = Enum.TowerType.Ground,
        Preview = {
            FieldOfView = 60,
            TowerOffset = Vector3.new(0, 0, 0),
            Icon = 101795075923269,
            Thumbnail = 0,
            TowerRotation = CFrame.Angles(0, 2.792526803190927, 0),
            CameraOffset = CFrame.new(0, 0, 6),
        },
        SkinData = {Grim = {Icon = 126912872410229, Rarity = Enum.SkinRarity.Rare}},
        Category = Enum.TowerCategory.Exclusive,
    },
}