-- Script path: ReplicatedStorage.Content.TowerCategories
-- Decompile time: 0.27 ms

return {
    Offense = {
        "Scout",
        "Soldier",
        "Paintballer",
        "Demoman",
        "Hunter",
        "Crook Boss",
        "Shotgunner",
        "Pyromancer",
        "Turret",
        "Cowboy",
        "Pursuit",
        "Gatling Gun",
        "Minigunner",
        "Brawler",
        "Accelerator",
        "Warden",
        "Militant",
        "Engineer",
        "Mortar",
        "Commando",
        "Slasher",
        "Executioner",
        "Gladiator",
        "Swarmer",
        "Toxic Gunner",
        "War Machine",
        "Sledger",
    },
    Defense = {
        "Sniper",
        "Freezer",
        "Rocketeer",
        "Trapper",
        "Ace Pilot",
        "Military Base",
        "Mercenary Base",
        "Ranger",
        "Electroshocker",
        "Necromancer",
        "Frost Blaster",
        "Elementalist",
        "Harvester",
        "Snowballer",
        "Hallow Punk",
        "Cyromancer",
        "Elf Camp",
        "Jester",
        "Mecha Base",
        "Archer",
        "Biologist",
        "Cryomancer",
        "Hacker",
    },
    Support = {"Medic", "Farm", "DJ Booth", "Commander", "Firework Technician"},
}