-- Script path: ReplicatedStorage.Content.NewEnemies.Normal.Stats
-- Decompile time: 0.21 ms

return {
    Speed = 2.7,
    MaxHealth = 6,
    HealthPerDifficulty = {
        Baby = 4,
        Easy = 4,
        Normal = 4,
        Casual = 5,
        Intermediate = 5,
        Insane = 6,
        Tutorial = 2,
        PVP_lowRanks = 4,
        PVP_midRanks = 6,
        PVP_highRanks = 8,
        SummerEasy = 8,
        SummerMedium = 10,
        Chapter1Mission1 = 6,
        Chapter1Mission2 = 6,
        Chapter1Mission3 = 6,
        Chapter1Mission5 = 6,
        Chapter1Mission6 = 8,
        Chapter1Mission7 = 6,
        Chapter1Mission8 = 10,
    },
    Reward = {
        Baby = 5,
        Easy = 5,
        Normal = 5,
        Casual = 5,
        Intermediate = 5,
        Insane = 5,
        Tutorial = 5,
        PVP_lowRanks = 5,
        PVP_midRanks = 5,
        PVP_highRanks = 5,
        SummerEasy = 5,
        SummerMedium = 5,
        Chapter1Mission1 = 5,
        Chapter1Mission2 = 5,
        Chapter1Mission3 = 10,
        Chapter1Mission4 = 10,
        Chapter1Mission5 = 10,
        Chapter1Mission6 = 12,
        Chapter1Mission7 = 12,
        Chapter1Mission8 = 15,
    },
    Attributes = {},
}