-- Script path: ReplicatedStorage.Content.Tower.EvolvedKingpin.Stats
-- Decompile time: 2.99 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
local KingpinTooltips = require(script.KingpinTooltips)
local TowerDPS = require(ReplicatedStorage.Shared.Modules.TowerDPS)
return {
    Stats = {
        Default = {
            Defaults = {
                Price = 3600,
                Damage = 24,
                Cooldown = 1.1,
                Range = 17.5,
                Limit = 4,
                Detections = {[Enum.StatusEffect.HiddenDetection] = false},
                Abilities = {
                    {
                        Name = "Bounty",
                        Description = "Places a hit order on an enemy in range. Earn extra cash when the target pays out.",
                        Level = 4,
                        Icon = 138164251626688,
                        Debounce = 120,
                        Cooldown = 120,
                        InitialCooldown = 40,
                        Paths = {1},
                    },
                },
                Attributes = {
                    BountyCashRewardMult = 0,
                    BountyRewardCap = 10000,
                    UnitQueuesUnlocked = 1,
                    GunnerSpawnTime = 37.5,
                    GunnerUpgrade = 0,
                    MoneyRunnerSpawnTime = 40,
                    MoneyRunnerUpgrade = 0,
                    BouncerSpawnTime = 30,
                    BouncerUpgrade = 0,
                    HitmanSpawnTime = 60,
                    HitmanUpgrade = 0,
                    Buildzone = 0,
                    BodyGuardUnlocked = false,
                    BodyGuardLevel = -1,
                    BodyGuardUnitName = "KingpinBodyGuard",
                    BodyGuardDamageMeter = 0,
                    MaxBodyGuards = 0,
                    BodyGuardSpawnDeadzone = 2,
                    BodyGuardSpawnRadius = 3,
                    BountyCallTime = 2,
                },
            },
            Upgrades = {
                {
                    Image = 115111916696325,
                    Title = "Hat Trick",
                    Cost = 1400,
                    Stats = {
                        Damage = 24,
                        Cooldown = 0.85,
                        Range = 20,
                        Attributes = {
                            UnitQueuesUnlocked = 1,
                            GunnerUpgrade = 0,
                            MoneyRunnerUpgrade = 0,
                            MoneyRunnerSpawnTime = 40,
                            BouncerUpgrade = 0,
                            HitmanUpgrade = 0,
                        },
                    },
                    Tooltips = {},
                },
                {
                    Image = 128115489998324,
                    Title = "Mafia Expansion",
                    Cost = 4000,
                    Stats = {
                        Damage = 7,
                        Cooldown = 0.14,
                        Range = 20,
                        Attributes = {
                            UnitQueuesUnlocked = 2,
                            GunnerUpgrade = 0,
                            MoneyRunnerUpgrade = 0,
                            BouncerUpgrade = 0,
                            HitmanUpgrade = 0,
                        },
                    },
                    Tooltips = {KingpinTooltips.unlockNewUnitQueue(2)},
                },
                {
                    Image = 72861050225989,
                    Title = "High Roller",
                    Cost = 6000,
                    Stats = {
                        Damage = 12,
                        Cooldown = 0.14,
                        Range = 20,
                        Detections = {[Enum.StatusEffect.FlyingDetection] = true},
                        Attributes = {
                            UnitQueuesUnlocked = 2,
                            GunnerUpgrade = 0,
                            GunnerSpawnTime = 30,
                            MoneyRunnerUpgrade = 0,
                            MoneyRunnerSpawnTime = 30,
                            BouncerUpgrade = 0,
                            HitmanUpgrade = 0,
                        },
                    },
                    Tooltips = {
                        KingpinTooltips.upgradeSpawnTime("KingpinHenchman", 30),
                        (KingpinTooltips.upgradeSpawnTime("MoneyRunner", 30)),
                    },
                },
                {
                    {
                        Image = 114668237754966,
                        Title = "LV. 10 Bounty Hunter",
                        Cost = 7250,
                        Stats = {
                            Damage = 160,
                            Cooldown = 1.65,
                            Range = 20,
                            Detections = {[Enum.StatusEffect.LeadDetection] = true},
                            Attributes = {
                                BountyCashRewardMult = 0.6,
                                BountyRewardCap = 10000,
                                UnitQueuesUnlocked = 2,
                                GunnerUpgrade = 0,
                                MoneyRunnerUpgrade = 1,
                                MoneyRunnerSpawnTime = 30,
                                BouncerUpgrade = 0,
                                HitmanUpgrade = 0,
                            },
                        },
                        Tooltips = {
                            KingpinTooltips.unlockBounty(0.5, 150),
                            (KingpinTooltips.upgradeUnit("MoneyRunner", 0, 1, 30)),
                        },
                    },
                    {
                        Image = 95999047723463,
                        Title = "Underworld Backup",
                        Cost = 14000,
                        Stats = {
                            Damage = 17,
                            Cooldown = 0.12,
                            Range = 22,
                            Attributes = {
                                UnitQueuesUnlocked = 3,
                                GunnerUpgrade = 1,
                                MoneyRunnerUpgrade = 0,
                                BouncerUpgrade = 0,
                                BouncerSpawnTime = 45,
                                HitmanUpgrade = 0,
                                Buildzone = 0,
                                BodyGuardUnlocked = false,
                                BodyGuardLevel = 0,
                                BodyGuardDamageMeter = 800,
                                MaxBodyGuards = 2,
                            },
                        },
                        Tooltips = {
                            KingpinTooltips.unlockNewUnitQueue(3),
                            KingpinTooltips.unlockUnit("KingpinBouncer", 45),
                            (KingpinTooltips.upgradeUnit("KingpinHenchman", 0, 1, 30)),
                        },
                    },
                },
                {
                    {
                        Image = 132421103594393,
                        Title = "LV. 50 Flashy Business",
                        Cost = 16500,
                        Stats = {
                            Damage = 295,
                            Cooldown = 1.65,
                            Range = 20,
                            Detections = {[Enum.StatusEffect.LeadDetection] = true},
                            Attributes = {
                                BountyCashRewardMult = 0.8,
                                BountyRewardCap = 25000,
                                UnitQueuesUnlocked = 2,
                                GunnerUpgrade = 1,
                                MoneyRunnerUpgrade = 2,
                                MoneyRunnerSpawnTime = 27.5,
                                BouncerUpgrade = 0,
                                HitmanUpgrade = 0,
                            },
                        },
                        Tooltips = {
                            KingpinTooltips.upgradeBounty(0.8, 120),
                            KingpinTooltips.upgradeUnit("KingpinHenchman", 0, 1, 30),
                            (KingpinTooltips.upgradeUnit("MoneyRunner", 1, 2, 27.5)),
                        },
                    },
                    {
                        Image = 105993154736785,
                        Title = "B.P. Operations",
                        Cost = 32500,
                        Stats = {
                            Damage = 34,
                            Cooldown = 0.12,
                            Range = 23,
                            Attributes = {
                                UnitQueuesUnlocked = 3,
                                GunnerUpgrade = 2,
                                GunnerSpawnTime = 25,
                                MoneyRunnerUpgrade = 0,
                                BouncerUpgrade = 1,
                                BouncerSpawnTime = 40,
                                HitmanUpgrade = 0,
                                Buildzone = 0,
                                BodyGuardUnlocked = false,
                                BodyGuardLevel = 1,
                                BodyGuardDamageMeter = 1200,
                                MaxBodyGuards = 3,
                            },
                        },
                        Tooltips = {
                            KingpinTooltips.upgradeUnit("KingpinHenchman", 1, 2, 25),
                            (KingpinTooltips.upgradeUnit("KingpinBouncer", 0, 1, 40)),
                        },
                    },
                },
                {
                    {
                        Image = 104949216258591,
                        Title = "LV. 999 BOSS",
                        Cost = 38500,
                        Stats = {
                            Damage = 225,
                            Cooldown = 0.8,
                            Range = 21.5,
                            Attributes = {
                                BountyCashRewardMult = 1,
                                BountyRewardCap = 50000,
                                UnitQueuesUnlocked = 2,
                                GunnerUpgrade = 2,
                                MoneyRunnerUpgrade = 3,
                                MoneyRunnerSpawnTime = 25,
                                BouncerUpgrade = 0,
                                HitmanUpgrade = 0,
                            },
                        },
                        Tooltips = {
                            KingpinTooltips.upgradeBounty(1, 120),
                            KingpinTooltips.upgradeUnit("KingpinHenchman", 1, 2, 25),
                            (KingpinTooltips.upgradeUnit("MoneyRunner", 2, 3, 25)),
                        },
                    },
                    {
                        Image = 119447258450364,
                        Title = "Golden Syndicate",
                        Cost = 64000,
                        Stats = {
                            Damage = 46,
                            Cooldown = 0.1,
                            Range = 23,
                            Detections = {[Enum.StatusEffect.LeadDetection] = true},
                            Attributes = {
                                UnitQueuesUnlocked = 3,
                                GunnerUpgrade = 3,
                                GunnerSpawnTime = 25,
                                MoneyRunnerUpgrade = 1,
                                BouncerUpgrade = 2,
                                BouncerSpawnTime = 40,
                                HitmanUpgrade = 0,
                                HitmanSpawnTime = 60,
                                Buildzone = 0,
                                BodyGuardUnlocked = false,
                                BodyGuardLevel = 2,
                                BodyGuardDamageMeter = 2000,
                                MaxBodyGuards = 4,
                            },
                        },
                        Tooltips = {
                            KingpinTooltips.unlockUnit("KingpinHitman", 75),
                            KingpinTooltips.upgradeUnit("KingpinHenchman", 2, 3, 25),
                            (KingpinTooltips.upgradeUnit("KingpinBouncer", 1, 2, 40)),
                        },
                    },
                },
            },
        },
    },
    Properties = {
        DisplayName = "Kingpin",
        EvolvesFrom = "Crook Boss",
        EvolutionLevel = 20,
        Description = "Looks like they'll be... sleepin' with the fishes! A master of the criminal underworld, Kingpin can call in hit orders and deploy a variety of henchmen to do his bidding.",
        BuyAllLevelsProductId = 3610048269,
        Height = 0,
        BoundingSize = Vector3.new(0, 0, 0),
        DPS_Display = {Default = TowerDPS.Default},
        Price = {
            {Value = 15000, Type = Enum.CurrencyType.Coins},
            {Value = 5500, Type = Enum.CurrencyType.Gems},
        },
        Role = Enum.TowerRole.Offense,
        Preview = {
            FieldOfView = 60,
            TowerOffset = Vector3.new(0, 0, 0),
            Icon = 6883304439,
            Thumbnail = 0,
            TowerRotation = CFrame.Angles(0, 2.792526803190927, 0),
            CameraOffset = CFrame.new(0, 0, 6),
        },
        Progression = {MaxLevel = 20, BaseExp = 75, GrowthRate = 1.075},
        UpgradeUnlockTree = {
            DefaultUnlockedThrough = 4,
            Nodes = {
                Upgrade5A = {
                    DisplayName = "LV. 50 Flashy Business",
                    Level = 5,
                    Path = 1,
                    RequiredTowerLevel = 5,
                    Coordinate = {q = 5, r = -1},
                },
                Upgrade5B = {
                    DisplayName = "B.P. Operations",
                    Level = 5,
                    Path = 2,
                    RequiredTowerLevel = 10,
                    Coordinate = {q = 4, r = 1},
                },
                Upgrade6A = {
                    DisplayName = "LV. 999 BOSS",
                    Level = 6,
                    Path = 1,
                    RequiredTowerLevel = 15,
                    PreviousNode = "Upgrade5A",
                    Coordinate = {q = 6, r = -1},
                },
                Upgrade6B = {
                    DisplayName = "Golden Syndicate",
                    Level = 6,
                    Path = 2,
                    RequiredTowerLevel = 20,
                    PreviousNode = "Upgrade5B",
                    Coordinate = {q = 5, r = 1},
                },
            },
        },
        Category = Enum.TowerCategory.Evolved,
        SkinData = {},
    },
}