-- Script path: ReplicatedStorage.Content.NewEnemies.Narrator.Stats
-- Decompile time: 0.56 ms

return {
    RageModeDebounce = 5,
    Speed = 0.75,
    Scale = 1.45,
    Health = 1250000,
    RewardThreshold = 0.01,
    Phase2Threshold = 0.5,
    DeathTime = 5.2,
    Description = "The Narrator is a performer from the Old World who used to be the right-hand man of Lord Exo. After being used for his revival, he achieved his theatrical moment on stage, striking a deal with Commander. He relies on his hands Righty and Lefty who were empowered by Lord Exo, making them some of the most powerful entities in existence.",
    HealthPerDifficulty = {Easy = 225000, Hard = 1250000},
    Reward = {Easy = 400000, Hard = 1000000},
    Attributes = {},
    Hands = {Left = {Offset = CFrame.new(-5, 2.3, 3)}, Right = {Offset = CFrame.new(5, 2, 3)}},
    Moveset = {
        HandSlam = {
            Range = 0,
            HitRadius = 12.5,
            Damage = 75000,
            StunTime = 5,
            phase2Only = false,
            Cooldown = 25,
            AfterCooldown = 5,
        },
        HandLaser = {
            Range = 0,
            CheckRadius = 50,
            HitRadius = 1.2,
            Duration = 3,
            RangeDebuff = 25,
            CooldownDebuff = 25,
            DebuffDuration = 22.5,
            phase2Only = false,
            Cooldown = 36,
            AfterCooldown = 2,
        },
        BossBaseAttack = {
            Range = 0,
            BaseDamage = 40,
            SpotLightTime = 2,
            StunTime = 3,
            Cooldown = 37.5,
            AfterCooldown = 2,
            DefaultChargeTime = 15,
            PlayersFormat = {20, 15, 13.5, 12.5},
        },
        HandSummon = {
            Range = 0,
            CheckRadius = 50,
            HitRadius = 0.5,
            Duration = 3,
            phase2Only = false,
            Cooldown = 35,
            AfterCooldown = 2,
            Spawns = {MiniHand = {amount = 3}},
        },
    },
}