-- Script path: ReplicatedStorage.Content.Challenges.BackToBasics
-- Decompile time: 4.35 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage = game:GetService("ServerStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    title = "Back to Basics",
    description = "Players are given a loadout of basic towers.",
    difficulty = "Fallen",
    startingCash = 700,
    gameModifier = Enum.GameModifier.BackToBasics,
    maps = {"Sky Islands", "Portland", "Autumn Falling", "Dusty Bridges", "Four Seasons"},
    onServerLoad = function() -- Line: 12 -- upvalues: ServerStorage (val)
        return require(ServerStorage.Server.Services.Game.GlobalModifierService).compose().addModifier("NoDialogue").complete()
    end,
    challengeRewards = {
        gems = 125,
        experience = 400,
        crates = {{type = "High Grade", amount = 3}},
        tickets = {Timescale = 3},
    },
    overrideLoadout = {
        Scout = {Skin = "Default", GoldenPerks = false, Order = 1},
        Demoman = {Skin = "Default", GoldenPerks = false, Order = 2},
        Sniper = {Skin = "Default", GoldenPerks = false, Order = 3},
        Soldier = {Skin = "Default", GoldenPerks = false, Order = 4},
        Hunter = {Skin = "Default", GoldenPerks = false, Order = 5},
    },
    enemyReplaceList = {
        ["Fallen Skeleton"] = "Skeleton",
        ["Necrotic Skeleton"] = "Breaker4",
        ["Possessed Armor"] = "Fallen",
    },
    enemyReplaceHealthList = {
        ["Fallen Hero"] = 2000,
        ["Fallen Tank"] = 4000,
        ["Fallen Rusher"] = 300,
        Templar = 4000,
        ["Fallen Summoner"] = 6000,
        ["Fallen Necromancer"] = 500,
        ["Fallen Guardian"] = 6000,
        ["Fallen King"] = 60000,
        ["Normal Boss"] = 175,
        ["Fallen Giant"] = 2000,
        ["Hidden Boss"] = 750,
        Bolt = 240,
        Abnormal = 6,
        Quick = 4,
        Heavy = 16,
        Breaker2 = 50,
        Fallen = 180,
        Hidden = 20,
        Hazmat = 250,
        Boomer = 2000,
        Skeleton = 35,
    },
    waveEnemiesOverride = {
        [2] = {
            {Name = "Quick", Delay = 0.5, Amount = 1},
            {Name = "Abnormal", Delay = 0.5, Amount = 4},
            {Name = "Quick", Delay = 0.5, Amount = 1},
        },
        [3] = {
            {
                Name = "Abnormal",
                Delay = 0.5,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Abnormal", Delay = 0.5, Amount = 5},
            {Name = "Quick", Delay = 0.5, Amount = 3},
        },
        [4] = {
            {
                Name = "Abnormal",
                Delay = 0.5,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Abnormal", Delay = 0.4, Amount = 10},
            {
                Name = "Abnormal",
                Delay = 0.5,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        [5] = {
            {Name = "Quick", Delay = 0.5, Amount = 10},
            {
                Name = "Abnormal",
                Delay = 0.3,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        [6] = {
            {Name = "Quick", Delay = 0.7, Amount = 4, Time = 0.5},
            {Name = "Abnormal", Delay = 0.5, Amount = 7},
        },
        [7] = {
            {
                Name = "Heavy",
                Delay = 0.7,
                Amount = 5,
                Time = 0.7,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Heavy", Delay = 0.6, Amount = 5},
        },
        [8] = {
            {
                Name = "Quick",
                Delay = 0.8,
                Amount = 6,
                Time = 0.8,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Heavy", Delay = 0.6, Amount = 6},
            {
                Name = "Abnormal",
                Delay = 0.4,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
        },
        [9] = {
            {Name = "Heavy", Delay = 0.6, Amount = 6, Time = 0.6},
            {
                Name = "Abnormal",
                Delay = 0.5,
                Amount = 10,
                Time = 1.5,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Quick",
                Delay = 0.5,
                Amount = 7,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
        },
        [10] = {
            {
                Name = "Abnormal",
                Delay = 0.5,
                Amount = 12,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Heavy", Delay = 0.5, Amount = 6},
            {Name = "Normal Boss", Delay = 0.6, Amount = 1},
        },
        [11] = {
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 8,
                Time = 1.2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Abnormal",
                Delay = 0.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Quick",
                Delay = 0.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        [12] = {
            {
                Name = "Normal Boss",
                Delay = 0.5,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Abnormal",
                Delay = 0.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        [13] = {{Name = "Hidden", Delay = 0.5, Amount = 10}},
        [14] = {
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 12,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Normal Boss",
                Delay = 0.6,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
        },
        [15] = {{Name = "Hidden", Delay = 0.5, Amount = 20}},
        [16] = {{Name = "Breaker2", Delay = 0.5, Amount = 8}},
        [17] = {
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 6,
                Time = 1.2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Breaker2", Delay = 0.5, Amount = 7},
        },
        [18] = {{Name = "Breaker2", Delay = 0.5, Amount = 14}},
        [19] = {
            {
                Name = "Heavy",
                Delay = 0.3,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Quick",
                Delay = 0.4,
                Amount = 6,
                Time = 0.4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Hidden", Delay = 0.5, Amount = 4},
            {Name = "Breaker2", Delay = 0.5, Amount = 3},
            {
                Name = "Normal Boss",
                Delay = 0.8,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Fallen Necromancer", Delay = 0.6, Amount = 1},
        },
        [20] = {
            {Name = "Fallen", Delay = 0.5, Amount = 4},
            {
                Name = "Normal Boss",
                Delay = 0.6,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
        },
        [21] = {
            {Name = "Breaker2", Delay = 0.5, Amount = 7, Time = 0.5},
            {Name = "Fallen", Delay = 0.5, Amount = 5},
            {
                Name = "Normal Boss",
                Delay = 0.8,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Hidden", Delay = 0.5, Amount = 4},
        },
        [22] = {
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 8,
                Time = 0,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Hidden", Delay = 0.5, Amount = 4},
            {Name = "Breaker2", Delay = 0.5, Amount = 8},
            {
                Name = "Normal Boss",
                Delay = 0.7,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Fallen Giant", Delay = 1, Amount = 1},
        },
        [23] = {
            {Name = "Fallen", Delay = 0.5, Amount = 6, Time = 0.5},
            {Name = "Fallen Giant", Delay = 1.5, Amount = 1},
            {Name = "Breaker2", Delay = 0.5, Amount = 8, Time = 0.7},
            {Name = "Fallen Necromancer", Delay = 0.8, Amount = 1},
        },
        [24] = {
            {
                Name = "Fallen",
                Delay = 0.5,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
            {Name = "Breaker2", Delay = 0.4, Amount = 8},
            {Name = "Hidden Boss", Delay = 0.5, Amount = 1},
        },
        [25] = {
            {
                Name = "Fallen",
                Delay = 1.5,
                Amount = 12,
                Time = 0.5,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
            {Name = "Heavy", Delay = 0.5, Amount = 4},
            {Name = "Breaker2", Delay = 0.5, Amount = 6},
            {Name = "Fallen Necromancer", Delay = 0.6, Amount = 4},
        },
        [26] = {{Name = "Bolt", Delay = 0.5, Amount = 12}},
        [27] = {
            {Name = "Bolt", Delay = 0.5, Amount = 10},
            {Name = "Fallen", Delay = 0.5, Amount = 8},
            {Name = "Breaker2", Delay = 0.4, Amount = 8},
            {Name = "Normal Boss", Delay = 0.5, Amount = 4},
        },
        [28] = {
            {Name = "Hazmat", Delay = 0.5, Amount = 13},
            {Name = "Fallen Giant", Delay = 1, Amount = 2},
            {Name = "Breaker2", Delay = 0.5, Amount = 10},
            {Name = "Bolt", Delay = 0.5, Amount = 10},
        },
        [29] = {
            {Name = "Fallen Giant", Delay = 1, Amount = 1},
            {Name = "Breaker2", Delay = 0.5, Amount = 10},
            {Name = "Bolt", Delay = 0.5, Amount = 12},
            {Name = "Fallen", Delay = 0.5, Amount = 12},
            {Name = "Hazmat", Delay = 0.5, Amount = 4},
        },
        [30] = {
            {Name = "Fallen", Delay = 0.5, Amount = 5},
            {Name = "Hazmat", Delay = 0.5, Amount = 4},
            {Name = "Normal Boss", Delay = 0.5, Amount = 4},
            {Name = "Hidden Boss", Delay = 1, Amount = 2},
            {Name = "Breaker2", Delay = 0.5, Amount = 10},
            {Name = "Bolt", Delay = 0.5, Amount = 9},
            {Time = 2, Name = "Fallen Tank", Delay = 2, Amount = 1},
            {Name = "Breaker2", Delay = 0.5, Amount = 10},
        },
        [31] = {
            {Name = "Fallen Giant", Delay = 1, Amount = 5},
            {Name = "Hazmat", Delay = 0.5, Amount = 13},
            {Name = "Fallen", Delay = 0.5, Amount = 10},
            {Name = "Fallen Necromancer", Delay = 1, Amount = 1},
        },
        [32] = {
            {Name = "Fallen Giant", Delay = 1, Amount = 3},
            {Name = "Breaker2", Delay = 0.5, Amount = 8},
            {Name = "Fallen Tank", Delay = 0.5, Amount = 1},
            {Name = "Breaker4", Delay = 0.8, Amount = 10},
        },
        [33] = {
            {Name = "Fallen Giant", Delay = 1, Amount = 6},
            {Name = "Bolt", Delay = 0.5, Amount = 24},
            {Name = "Breaker2", Delay = 0.5, Amount = 10},
            {Name = "Breaker4", Delay = 0.8, Amount = 12},
            {Name = "Fallen Necromancer", Delay = 0.8, Amount = 1},
            {Name = "Hidden Boss", Delay = 1, Amount = 3},
        },
        [34] = {
            {Name = "Fallen Giant", Delay = 1, Amount = 8},
            {Name = "Boomer", Delay = 0.8, Amount = 1},
            {Name = "Bolt", Delay = 0.5, Amount = 8},
            {Name = "Breaker2", Delay = 0.5, Amount = 6},
            {Name = "Hazmat", Delay = 0.5, Amount = 6},
            {Name = "Fallen", Delay = 0.5, Amount = 8},
            {Name = "Breaker4", Delay = 0.8, Amount = 14},
        },
        [35] = {
            {Name = "Templar", Delay = 3, Amount = 1},
            {Name = "Hazmat", Delay = 0.5, Amount = 5},
            {Name = "Breaker4", Delay = 0.8, Amount = 20},
        },
        [36] = {
            {Name = "Fallen Giant", Delay = 1, Amount = 8},
            {Name = "Boomer", Delay = 1.5, Amount = 1},
            {Name = "Bolt", Delay = 0.3, Amount = 8},
            {Name = "Fallen Tank", Delay = 2, Amount = 1},
            {Name = "Fallen Rusher", Delay = 0.3, Amount = 8},
            {Name = "Fallen Summoner", Delay = 1.5, Amount = 1},
        },
        [37] = {
            {Name = "Boomer", Delay = 1.6, Amount = 1},
            {Name = "Bolt", Delay = 0.5, Amount = 10},
            {Name = "Fallen Rusher", Delay = 0.3, Amount = 6},
            {Name = "Fallen Giant", Delay = 1, Amount = 6},
            {Name = "Hidden Boss", Delay = 1, Amount = 2},
            {Name = "Hazmat", Delay = 0.5, Amount = 6},
            {Name = "Fallen Rusher", Delay = 0.3, Amount = 6},
            {Name = "Fallen", Delay = 0.5, Amount = 6},
            {Name = "Templar", Delay = 3, Amount = 1},
            {Name = "Fallen Summoner", Delay = 3, Amount = 2},
            {Name = "Fallen Rusher", Delay = 0.3, Amount = 6},
        },
        [38] = {
            {Name = "Boomer", Delay = 1.6, Amount = 1},
            {Name = "Bolt", Delay = 0.5, Amount = 10},
            {Name = "Fallen Rusher", Delay = 0.3, Amount = 6},
            {Name = "Fallen Giant", Delay = 1, Amount = 6},
            {Name = "Hidden Boss", Delay = 1, Amount = 2},
            {Name = "Hazmat", Delay = 0.5, Amount = 6},
            {Name = "Fallen Rusher", Delay = 0.3, Amount = 6},
            {Name = "Fallen", Delay = 0.5, Amount = 6},
            {Name = "Templar", Delay = 3, Amount = 1},
            {Name = "Fallen Summoner", Delay = 3, Amount = 2},
            {Name = "Fallen Rusher", Delay = 0.3, Amount = 6},
        },
        [39] = {
            {Name = "Boomer", Delay = 0.8, Amount = 2},
            {Name = "Fallen Tank", Delay = 2.5, Amount = 2},
            {Name = "Fallen Rusher", Delay = 0.3, Amount = 6},
            {Name = "Bolt", Delay = 0.1, Amount = 10},
            {Name = "Templar", Delay = 3, Amount = 1},
            {Name = "Hazmat", Delay = 0.5, Amount = 10},
            {Name = "Fallen Rusher", Delay = 0.3, Amount = 2},
            {Name = "Fallen", Delay = 0.4, Amount = 15},
            {Name = "Fallen Rusher", Delay = 0.4, Amount = 9},
            {Name = "Fallen Hero", Delay = 1.5, Amount = 7},
            {Name = "Fallen", Delay = 0.4, Amount = 5},
            {Name = "Fallen Summoner", Delay = 2, Amount = 1},
            {Name = "Fallen Rusher", Delay = 0.4, Amount = 9},
        },
        [40] = {
            {Name = "Fallen Hero", Delay = 1.3, Amount = 3},
            {Name = "Templar", Delay = 4, Amount = 1},
            {Name = "Bolt", Delay = 0.1, Amount = 6},
            {Name = "Fallen Rusher", Delay = 0.3, Amount = 9},
            {Name = "Fallen", Delay = 0.35, Amount = 10},
            {Name = "Fallen Giant", Delay = 1, Amount = 5},
            {Name = "Fallen Rusher", Delay = 0.4, Amount = 6},
            {Name = "Fallen Guardian", Delay = 2, Amount = 4},
            {Name = "Fallen King", Delay = 2, Amount = 1},
            {Name = "Fallen Hero", Delay = 1, Amount = 2},
            {Name = "Fallen Giant", Delay = 1, Amount = 4},
            {Name = "Breaker4", Delay = 0.8, Amount = 7},
            {Name = "Fallen Rusher", Delay = 0.4, Amount = 1},
        },
    },
}