-- Script path: ReplicatedStorage.Content.Challenges.BossRush
-- Decompile time: 13.69 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage = game:GetService("ServerStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    title = "Boss Rush",
    description = "All the bosses after teamed up to take you down! Can you survive the onslaught?",
    disabled = true,
    startingCash = 900,
    gameModifier = Enum.GameModifier.BossRush,
    maps = {"Wrecked Battlefield", "Sacred Mountains", "Winter Abyss", "Ruby Escort"},
    onServerLoad = function() -- Line: 11 -- upvalues: ServerStorage (val)
        return require(ServerStorage.Server.Services.Game.GlobalModifierService).compose().addModifier("NoDialogue").complete()
    end,
    challengeRewards = {
        gems = 150,
        experience = 500,
        consumables = {{type = "Nuke", amount = 3}},
        tickets = {Timescale = 4},
    },
    waveCash = function(a1) -- Line: 35
        local v1 = 205 + (100 * a1 - 1)
        if a1 < 11 then
            return 205 + (100 * a1 - 1)
        end
        if a1 > 11 then
            v1 = 205 + (50 * a1 - 1)
        end
        return v1
    end,
    enemyReplaceHealthList = {
        ["Normal Boss"] = 160,
        ["Grave Digger"] = 10000,
        ["Fallen Hero"] = 5000,
        ["Fallen Guardian"] = 14000,
        ["Fallen King"] = 75000,
        Abnormal = 6,
        Quick = 4,
        Heavy = 16,
        ["Abnormal Boss"] = 175,
        Breaker2 = 50,
        Necromancer = 400,
        Fallen = 180,
    },
    waveEnemiesOverride = {
        {{Name = "Speedy", Amount = 2, Delay = 0.5}, {Name = "Normal", Amount = 6, Delay = 0.8}},
        {
            {Name = "Slow", Amount = 3, Delay = 0.5},
            {Name = "Normal", Amount = 10, Delay = 0.65},
            {Name = "Speedy", Amount = 5, Delay = 0.8},
        },
        {
            {Name = "Slow", Amount = 8, Delay = 0.5},
            {Name = "Normal", Amount = 15, Delay = 0.65},
            {Name = "Speedy", Amount = 10, Delay = 0.8},
        },
        {
            {Name = "Slow", Amount = 8, Delay = 0.5},
            {
                Name = "Normal Boss",
                Amount = 1,
                Delay = 0.8,
                Modifiers = {[Enum.Modifier.Boss] = true},
            },
        },
        {
            {Name = "Normal", Amount = 10, Delay = 0.5},
            {Name = "Slow", Amount = 10, Delay = 0.6},
            {Name = "Normal Boss", Amount = 1, Delay = 0.8},
            {Name = "Speedy", Amount = 5, Delay = 0.5},
        },
        {
            {Name = "Slow", Amount = 5, Delay = 0.6},
            {Name = "Normal Boss", Amount = 2, Delay = 0.5},
            {Name = "Speedy", Amount = 20, Delay = 0.8},
        },
        {
            {Name = "Slow", Amount = 12, Delay = 0.5},
            {Name = "Breaker2", Amount = 5, Delay = 0.7},
            {Name = "Speedy", Amount = 10, Delay = 0.5},
        },
        {{Name = "Breaker2", Amount = 6, Delay = 1}, {Name = "Hidden", Amount = 10, Delay = 0.6}},
        {
            {Name = "Hidden", Amount = 4, Delay = 0.5},
            {Name = "Breaker2", Amount = 5, Delay = 0.5},
            {Name = "Slow", Amount = 4, Delay = 0.6},
            {Name = "Normal Boss", Amount = 1, Delay = 0.6},
            {Name = "Speedy", Amount = 4, Delay = 0.7},
            {Name = "Necromancer", Amount = 1, Delay = 0.8},
        },
        {
            {Name = "Normal", Amount = 20, Delay = 0.1},
            {Name = "Armored", Amount = 8, Delay = 0.5},
            {Name = "Breaker2", Amount = 12, Delay = 0.5},
            {
                Name = "Grave Digger",
                Amount = 1,
                Delay = 1,
                Modifiers = {[Enum.Modifier.Boss] = true},
            },
        },
        {
            {Name = "Normal Boss", Delay = 0.8, Amount = 2},
            {Name = "Slow", Delay = 0.6, Amount = 8},
            {Name = "Hidden", Delay = 0.5, Amount = 4},
            {Name = "Breaker2", Delay = 0.5, Amount = 5},
            {Name = "Molten", Delay = 0.5, Amount = 5},
        },
        {
            {Name = "Molten", Delay = 0.5, Amount = 6},
            {Name = "Slow Boss", Delay = 0.8, Amount = 1},
            {Name = "Breaker2", Delay = 0.5, Amount = 4},
            {Name = "Necromancer", Delay = 0.8, Amount = 1},
        },
        {
            {Name = "Molten", Delay = 0.5, Amount = 12},
            {Name = "Hidden Boss", Delay = 1, Amount = 1},
            {Name = "Necromancer", Delay = 0.8, Amount = 2},
        },
        {
            {Name = "Shock", Delay = 0.5, Amount = 10},
            {Name = "Molten", Delay = 0.5, Amount = 8},
            {Name = "Normal Boss", Delay = 0.8, Amount = 4},
        },
        {
            {Name = "Slow Boss", Delay = 1, Amount = 2},
            {Name = "Shock", Delay = 0.5, Amount = 10},
            {Name = "Necromancer", Delay = 0.8, Amount = 2},
            {Name = "Hidden Boss", Delay = 1, Amount = 2},
        },
        {
            {Name = "Slow Boss", Delay = 1, Amount = 1},
            {Name = "Breaker2", Delay = 0.5, Amount = 10},
            {Name = "Shock", Delay = 0.5, Amount = 12},
            {Name = "Molten", Delay = 0.5, Amount = 12},
        },
        {
            {Name = "Molten", Delay = 0.5, Amount = 10},
            {Name = "Normal Boss", Delay = 0.8, Amount = 4},
            {Name = "Hidden Boss", Delay = 1, Amount = 2},
            {Name = "Hidden", Delay = 0.5, Amount = 4},
            {Name = "Slow", Delay = 0.5, Amount = 4},
            {Name = "Shock", Delay = 0.5, Amount = 9},
            {Name = "Speedy Boss", Delay = 1, Amount = 1},
        },
        {
            {Name = "Slow Boss", Delay = 1, Amount = 6},
            {Name = "Speedy Boss", Delay = 1, Amount = 1},
            {Name = "Molten", Delay = 0.5, Amount = 10},
            {Name = "Necromancer", Delay = 0.8, Amount = 1},
        },
        {
            {Name = "Slow Boss", Delay = 1, Amount = 3},
            {Name = "Breaker2", Delay = 0.5, Amount = 8},
            {Name = "Speedy Boss", Delay = 0.8, Amount = 1},
            {Name = "Breaker4", Delay = 0.8, Amount = 7},
        },
        {
            {Name = "Molten", Delay = 0.5, Amount = 20},
            {Name = "Molten Titan", Delay = 1, Amount = 5},
            {
                Name = "Molten Boss",
                Delay = 1,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Boss] = true},
            },
        },
        {
            {
                Name = "Enraged",
                Amount = 15,
                Delay = 1.2,
                Time = 2.4,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.HealthRegen] = true,
                },
            },
            {
                Name = "Hazmat",
                Amount = 4,
                Delay = 0.5,
                Time = 1.5,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
            {
                Name = "Hidden Boss",
                Amount = 3,
                Delay = 1.2,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
            {
                Name = "Hazmat",
                Amount = 6,
                Delay = 1.2,
                Time = 1.5,
                Modifiers = {[Enum.Modifier.Hidden] = true},
            },
            {Name = "Breaker2", Amount = 10, Delay = 1.2, Time = 1.5},
            {Name = "Failed Experiment", Amount = 1, Delay = 0.8},
        },
        {
            {
                Name = "Hidden Boss",
                Amount = 3,
                Delay = 2.5,
                Time = 0.2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Armored",
                Amount = 20,
                Delay = 1.2,
                Time = 1.2,
                Modifiers = {[Enum.Modifier.Slime] = true, [Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Breaker2",
                Amount = 18,
                Delay = 1.2,
                Time = 1.2,
                Modifiers = {[Enum.Modifier.Slime] = true, [Enum.Modifier.Hidden] = true},
            },
            {
                Name = "Hazmat",
                Amount = 8,
                Delay = 0.8,
                Time = 2.4,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
            {
                Name = "Necromancer",
                Amount = 1,
                Delay = 0.6,
                Time = 1,
                Modifiers = {
                    [Enum.Modifier.Slime] = true,
                    [Enum.Modifier.HealthRegen] = true,
                },
            },
        },
        {
            {
                Name = "Armored",
                Amount = 40,
                Delay = 0.5,
                Time = 2,
                Modifiers = {
                    [Enum.Modifier.HealthRegen] = true,
                    [Enum.Modifier.Bloated] = true,
                },
            },
            {Name = "Hidden Boss", Amount = 1, Delay = 1},
            {
                Name = "Ghoul",
                Amount = 10,
                Delay = 0.6,
                Time = 3,
                Modifiers = {[Enum.Modifier.Slime] = true, [Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Hidden Boss",
                Amount = 1,
                Delay = 1,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Living Experiment",
                Amount = 1,
                Delay = 1,
                Modifiers = {[Enum.Modifier.HealthRegen] = true},
            },
            {
                Name = "Reaver",
                Amount = 4,
                Delay = 1.2,
                Time = 6,
                Modifiers = {[Enum.Modifier.HealthRegen] = true},
            },
            {Name = "Failed Experiment", Amount = 1, Delay = 1, Time = 1},
        },
        {
            {
                Name = "Hazmat",
                Amount = 20,
                Delay = 1.5,
                Time = 1.5,
                Modifiers = {[Enum.Modifier.HealthRegen] = true},
            },
            {
                Name = "Hidden Boss",
                Amount = 3,
                Delay = 0.7,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Failed Experiment", Amount = 1, Delay = 1},
            {
                Name = "Living Experiment",
                Amount = 1,
                Delay = 1,
                Modifiers = {[Enum.Modifier.HealthRegen] = true},
            },
            {
                Name = "Reaver",
                Amount = 6,
                Delay = 0.8,
                Time = 3,
                Modifiers = {[Enum.Modifier.HealthRegen] = true},
            },
            {
                Name = "Enraged",
                Amount = 10,
                Delay = 0.2,
                Time = 3,
                Modifiers = {
                    [Enum.Modifier.HealthRegen] = true,
                    [Enum.Modifier.Bloated] = true,
                },
            },
            {
                Name = "Necromancer",
                Amount = 3,
                Delay = 1.2,
                Modifiers = {[Enum.Modifier.HealthRegen] = true},
            },
        },
        {
            {
                Name = "Enraged",
                Amount = 32,
                Delay = 1,
                Time = 2,
                Modifiers = {
                    [Enum.Modifier.Nimble] = true,
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Hidden] = true,
                },
            },
            {
                Name = "Breaker2",
                Amount = 10,
                Delay = 1,
                Time = 1,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Hidden] = true,
                },
            },
            {
                Name = "Enraged",
                Amount = 10,
                Delay = 1,
                Time = 2,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Hidden] = true,
                },
            },
            {
                Name = "Ghoul",
                Amount = 5,
                Delay = 1,
                Time = 1,
                Modifiers = {[Enum.Modifier.Slime] = true, [Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Reaver",
                Amount = 5,
                Delay = 1.2,
                Time = 2,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Nimble] = true,
                },
            },
            {
                Name = "Hazmat",
                Amount = 10,
                Delay = 1.2,
                Time = 2.4,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Failed Experiment", Amount = 2, Delay = 2},
        },
        {
            {Name = "Failed Experiment", Amount = 2, Delay = 3, Time = 0.1},
            {
                Name = "Slime",
                Amount = 2,
                Delay = 0.8,
                Time = 3,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Hidden] = true,
                },
            },
            {
                Name = "Hidden Boss",
                Amount = 3,
                Delay = 1,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Ghoul",
                Amount = 6,
                Delay = 1.2,
                Time = 0.1,
                Modifiers = {[Enum.Modifier.Slime] = true, [Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Reaver",
                Amount = 4,
                Delay = 0.8,
                Modifiers = {
                    [Enum.Modifier.Nimble] = true,
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Hidden] = true,
                },
            },
            {
                Name = "Armored",
                Amount = 50,
                Delay = 0.6,
                Time = 1.2,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Slime] = true,
                    [Enum.Modifier.HealthRegen] = true,
                },
            },
            {Name = "Living Experiment", Amount = 2, Delay = 2},
            {
                Name = "Necromancer",
                Amount = 4,
                Delay = 1.2,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
        },
        {
            {
                Name = "Hidden Boss",
                Amount = 2,
                Delay = 1.5,
                Time = 0.1,
                Modifiers = {
                    [Enum.Modifier.Nimble] = true,
                    [Enum.Modifier.Slime] = true,
                    [Enum.Modifier.HealthRegen] = true,
                },
            },
            {
                Name = "Living Experiment",
                Amount = 5,
                Delay = 3,
                Time = 2,
                Modifiers = {[Enum.Modifier.HealthRegen] = true},
            },
            {Name = "Failed Experiment", Amount = 1, Delay = 2},
            {
                Name = "Hidden Boss",
                Amount = 2,
                Delay = 1.5,
                Time = 0.1,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Slime] = true,
                    [Enum.Modifier.HealthRegen] = true,
                },
            },
            {
                Name = "Armored",
                Amount = 15,
                Delay = 0.2,
                Modifiers = {
                    [Enum.Modifier.Nimble] = true,
                    [Enum.Modifier.Bloated] = true,
                },
            },
            {
                Name = "Necromancer",
                Amount = 3,
                Delay = 0.8,
                Modifiers = {[Enum.Modifier.Bloated] = true, [Enum.Modifier.Slime] = true},
            },
        },
        {
            {
                Name = "Reaver",
                Amount = 10,
                Delay = 1.6,
                Time = 3.2,
                Modifiers = {
                    [Enum.Modifier.HealthRegen] = true,
                    [Enum.Modifier.Bloated] = true,
                },
            },
            {
                Name = "Ghoul",
                Amount = 12,
                Delay = 0.8,
                Time = 0.8,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Living Experiment",
                Amount = 1,
                Delay = 1,
                Modifiers = {[Enum.Modifier.HealthRegen] = true},
            },
            {
                Name = "Breaker4",
                Amount = 10,
                Delay = 1.2,
                Time = 2.4,
                Modifiers = {[Enum.Modifier.HealthRegen] = true},
            },
            {
                Name = "Living Experiment",
                Amount = 1,
                Delay = 1,
                Modifiers = {[Enum.Modifier.HealthRegen] = true},
            },
            {
                Name = "Breaker2",
                Amount = 15,
                Delay = 0.5,
                Modifiers = {[Enum.Modifier.HealthRegen] = true},
            },
            {Name = "Failed Experiment", Amount = 2, Delay = 1.8},
        },
        {
            {
                Name = "Reaver",
                Amount = 6,
                Delay = 1.6,
                Time = 3.2,
                Modifiers = {
                    [Enum.Modifier.HealthRegen] = true,
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Slime] = true,
                },
            },
            {
                Name = "Ghoul",
                Amount = 10,
                Delay = 1.2,
                Time = 2.4,
                Modifiers = {[Enum.Modifier.Bloated] = true, [Enum.Modifier.Slime] = true},
            },
            {
                Name = "Slime",
                Amount = 1,
                Delay = 0.8,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Hidden] = true,
                },
            },
            {
                Name = "Living Experiment",
                Amount = 3,
                Delay = 2,
                Time = 2,
                Modifiers = {[Enum.Modifier.Bloated] = true, [Enum.Modifier.Slime] = true},
            },
            {
                Name = "Slime",
                Amount = 1,
                Delay = 0.8,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Hidden] = true,
                },
            },
            {
                Name = "Breaker4",
                Amount = 10,
                Delay = 0.8,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Slime",
                Amount = 1,
                Delay = 0.8,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Hidden] = true,
                },
            },
            {
                Name = "Necromancer",
                Amount = 2,
                Delay = 0.8,
                Modifiers = {
                    [Enum.Modifier.HealthRegen] = true,
                    [Enum.Modifier.Bloated] = true,
                },
            },
            {
                Name = "Hidden Boss",
                Amount = 4,
                Delay = 0.8,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
        },
        {
            {
                Name = "Ghoul",
                Amount = 25,
                Delay = 1.6,
                Time = 0.8,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Slime",
                Amount = 5,
                Delay = 1.8,
                Time = 1.8,
                Modifiers = {[Enum.Modifier.Hidden] = true, [Enum.Modifier.Tank] = true},
            },
            {
                Name = "Failed Experiment",
                Amount = 2,
                Delay = 4,
                Time = 2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Patient Zero", Amount = 1, Delay = 1},
            {
                Name = "Reaver",
                Amount = 1,
                Delay = 0.2,
                Modifiers = {
                    [Enum.Modifier.Slime] = true,
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.HealthRegen] = true,
                },
            },
            {
                Name = "Living Experiment",
                Amount = 1,
                Delay = 1,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.HealthRegen] = true,
                },
            },
            {
                Name = "Reaver",
                Amount = 1,
                Delay = 0.2,
                Modifiers = {
                    [Enum.Modifier.Slime] = true,
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.HealthRegen] = true,
                },
            },
            {
                Name = "Living Experiment",
                Amount = 1,
                Delay = 1,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.HealthRegen] = true,
                },
            },
            {
                Name = "Reaver",
                Amount = 1,
                Delay = 1,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.Slime] = true,
                    [Enum.Modifier.HealthRegen] = true,
                },
            },
            {
                Name = "Living Experiment",
                Amount = 1,
                Delay = 1,
                Modifiers = {
                    [Enum.Modifier.Bloated] = true,
                    [Enum.Modifier.HealthRegen] = true,
                },
            },
        },
        [40] = {
            {Name = "Fallen Hero", Delay = 1.3, Amount = 3},
            {Name = "Warden", Delay = 4, Amount = 1},
            {Name = "Glitch", Delay = 0.1, Amount = 6},
            {Name = "Error", Delay = 0.3, Amount = 9},
            {Name = "Fallen", Delay = 0.35, Amount = 10},
            {Name = "Giant Boss", Delay = 1, Amount = 5},
            {Name = "Error", Delay = 0.4, Amount = 6},
            {Name = "Fallen Guardian", Delay = 2, Amount = 4},
            {
                Name = "Fallen King",
                Delay = 2,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Boss] = true},
            },
            {Name = "Fallen Hero", Delay = 1, Amount = 2},
            {Name = "Giant Boss", Delay = 1, Amount = 4},
            {Name = "Breaker4", Delay = 0.8, Amount = 7},
            {Name = "Error", Delay = 0.4, Amount = 1},
        },
        [41] = {
            {Name = "lava", Delay = 0.5, Amount = 12},
            {Name = "Mega Slow", Delay = 1.25, Amount = 6},
            {Name = "Giant Boss", Delay = 1.25, Amount = 4},
            {Name = "Slow King", Delay = 1.5, Amount = 4},
            {Name = "Breaker2", Delay = 0.3, Amount = 5},
        },
        [42] = {
            {Name = "Breaker2", Delay = 0.4, Amount = 15},
            {Name = "Error", Delay = 0.4, Amount = 7},
            {Name = "Lead Balloon", Delay = 0.5, Amount = 6},
            {Name = "Breaker4", Delay = 0.8, Amount = 8},
            {Name = "Mega Slow", Delay = 1.25, Amount = 5},
            {Name = "Slow King", Delay = 1, Amount = 5},
            {Name = "Fallen Reaper", Delay = 0.4, Amount = 6},
        },
        [43] = {
            {Name = "Error", Delay = 0.3, Amount = 8},
            {Name = "Circuit", Delay = 0.5, Amount = 1},
            {Name = "Lava", Delay = 0.6, Amount = 16},
            {Name = "Lead Balloon", Delay = 0.3, Amount = 8},
            {Name = "Lead Boss", Delay = 0.5, Amount = 12},
            {Name = "Slow King", Delay = 1.5, Amount = 2},
            {Name = "Speedy King", Delay = 1.2, Amount = 3},
        },
        [44] = {
            {Name = "Lava", Delay = 0.6, Amount = 20},
            {Name = "Mega Slow", Delay = 1.2, Amount = 5},
            {Name = "Lead Balloon", Delay = 0.3, Amount = 12},
            {Name = "Circuit", Delay = 0.5, Amount = 1},
            {Name = "Molten Titan", Delay = 1.5, Amount = 3},
            {Name = "Molten Boss", Delay = 2, Amount = 1},
            {Name = "Speedy King", Delay = 1.2, Amount = 1},
        },
        [45] = {
            {Name = "Warden", Delay = 1, Amount = 1},
            {Name = "Breaker2", Delay = 0.25, Amount = 8},
            {Name = "Breaker4", Delay = 0.5, Amount = 6},
            {Name = "Mega Slow", Delay = 1, Amount = 10},
            {Name = "Health Cultist", Delay = 0.6, Amount = 1},
            {Name = "Slow King", Delay = 1.2, Amount = 6},
            {Name = "Speedy King", Delay = 1.2, Amount = 3},
            {Name = "Soul", Delay = 0.5, Amount = 4},
            {Name = "Circuit", Delay = 0.5, Amount = 1},
            {Name = "Fallen Hero", Delay = 1.3, Amount = 3},
            {Name = "Soul Stealer", Delay = 1.3, Amount = 3},
        },
        [46] = {
            {Name = "Breaker2", Delay = 0.25, Amount = 16},
            {Name = "Fallen", Delay = 0.35, Amount = 12},
            {Name = "Soul", Delay = 0.5, Amount = 8},
            {Name = "Soul Boss", Delay = 0.75, Amount = 4},
            {Name = "Fallen Reaper", Delay = 1, Amount = 3},
            {Name = "Slow King", Delay = 1, Amount = 7},
            {Name = "Speedy King", Delay = 1, Amount = 4},
            {Name = "Necromancer Boss", Delay = 1.25, Amount = 1},
        },
        [47] = {
            {Name = "Breaker4", Delay = 0.5, Amount = 10},
            {Name = "Soul Boss", Delay = 0.75, Amount = 6},
            {Name = "Slow King", Delay = 1, Amount = 8},
            {Name = "Speedy King", Delay = 0.75, Amount = 4},
            {Name = "Soul Stealer", Delay = 1.5, Amount = 2},
            {Name = "Fallen", Delay = 0.35, Amount = 8},
            {Name = "Fallen Titan", Delay = 2, Amount = 2},
        },
        [48] = {
            {Name = "Fallen Hero", Delay = 1.3, Amount = 3},
            {Name = "Warden", Delay = 4, Amount = 1},
            {Name = "Breaker4", Delay = 0.5, Amount = 8},
            {Name = "Error", Delay = 0.2, Amount = 9},
            {Name = "Fallen", Delay = 0.75, Amount = 5},
            {Name = "Soul", Delay = 0.75, Amount = 3},
            {Name = "Soul Boss", Delay = 0.75, Amount = 4},
            {Name = "Slow King", Delay = 1, Amount = 5},
            {Name = "Speedy King", Delay = 0.75, Amount = 5},
            {Name = "Error", Delay = 0.4, Amount = 6},
            {Name = "Fallen Hero", Delay = 1.3, Amount = 2},
        },
        [49] = {
            {Name = "Fallen Hero", Delay = 0.6, Amount = 3},
            {Name = "Fallen", Delay = 0.3, Amount = 5},
            {Name = "Soul", Delay = 0.5, Amount = 3},
            {Name = "Soul Boss", Delay = 1, Amount = 4},
            {Name = "Slow King", Delay = 1.2, Amount = 2},
            {Name = "Speedy King", Delay = 1, Amount = 3},
            {Name = "Soul Stealer", Delay = 2.5, Amount = 2},
            {Name = "Vindicator", Delay = 2, Amount = 1},
            {Name = "Unknown", Delay = 3, Amount = 6},
        },
        [50] = {
            {Name = "Fallen Hero", Delay = 0.6, Amount = 10},
            {Name = "Soul Boss", Delay = 1, Amount = 10},
            {Name = "Slow King", Delay = 1.2, Amount = 10},
            {Name = "Speedy King", Delay = 1, Amount = 12},
            {Name = "Soul Stealer", Delay = 2.5, Amount = 4},
            {Name = "Unknown", Delay = 2, Amount = 6},
            {Name = "Fallen Titan", Delay = 2, Amount = 2},
            {Name = "Fallen Guardian", Delay = 1.5, Amount = 2},
            {Name = "Vindicator", Delay = 3, Amount = 2},
            {
                Name = "Void Reaver",
                Delay = 4,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Boss] = true},
            },
            {Name = "Breaker2", Delay = 0.3, Amount = 12},
            {Name = "Breaker4", Delay = 0.7, Amount = 8},
            {Name = "Giant Boss", Delay = 1.2, Amount = 6},
            {Name = "Fallen Guardian", Delay = 1.5, Amount = 2},
            {Name = "Vindicator", Delay = 3, Amount = 2},
            {Name = "Unknown", Delay = 2, Amount = 6},
        },
    },
}