-- Script path: ReplicatedStorage.Content.Challenges.ClassicRobloxPart4
-- Decompile time: 4.44 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage = game:GetService("ServerStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    disabled = true,
    startingCash = 1300,
    consumablesDisabled = true,
    title = "Tropical Turmoil",
    description = "Challenge 4 of the Roblox Classic event. Loadouts are premade, map is Island Chaos, and is 12 waves",
    onServerLoad = function() -- Line: 8 -- upvalues: ServerStorage (val)
        return require(ServerStorage.Server.Services.Game.GlobalModifierService).compose().addModifier("ClassicOof").addModifier("ClassicDeath").complete()
    end,
    waveCash = function(a1) -- Line: 18
        return math.pow(a1 * 1350, 0.99) + 100
    end,
    maps = {"Classic Island Chaos"},
    gameModifier = Enum.GameModifier.ClassicRoblox,
    waveMusic = {"Egg Hunt 2024", [12] = "Legacy Fallen King"},
    enemyReplaceList = {
        Normal = "Korblox Seeker",
        Slow = "Korblox Undead",
        Speedy = "Korblox Guard",
        Hidden = "Korblox Soul",
        ["Normal Boss"] = "Korblox Warrior",
        ["Slow Boss"] = "Korblox General",
        ["Grave Digger"] = "Korblox Deathwalker",
    },
    enemyReplaceHealthList = {
        ["Korblox Seeker"] = 5,
        ["Korblox Undead"] = 35,
        ["Korblox Soul"] = 20,
        ["Korblox Guard"] = 15,
        ["Korblox Warrior"] = 500,
        ["Korblox General"] = 2500,
        Breaker = 12,
        Breaker2 = 30,
        Breaker3 = 75,
        Breaker4 = 150,
        Necromancer = 500,
        ["Redcliff Traitor"] = 1000,
        ["Korblox Deathwalker"] = 30000,
    },
    overrideLoadout = {
        Warden = {Skin = "Default", GoldenPerks = false, Order = 1},
        Soldier = {Skin = "Default", GoldenPerks = true, Order = 2},
        Commander = {Skin = "Default", GoldenPerks = false, Order = 3},
        Pursuit = {Skin = "Default", GoldenPerks = false, Order = 4},
        Minigunner = {Skin = "Default", GoldenPerks = false, Order = 5},
    },
    overwriteRewards = {
        Badges = {
            [1273235549791625] = function(a1, a2) -- Line: 66
                return a2
            end,
        },
        BadgeIcons = {[17577567446] = {Label = "Token", BadgeId = 1273235549791625}},
    },
    waveEnemiesOverride = {
        {{Name = "Speedy", Amount = 2, Delay = 2, Time = 2}, {Name = "Normal", Amount = 8, Delay = 0.8}},
        {
            {Name = "Normal", Amount = 15, Delay = 0.8, Time = 1.6},
            {Name = "Speedy", Amount = 4, Delay = 1.2},
            {Name = "Slow", Amount = 1, Delay = 0.2},
        },
        {
            {Name = "Speedy", Amount = 6, Delay = 0.8, Time = 0.8},
            {Name = "Slow", Amount = 1, Delay = 0.2},
            {Name = "Normal", Amount = 5, Delay = 0.1},
            {Name = "Slow", Amount = 1, Delay = 0.2},
            {Name = "Normal", Amount = 5, Delay = 0.1},
            {Name = "Slow", Amount = 1, Delay = 0.2},
            {Name = "Normal", Amount = 5, Delay = 0.1},
            {Name = "Slow", Amount = 1, Delay = 0.2},
        },
        {
            {
                Name = "Normal",
                Amount = 2,
                Delay = 0.1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Slow", Amount = 4, Delay = 0.5},
            {Name = "Normal Boss", Amount = 1, Delay = 0},
            {Name = "Speedy", Amount = 10, Delay = 0.1},
            {
                Name = "Normal",
                Amount = 2,
                Delay = 0.1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Slow", Amount = 4, Delay = 0.5},
            {Name = "Normal Boss", Amount = 1, Delay = 0},
        },
        {
            {Name = "Speedy", Amount = 20, Delay = 1, Time = 0},
            {Name = "Hidden", Amount = 15, Delay = 1.8, Time = 1.8},
            {
                Name = "Normal",
                Amount = 5,
                Delay = 0.2,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Slow",
                Amount = 4,
                Delay = 0.2,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Normal Boss", Amount = 2, Delay = 1.5},
            {
                Name = "Normal",
                Amount = 5,
                Delay = 0.4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Slow",
                Amount = 4,
                Delay = 0.2,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Normal Boss", Amount = 2, Delay = 1.5},
        },
        {
            {
                Name = "Normal Boss",
                Amount = 1,
                Delay = 2.5,
                Time = 4.5,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Speedy", Amount = 15, Delay = 1, Time = 1},
            {
                Name = "Normal",
                Amount = 35,
                Delay = 0.8,
                Time = 1.6,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Slow", Amount = 25, Delay = 0.8, Time = 1.6},
            {Name = "Normal Boss", Amount = 5, Delay = 2.5, Time = 4.5},
        },
        {
            {
                Name = "Normal Boss",
                Amount = 1,
                Delay = 2.5,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {
                Name = "Slow",
                Amount = 1,
                Delay = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Hidden", Amount = 40, Delay = 0.7, Time = 1.4},
            {
                Name = "Slow",
                Amount = 2,
                Delay = 4,
                Time = 1.5,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Normal Boss", Amount = 2, Delay = 1, Time = 1.5},
            {Name = "Necromancer", Amount = 1, Delay = 0.6},
            {
                Name = "Hidden",
                Amount = 10,
                Delay = 1.6,
                Time = 3.6,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
            {
                Name = "Slow",
                Amount = 2,
                Delay = 4,
                Time = 1.5,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Normal Boss", Amount = 2, Delay = 1, Time = 1.5},
            {Name = "Necromancer", Amount = 1, Delay = 0.6},
        },
        {
            {Name = "Slow", Amount = 60, Delay = 0.5, Time = 1},
            {Name = "Normal Boss", Amount = 10, Delay = 1.5, Time = 1.5},
            {Name = "Redcliff Traitor", Amount = 1, Delay = 2.5},
            {
                Name = "Speedy",
                Amount = 30,
                Delay = 0.8,
                Time = 0.8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Slow Boss", Amount = 1, Delay = 0.8},
        },
        {
            {Name = "Slow", Amount = 40, Delay = 0.8, Time = 2.4},
            {
                Name = "Korblox Warrior",
                Amount = 1,
                Delay = 0.8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Necromancer", Amount = 1, Delay = 0.8},
            {Name = "Redcliff Traitor", Amount = 1, Delay = 0.8},
            {
                Name = "Hidden",
                Amount = 3,
                Delay = 2,
                Time = 2,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Korblox Warrior", Amount = 1, Delay = 0.8},
            {Name = "Necromancer", Amount = 1, Delay = 0.8},
            {
                Name = "Hidden",
                Delay = 2,
                Time = 2,
                Modifiers = {[Enum.Modifier.Tank] = true, [Enum.Modifier.Slime] = true},
            },
            {Name = "Redcliff Traitor", Amount = 1, Delay = 0.8},
            {Name = "Korblox Warrior", Amount = 1, Delay = 0.8},
        },
        {
            {
                Name = "Breaker2",
                Amount = 22,
                Delay = 0.9,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Redcliff Traitor", Amount = 1, Delay = 0.8},
            {Name = "Breaker4", Amount = 3, Delay = 0.6},
            {
                Name = "Korblox Warrior",
                Amount = 4,
                Delay = 0.5,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Slow Boss", Amount = 1, Delay = 0.5},
            {Name = "Redcliff Traitor", Amount = 1, Delay = 0.8},
            {
                Name = "Speedy",
                Amount = 10,
                Delay = 0.2,
                Modifiers = {[Enum.Modifier.Tank] = true, [Enum.Modifier.Nimble] = true},
            },
            {Name = "Breaker4", Amount = 3, Delay = 0.6},
            {Name = "Slow Boss", Amount = 1, Delay = 0.5},
            {Name = "Necromancer", Amount = 2, Delay = 0.5},
        },
        {
            {Name = "Redcliff Traitor", Amount = 1, Delay = 0.8},
            {
                Name = "Slow",
                Amount = 45,
                Delay = 0.6,
                Time = 1.2,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
            {Name = "Slow Boss", Amount = 2, Delay = 2},
            {
                Name = "Korblox Warrior",
                Amount = 6,
                Delay = 1,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Redcliff Traitor", Amount = 1, Delay = 0.8},
            {
                Name = "Hidden",
                Amount = 5,
                Delay = 0.3,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Slow Boss", Amount = 2, Delay = 2},
            {Name = "Necromancer", Amount = 3, Delay = 0.5},
            {Name = "Redcliff Traitor", Amount = 1, Delay = 0.8},
        },
        {
            {Name = "Slow Boss", Amount = 1, Delay = 1},
            {
                Name = "Normal",
                Amount = 50,
                Delay = 0.8,
                Time = 1.6,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Hidden",
                Amount = 25,
                Delay = 1.6,
                Time = 3.2,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {
                Name = "Speedy",
                Amount = 10,
                Delay = 1.8,
                Time = 3.6,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Redcliff Traitor", Amount = 2, Delay = 4, Time = 2},
            {
                Name = "Korblox Warrior",
                Amount = 4,
                Delay = 2,
                Time = 1,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Slow Boss", Amount = 2, Delay = 4, Time = 1},
            {Name = "Necromancer", Amount = 2, Delay = 3, Time = 3},
            {
                Name = "Grave Digger",
                Amount = 1,
                Delay = 0.8,
                Modifiers = {[Enum.Modifier.Boss] = true},
            },
        },
    },
    dialogue = {
        {
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "I've put up with you for long enough inteloper!",
            },
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "You may have come this far but you will not rob me of my moment.",
                Wait = 5,
            },
            {Speaker = "1x1x1x1", Emotion = "Neutral", Text = "I will squash you here and now!"},
        },
        [3] = {
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "Your commander is just as defiant as you are.",
                Wait = 5,
            },
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "It would be so much easier for the both of you if you both just gave up now!",
            },
        },
        [5] = {
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "Personally I gotta say I always hated the beach, too much sand.",
                Wait = 5,
            },
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "I don't like sand. It's coarse and rough and irritating and it gets everywhere",
            },
        },
        [7] = {
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "How much more of this can you take!?",
                Wait = 5,
            },
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "You should be groveling at my feet by now!",
            },
        },
        [10] = {
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "Your intrusion has gone on long enough!",
                Wait = 5,
            },
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "My plan will not be foiled by the likes of you!",
            },
        },
        [12] = {
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "Now its time I unleash my enhanced Deathwalker on you!",
                Wait = 5,
            },
            {
                Speaker = "1x1x1x1",
                Emotion = "Neutral",
                Text = "This Deathwalker is the older brother to my former roommate!",
            },
        },
    },
}