-- Script path: ReplicatedStorage.Content.Challenges.Juggernaut
-- Decompile time: 6.79 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage = game:GetService("ServerStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    description = "All enemies have high defenses, tank and bloated modifiers.",
    startingCash = 800,
    consumablesDisabled = true,
    title = script.Name,
    gameModifier = Enum.GameModifier.Juggernaut,
    onServerLoad = function() -- Line: 10 -- upvalues: ServerStorage (val)
        return require(ServerStorage.Server.Services.Game.GlobalModifierService).compose().addModifier("NoDialogue").complete()
    end,
    waveCash = function(a1) -- Line: 17
        return math.pow(a1 * 500, 1) + 100
    end,
    modifiersToAllEnemies = {Enum.Modifier.Bloated},
    maps = {"Mason Arch", "Gilded Path", "Lay By", "Dead Ahead"},
    allEnemiesStatsAddition = {Defense = 50},
    enemyReplaceHealthList = {
        ["Abnormal Boss"] = 250,
        Fallen = 300,
        Breaker2 = 50,
        Breaker = 25,
        ["Fallen Hero"] = 5000,
        ["Fallen Guardian"] = 14000,
        ["Fallen King"] = 75000,
        Abnormal = 6,
        Quick = 4,
        Heavy = 16,
        Necromancer = 400,
    },
    challengeRewards = {
        gems = 125,
        experience = 400,
        consumables = {{type = "Nuke", amount = 2}},
        tickets = {Timescale = 4},
    },
    waveEnemiesOverride = {
        {
            {
                Name = "Abnormal",
                Delay = 5,
                Amount = 3,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Abnormal",
                Delay = 4,
                Amount = 5,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Abnormal",
                Delay = 3,
                Amount = 7,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Abnormal",
                Delay = 1.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Quick",
                Delay = 0.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Abnormal",
                Delay = 0.75,
                Amount = 5,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Quick",
                Delay = 1,
                Amount = 8,
                Time = 0.4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Heavy",
                Delay = 1.2,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Quick",
                Delay = 0.6,
                Amount = 5,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Abnormal",
                Delay = 0.6,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 6,
                Time = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Abnormal",
                Delay = 0.5,
                Amount = 5,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Quick",
                Delay = 0.5,
                Amount = 7,
                Time = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Abnormal",
                Delay = 0.5,
                Amount = 12,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Abnormal Boss",
                Delay = 0.6,
                Amount = 1,
                PathName = "1",
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Abnormal",
                Delay = 0.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Quick",
                Delay = 0.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Abnormal Boss",
                Delay = 0.5,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Abnormal",
                Delay = 0.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Shadow",
                Delay = 0.5,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 12,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Abnormal Boss",
                Delay = 0.6,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Shadow",
                Delay = 0.5,
                Amount = 20,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 14,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Heavy",
                Delay = 0.3,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Quick",
                Delay = 0.4,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Shadow",
                Delay = 0.5,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 3,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Abnormal Boss",
                Delay = 0.6,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Dark Necromancer",
                Delay = 0.6,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {Name = "Fallen", Delay = 0.5, Amount = 4},
            {
                Name = "Abnormal Boss",
                Delay = 0.6,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 7,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Fallen", Delay = 0.5, Amount = 5},
            {
                Name = "Abnormal Boss",
                Delay = 0.8,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Shadow",
                Delay = 0.5,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Heavy",
                Delay = 0.6,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Shadow",
                Delay = 0.5,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Abnormal Boss",
                Delay = 0.7,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Giant Boss", Delay = 1, Amount = 1},
        },
        {
            {Name = "Fallen", Delay = 0.5, Amount = 6, Time = 3},
            {Name = "Giant Boss", Delay = 1.5, Amount = 1},
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Dark Necromancer",
                Delay = 0.8,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {Name = "Fallen", Delay = 1, Amount = 6},
            {
                Name = "Mystery",
                Delay = 0.4,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Shadow Boss", Delay = 0.5, Amount = 1},
        },
        {
            {Name = "Fallen", Delay = 1, Amount = 12},
            {
                Name = "Heavy",
                Delay = 0.5,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Dark Necromancer", Delay = 0.6, Amount = 4},
        },
        {{Name = "Glitch", Delay = 0.5, Amount = 12}},
        {
            {Name = "Glitch", Delay = 0.5, Amount = 10},
            {Name = "Fallen", Delay = 0.5, Amount = 8},
            {
                Name = "Mystery",
                Delay = 0.4,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Abnormal Boss",
                Delay = 0.5,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {
                Name = "Hazard",
                Delay = 0.5,
                Amount = 13,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Giant Boss", Delay = 1, Amount = 2},
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Glitch", Delay = 0.5, Amount = 10},
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 1},
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Glitch", Delay = 0.5, Amount = 12},
            {Name = "Fallen", Delay = 0.5, Amount = 12},
            {
                Name = "Hazard",
                Delay = 0.5,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {Name = "Fallen", Delay = 0.5, Amount = 5},
            {
                Name = "Hazard",
                Delay = 0.5,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Abnormal Boss",
                Delay = 0.5,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Shadow Boss", Delay = 1, Amount = 2},
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Glitch", Delay = 0.5, Amount = 9},
            {Time = 2, Name = "Tank", Delay = 2, Amount = 1},
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 5},
            {
                Name = "Hazard",
                Delay = 0.5,
                Amount = 13,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Fallen", Delay = 0.5, Amount = 10},
            {
                Name = "Dark Necromancer",
                Delay = 1,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 3},
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Tank", Delay = 0.5, Amount = 1},
            {Name = "Mystery Boss", Delay = 0.8, Amount = 10},
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 6},
            {Name = "Glitch", Delay = 0.5, Amount = 24},
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Mystery Boss", Delay = 0.8, Amount = 12},
            {
                Name = "Dark Necromancer",
                Delay = 0.8,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Shadow Boss", Delay = 1, Amount = 3},
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 8},
            {Name = "Boomer", Delay = 0.8, Amount = 1},
            {Name = "Glitch", Delay = 0.5, Amount = 8},
            {
                Name = "Mystery",
                Delay = 0.5,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {
                Name = "Hazard",
                Delay = 0.5,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Fallen", Delay = 0.5, Amount = 8},
            {Name = "Mystery Boss", Delay = 0.8, Amount = 14},
        },
        {
            {Name = "Templar", Delay = 3, Amount = 1},
            {
                Name = "Hazard",
                Delay = 0.5,
                Amount = 5,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Mystery Boss", Delay = 0.8, Amount = 20},
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 8},
            {Name = "Boomer", Delay = 1.5, Amount = 1},
            {Name = "Glitch", Delay = 0.3, Amount = 8},
            {Name = "Tank", Delay = 2, Amount = 1},
            {Name = "Error", Delay = 0.3, Amount = 8},
            {Name = "Summoner Boss", Delay = 1.5, Amount = 1},
        },
        {
            {Name = "Boomer", Delay = 1.6, Amount = 1},
            {Name = "Glitch", Delay = 0.5, Amount = 10},
            {Name = "Error", Delay = 0.3, Amount = 6},
            {Name = "Giant Boss", Delay = 1, Amount = 6},
            {Name = "Shadow Boss", Delay = 1, Amount = 2},
            {
                Name = "Hazard",
                Delay = 0.5,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Error", Delay = 0.3, Amount = 6},
            {Name = "Fallen", Delay = 0.5, Amount = 6},
            {Name = "Templar", Delay = 3, Amount = 1},
            {Name = "Summoner Boss", Delay = 3, Amount = 2},
            {Name = "Error", Delay = 0.3, Amount = 6},
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 8},
            {Name = "Error", Delay = 0.3, Amount = 3},
            {Name = "Templar", Delay = 3, Amount = 1},
            {
                Name = "Hazard",
                Delay = 0.5,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Error", Delay = 0.4, Amount = 9},
            {Name = "Mystery Boss", Delay = 0.8, Amount = 15},
            {Name = "Tank", Delay = 2, Amount = 1},
            {Name = "Giant Boss", Delay = 1, Amount = 8},
            {Name = "Error", Delay = 0.3, Amount = 6},
        },
        {
            {Name = "Boomer", Delay = 0.8, Amount = 2},
            {Name = "Tank", Delay = 2.5, Amount = 2},
            {Name = "Error", Delay = 0.3, Amount = 6},
            {Name = "Glitch", Delay = 0.1, Amount = 10},
            {Name = "Templar", Delay = 3, Amount = 1},
            {
                Name = "Hazard",
                Delay = 0.5,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Tank] = true},
            },
            {Name = "Error", Delay = 0.3, Amount = 2},
            {Name = "Fallen", Delay = 0.4, Amount = 15},
            {Name = "Error", Delay = 0.4, Amount = 9},
            {Name = "Fallen Hero", Delay = 1.5, Amount = 7},
            {Name = "Fallen", Delay = 0.4, Amount = 5},
            {Name = "Summoner Boss", Delay = 2, Amount = 1},
            {Name = "Error", Delay = 0.4, Amount = 9},
        },
        {
            {Name = "Fallen Hero", Delay = 1.3, Amount = 3},
            {Name = "Templar", Delay = 4, Amount = 1},
            {Name = "Glitch", Delay = 0.1, Amount = 6},
            {Name = "Error", Delay = 0.3, Amount = 9},
            {Name = "Fallen", Delay = 0.35, Amount = 10},
            {Name = "Giant Boss", Delay = 1, Amount = 5},
            {Name = "Error", Delay = 0.4, Amount = 6},
            {Name = "Fallen Guardian", Delay = 2, Amount = 4},
            {
                Name = "Fallen King",
                Delay = 2,
                Amount = 1,
                Modifiers = {[Enum.Modifier.Boss] = true},
            },
            {Name = "Fallen Hero", Delay = 1, Amount = 2},
            {Name = "Giant Boss", Delay = 1, Amount = 4},
            {Name = "Mystery Boss", Delay = 0.8, Amount = 7},
            {Name = "Error", Delay = 0.4, Amount = 1},
        },
    },
}