-- Script path: ReplicatedStorage.Content.Challenges.Legion
-- Decompile time: 5.97 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage = game:GetService("ServerStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    description = "AOE focused challenge that pits the player against swarms of enemies.",
    startingCash = 700,
    title = script.Name,
    gameModifier = Enum.GameModifier.Legion,
    maps = {"Infernal Abyss", "Winter Stronghold"},
    onServerLoad = function() -- Line: 11 -- upvalues: ServerStorage (val)
        return require(ServerStorage.Server.Services.Game.GlobalModifierService).compose().addModifier("NoDialogue").complete()
    end,
    challengeRewards = {
        gems = 100,
        experience = 300,
        crates = {{type = "High Grade", amount = 2}},
        tickets = {Timescale = 2},
    },
    waveCash = function(a1) -- Line: 33
        return 125 + (25 * a1 - 1)
    end,
    enemyReplaceHealthList = {
        ["Fallen Hero"] = 5000,
        ["Fallen Guardian"] = 14000,
        ["Fallen King"] = 75000,
        Abnormal = 6,
        Quick = 4,
        Heavy = 16,
        ["Abnormal Boss"] = 175,
        Breaker2 = 50,
        Necromancer = 400,
        Fallen = 180,
    },
    waveEnemiesOverride = {
        {{Name = "Abnormal", Delay = 0.25, Amount = 10}},
        {{Name = "Abnormal", Delay = 0.25, Amount = 12}},
        {{Name = "Abnormal", Delay = 0.25, Amount = 14}},
        {{Name = "Abnormal", Delay = 0.25, Amount = 16}},
        {{Name = "Quick", Delay = 0.25, Amount = 16}},
        {{Name = "Abnormal", Delay = 0.25, Amount = 10}, {Name = "Quick", Delay = 0.25, Amount = 16}},
        {{Name = "Heavy", Delay = 0.3, Amount = 20}},
        {
            {
                Name = "Quick",
                Delay = 0.3,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Abnormal", Delay = 0.3, Amount = 12},
            {Name = "Heavy", Delay = 0.3, Amount = 12},
        },
        {
            {Name = "Heavy", Delay = 0.3, Amount = 12},
            {Name = "Abnormal", Delay = 0.25, Amount = 10},
            {Name = "Quick", Delay = 0.25, Amount = 14},
        },
        {
            {Name = "Abnormal", Delay = 0.25, Amount = 24},
            {Name = "Heavy", Delay = 0.3, Amount = 8},
            {Name = "Abnormal Boss", Delay = 0.3, Amount = 2},
        },
        {
            {Name = "Heavy", Delay = 0.3, Amount = 16},
            {Name = "Abnormal", Delay = 0.25, Amount = 16},
            {
                Name = "Quick",
                Delay = 0.25,
                Amount = 16,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
        },
        {
            {Name = "Abnormal Boss", Delay = 0.25, Amount = 2},
            {Name = "Abnormal", Delay = 0.25, Amount = 16},
        },
        {{Name = "Shadow", Delay = 0.25, Amount = 20}},
        {{Name = "Heavy", Delay = 0.3, Amount = 24}, {Name = "Abnormal Boss", Delay = 0.3, Amount = 4}},
        {
            {
                Name = "Shadow",
                Delay = 0.25,
                Amount = 40,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
        },
        {{Name = "Breaker2", Delay = 0.25, Amount = 16}},
        {{Name = "Heavy", Delay = 0.3, Amount = 12}, {Name = "Breaker2", Delay = 0.25, Amount = 12}},
        {{Name = "Breaker2", Delay = 0.25, Amount = 28}},
        {
            {Name = "Heavy", Delay = 0.15, Amount = 8},
            {
                Name = "Quick",
                Delay = 0.2,
                Amount = 12,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {
                Name = "Shadow",
                Delay = 0.25,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {
                Name = "Breaker2",
                Delay = 0.25,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {
                Name = "Abnormal Boss",
                Delay = 0.3,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Dark Necromancer", Delay = 0.3, Amount = 2},
        },
        {
            {Name = "Fallen", Delay = 0.25, Amount = 8},
            {
                Name = "Abnormal Boss",
                Delay = 0.3,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
        },
        {
            {Name = "Breaker2", Delay = 0.25, Amount = 14},
            {Name = "Fallen", Delay = 0.25, Amount = 10},
            {
                Name = "Abnormal Boss",
                Delay = 0.4,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Heavy", Delay = 0.3, Amount = 16},
            {
                Name = "Shadow",
                Delay = 0.25,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
        },
        {
            {Name = "Heavy", Delay = 0.3, Amount = 16},
            {
                Name = "Shadow",
                Delay = 0.25,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Breaker2", Delay = 0.25, Amount = 16},
            {
                Name = "Abnormal Boss",
                Delay = 0.35,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Giant Boss", Delay = 0.5, Amount = 2},
        },
        {
            {Name = "Fallen", Delay = 0.25, Amount = 12},
            {Name = "Giant Boss", Delay = 0.75, Amount = 2},
            {
                Name = "Breaker2",
                Delay = 0.25,
                Amount = 16,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Dark Necromancer", Delay = 0.4, Amount = 2},
        },
        {
            {Name = "Fallen", Delay = 0.25, Amount = 12},
            {
                Name = "Breaker2",
                Delay = 0.2,
                Amount = 16,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Shadow Boss", Delay = 0.25, Amount = 2},
        },
        {
            {Name = "Fallen", Delay = 0.25, Amount = 24},
            {Name = "Heavy", Delay = 0.25, Amount = 8},
            {
                Name = "Breaker2",
                Delay = 0.25,
                Amount = 12,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Dark Necromancer", Delay = 0.3, Amount = 8},
        },
        {
            {
                Name = "Glitch",
                Delay = 0.25,
                Amount = 24,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
        },
        {
            {Name = "Glitch", Delay = 0.25, Amount = 20},
            {
                Name = "Fallen",
                Delay = 0.25,
                Amount = 16,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
            {
                Name = "Breaker2",
                Delay = 0.2,
                Amount = 16,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {
                Name = "Abnormal Boss",
                Delay = 0.25,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
        },
        {
            {
                Name = "Hazard",
                Delay = 0.25,
                Amount = 26,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Giant Boss", Delay = 0.5, Amount = 4},
            {
                Name = "Breaker2",
                Delay = 0.25,
                Amount = 20,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Glitch", Delay = 0.25, Amount = 20},
        },
        {
            {
                Name = "Giant Boss",
                Delay = 0.5,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Breaker2",
                Delay = 0.25,
                Amount = 20,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Glitch", Delay = 0.25, Amount = 24},
            {
                Name = "Fallen",
                Delay = 0.25,
                Amount = 24,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Hazard",
                Delay = 0.25,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
        },
        {
            {
                Name = "Fallen",
                Delay = 0.25,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {
                Name = "Hazard",
                Delay = 0.25,
                Amount = 8,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Abnormal Boss", Delay = 0.25, Amount = 8},
            {
                Name = "Shadow Boss",
                Delay = 0.5,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Breaker2",
                Delay = 0.25,
                Amount = 20,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Glitch", Delay = 0.25, Amount = 18},
            {Name = "Tank", Delay = 1, Amount = 2},
            {Name = "Breaker2", Delay = 0.25, Amount = 20},
        },
        {
            {Name = "Giant Boss", Delay = 0.5, Amount = 10},
            {Name = "Hazard", Delay = 0.25, Amount = 26},
            {
                Name = "Fallen",
                Delay = 0.25,
                Amount = 20,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Dark Necromancer", Delay = 0.5, Amount = 2},
        },
        {
            {Name = "Giant Boss", Delay = 0.5, Amount = 6},
            {
                Name = "Breaker2",
                Delay = 0.25,
                Amount = 16,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Tank", Delay = 0.25, Amount = 3},
            {Name = "Breaker4", Delay = 0.4, Amount = 20},
        },
        {
            {Name = "Giant Boss", Delay = 0.5, Amount = 12},
            {
                Name = "Glitch",
                Delay = 0.25,
                Amount = 48,
                Time = 2,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
            {
                Name = "Breaker2",
                Delay = 0.25,
                Amount = 20,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Breaker4", Delay = 0.4, Amount = 24},
            {
                Name = "Dark Necromancer",
                Delay = 0.4,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {Name = "Shadow Boss", Delay = 0.5, Amount = 6},
        },
        {
            {
                Name = "Giant Boss",
                Delay = 0.5,
                Amount = 16,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Boomer",
                Delay = 0.4,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {
                Name = "Glitch",
                Delay = 0.25,
                Amount = 16,
                Modifiers = {[Enum.Modifier.Slime] = true},
            },
            {Name = "Breaker2", Delay = 0.25, Amount = 12},
            {
                Name = "Hazard",
                Delay = 0.25,
                Amount = 12,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Fallen", Delay = 0.25, Amount = 16},
            {Name = "Breaker4", Delay = 0.4, Amount = 28},
        },
        {
            {
                Name = "Warden",
                Delay = 1.5,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Hazard",
                Delay = 0.25,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Breaker4", Delay = 0.4, Amount = 40},
        },
        {
            {Name = "Giant Boss", Delay = 0.5, Amount = 16},
            {
                Name = "Boomer",
                Delay = 0.75,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {
                Name = "Glitch",
                Delay = 0.15,
                Amount = 16,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Tank", Delay = 0.5, Amount = 4},
            {Name = "Error", Delay = 0.15, Amount = 16},
            {Name = "Summoner Boss", Delay = 0.75, Amount = 2},
        },
        {
            {
                Name = "Boomer",
                Delay = 0.8,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {
                Name = "Glitch",
                Delay = 0.25,
                Amount = 20,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Error", Delay = 0.15, Amount = 12},
            {
                Name = "Giant Boss",
                Delay = 0.5,
                Amount = 12,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Shadow Boss",
                Delay = 0.5,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Bloated] = true},
            },
            {
                Name = "Hazard",
                Delay = 0.25,
                Amount = 12,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Error", Delay = 0.15, Amount = 12},
            {
                Name = "Fallen",
                Delay = 0.25,
                Amount = 12,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Warden", Delay = 1.5, Amount = 2},
            {Name = "Summoner Boss", Delay = 1.5, Amount = 4},
            {Name = "Error", Delay = 0.15, Amount = 12},
        },
        {
            {Name = "Giant Boss", Delay = 0.5, Amount = 16},
            {Name = "Error", Delay = 0.15, Amount = 6},
            {Name = "Warden", Delay = 1.5, Amount = 2},
            {
                Name = "Hazard",
                Delay = 0.25,
                Amount = 20,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Error", Delay = 0.2, Amount = 18},
            {Name = "Breaker4", Delay = 0.4, Amount = 30},
            {Name = "Tank", Delay = 1, Amount = 2},
            {Name = "Giant Boss", Delay = 0.5, Amount = 16},
            {Name = "Error", Delay = 0.15, Amount = 12},
        },
        {
            {
                Name = "Boomer",
                Delay = 0.4,
                Amount = 4,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Tank", Delay = 1.25, Amount = 4},
            {Name = "Error", Delay = 0.15, Amount = 12},
            {
                Name = "Glitch",
                Delay = 0.1,
                Amount = 10,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Warden", Delay = 1.5, Amount = 2},
            {
                Name = "Hazard",
                Delay = 0.25,
                Amount = 20,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Error", Delay = 0.15, Amount = 4},
            {Name = "Fallen", Delay = 0.2, Amount = 30},
            {Name = "Error", Delay = 0.2, Amount = 18},
            {Name = "Fallen Hero", Delay = 0.75, Amount = 14},
            {Name = "Fallen", Delay = 0.2, Amount = 10},
            {Name = "Summoner Boss", Delay = 1, Amount = 2},
            {Name = "Error", Delay = 0.2, Amount = 18},
        },
        {
            {Name = "Fallen Hero", Delay = 0.7, Amount = 6},
            {Name = "Warden", Delay = 2, Amount = 2},
            {
                Name = "Glitch",
                Delay = 0.1,
                Amount = 6,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Error", Delay = 0.15, Amount = 18},
            {
                Name = "Fallen",
                Delay = 0.175,
                Amount = 20,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Giant Boss", Delay = 0.5, Amount = 10},
            {Name = "Error", Delay = 0.2, Amount = 12},
            {Name = "Fallen Guardian", Delay = 1, Amount = 8},
            {
                Name = "Fallen King",
                Delay = 1,
                Amount = 2,
                Modifiers = {[Enum.Modifier.Boss] = true},
            },
            {Name = "Fallen Hero", Delay = 0.5, Amount = 4},
            {Name = "Giant Boss", Delay = 0.5, Amount = 8},
            {
                Name = "Breaker4",
                Delay = 0.4,
                Amount = 14,
                Modifiers = {[Enum.Modifier.Nimble] = true},
            },
            {Name = "Error", Delay = 0.2, Amount = 2},
        },
    },
}