-- Script path: ReplicatedStorage.Content.Challenges.Vanguard
-- Decompile time: 4.50 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage = game:GetService("ServerStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    description = "All enemies have Nimble.",
    startingCash = 700,
    title = script.Name,
    gameModifier = Enum.GameModifier.Vanguard,
    modifiersToAllEnemies = {Enum.Modifier.Nimble},
    maps = {"Black Spot Exchange", "Winter Stronghold", "Candy Valley", "Infernal Abyss"},
    challengeRewards = {
        gems = 100,
        experience = 350,
        consumables = {{type = "Blizzard Bomb", amount = 2}},
        tickets = {Timescale = 3},
    },
    enemyReplaceList = {
        Mystery = "Breaker2",
        ["Mystery Boss"] = "Breaker4",
        ["Dark Necromancer"] = "Necromancer",
        Templar = "Warden",
    },
    enemyReplaceHealthList = {
        ["Fallen Hero"] = 5000,
        ["Fallen Guardian"] = 14000,
        ["Fallen King"] = 75000,
        Abnormal = 6,
        Quick = 4,
        Heavy = 16,
        ["Abnormal Boss"] = 175,
        Breaker2 = 50,
        Necromancer = 400,
        Fallen = 180,
    },
    onServerLoad = function() -- Line: 45 -- upvalues: ServerStorage (val)
        return require(ServerStorage.Server.Services.Game.GlobalModifierService).compose().addModifier("NoDialogue").complete()
    end,
    waveEnemiesOverride = {
        {{Name = "Abnormal", Delay = 0.5, Amount = 5}},
        {{Name = "Abnormal", Delay = 0.5, Amount = 6}},
        {{Name = "Abnormal", Delay = 0.5, Amount = 7}},
        {{Name = "Abnormal", Delay = 0.5, Amount = 8}},
        {{Name = "Quick", Delay = 0.5, Amount = 8}},
        {
            {Name = "Abnormal", Delay = 0.5, Amount = 5},
            {Name = "Quick", Delay = 0.5, Amount = 8, Time = 0.4},
        },
        {{Name = "Heavy", Delay = 0.6, Amount = 10}},
        {
            {Name = "Quick", Delay = 0.6, Amount = 5},
            {Name = "Abnormal", Delay = 0.6, Amount = 6},
            {Name = "Heavy", Delay = 0.6, Amount = 6, Time = 1},
        },
        {
            {Name = "Heavy", Delay = 0.6, Amount = 6},
            {Name = "Abnormal", Delay = 0.5, Amount = 5},
            {Name = "Quick", Delay = 0.5, Amount = 7, Time = 1},
        },
        {
            {Name = "Abnormal", Delay = 0.5, Amount = 12},
            {Name = "Heavy", Delay = 0.6, Amount = 4},
            {Name = "Abnormal Boss", Delay = 0.6, Amount = 1},
        },
        {
            {Name = "Heavy", Delay = 0.6, Amount = 8},
            {Name = "Abnormal", Delay = 0.5, Amount = 8},
            {Name = "Quick", Delay = 0.5, Amount = 8},
        },
        {
            {Name = "Abnormal Boss", Delay = 0.5, Amount = 1},
            {Name = "Abnormal", Delay = 0.5, Amount = 8},
        },
        {{Name = "Shadow", Delay = 0.5, Amount = 10}},
        {{Name = "Heavy", Delay = 0.6, Amount = 12}, {Name = "Abnormal Boss", Delay = 0.6, Amount = 2}},
        {{Name = "Shadow", Delay = 0.5, Amount = 20}},
        {{Name = "Mystery", Delay = 0.5, Amount = 8}},
        {{Name = "Heavy", Delay = 0.6, Amount = 6}, {Name = "Mystery", Delay = 0.5, Amount = 6}},
        {{Name = "Mystery", Delay = 0.5, Amount = 14}},
        {
            {Name = "Heavy", Delay = 0.3, Amount = 4},
            {Name = "Quick", Delay = 0.4, Amount = 6},
            {Name = "Shadow", Delay = 0.5, Amount = 4},
            {Name = "Mystery", Delay = 0.5, Amount = 3},
            {Name = "Abnormal Boss", Delay = 0.6, Amount = 2},
            {Name = "Dark Necromancer", Delay = 0.6, Amount = 1},
        },
        {{Name = "Fallen", Delay = 0.5, Amount = 4}, {Name = "Abnormal Boss", Delay = 0.6, Amount = 1}},
        {
            {Name = "Mystery", Delay = 0.5, Amount = 7},
            {Name = "Fallen", Delay = 0.5, Amount = 5},
            {Name = "Abnormal Boss", Delay = 0.8, Amount = 2},
            {Name = "Heavy", Delay = 0.6, Amount = 8},
            {Name = "Shadow", Delay = 0.5, Amount = 4},
        },
        {
            {Name = "Heavy", Delay = 0.6, Amount = 8},
            {Name = "Shadow", Delay = 0.5, Amount = 4},
            {Name = "Mystery", Delay = 0.5, Amount = 8},
            {Name = "Abnormal Boss", Delay = 0.7, Amount = 2},
            {Name = "Giant Boss", Delay = 1, Amount = 1},
        },
        {
            {Name = "Fallen", Delay = 0.5, Amount = 6, Time = 3},
            {Name = "Giant Boss", Delay = 1.5, Amount = 1},
            {Name = "Mystery", Delay = 0.5, Amount = 8},
            {Name = "Dark Necromancer", Delay = 0.8, Amount = 1},
        },
        {
            {Name = "Fallen", Delay = 0.5, Amount = 6},
            {Name = "Mystery", Delay = 0.4, Amount = 8},
            {Name = "Shadow Boss", Delay = 0.5, Amount = 1},
        },
        {
            {Name = "Fallen", Delay = 0.5, Amount = 12},
            {Name = "Heavy", Delay = 0.5, Amount = 4},
            {Name = "Mystery", Delay = 0.5, Amount = 6},
            {Name = "Dark Necromancer", Delay = 0.6, Amount = 4},
        },
        {{Name = "Glitch", Delay = 0.5, Amount = 12}},
        {
            {Name = "Glitch", Delay = 0.5, Amount = 10},
            {Name = "Fallen", Delay = 0.5, Amount = 8},
            {Name = "Mystery", Delay = 0.4, Amount = 8},
            {Name = "Abnormal Boss", Delay = 0.5, Amount = 4},
        },
        {
            {Name = "Hazard", Delay = 0.5, Amount = 13},
            {Name = "Giant Boss", Delay = 1, Amount = 2},
            {Name = "Mystery", Delay = 0.5, Amount = 10},
            {Name = "Glitch", Delay = 0.5, Amount = 10},
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 1},
            {Name = "Mystery", Delay = 0.5, Amount = 10},
            {Name = "Glitch", Delay = 0.5, Amount = 12},
            {Name = "Fallen", Delay = 0.5, Amount = 12},
            {Name = "Hazard", Delay = 0.5, Amount = 4},
        },
        {
            {Name = "Fallen", Delay = 0.5, Amount = 5},
            {Name = "Hazard", Delay = 0.5, Amount = 4},
            {Name = "Abnormal Boss", Delay = 0.5, Amount = 4},
            {Name = "Shadow Boss", Delay = 1, Amount = 2},
            {Name = "Mystery", Delay = 0.5, Amount = 10},
            {Name = "Glitch", Delay = 0.5, Amount = 9},
            {Time = 2, Name = "Tank", Delay = 2, Amount = 1},
            {Name = "Mystery", Delay = 0.5, Amount = 10},
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 5},
            {Name = "Hazard", Delay = 0.5, Amount = 13},
            {Name = "Fallen", Delay = 0.5, Amount = 10},
            {Name = "Dark Necromancer", Delay = 1, Amount = 1},
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 3},
            {Name = "Mystery", Delay = 0.5, Amount = 8},
            {Name = "Tank", Delay = 0.5, Amount = 1},
            {Name = "Mystery Boss", Delay = 0.8, Amount = 10},
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 6},
            {Name = "Glitch", Delay = 0.5, Amount = 24},
            {Name = "Mystery", Delay = 0.5, Amount = 10},
            {Name = "Mystery Boss", Delay = 0.8, Amount = 12},
            {Name = "Dark Necromancer", Delay = 0.8, Amount = 1},
            {Name = "Shadow Boss", Delay = 1, Amount = 3},
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 8},
            {Name = "Boomer", Delay = 0.8, Amount = 1},
            {Name = "Glitch", Delay = 0.5, Amount = 8},
            {Name = "Mystery", Delay = 0.5, Amount = 6},
            {Name = "Hazard", Delay = 0.5, Amount = 6},
            {Name = "Fallen", Delay = 0.5, Amount = 8},
            {Name = "Mystery Boss", Delay = 0.8, Amount = 14},
        },
        {
            {Name = "Templar", Delay = 3, Amount = 1},
            {Name = "Hazard", Delay = 0.5, Amount = 5},
            {Name = "Mystery Boss", Delay = 0.8, Amount = 20},
        },
        {
            {Name = "Giant Boss", Delay = 1, Amount = 8},
            {Name = "Boomer", Delay = 1.5, Amount = 1},
            {Name = "Glitch", Delay = 0.3, Amount = 8},
            {Name = "Tank", Delay = 2, Amount = 1},
            {Name = "Error", Delay = 0.3, Amount = 8},
            {Name = "Summoner Boss", Delay = 1.5, Amount = 1},
        },
        {
            {Name = "Boomer", Delay = 1.6, Amount = 1},
            {Name = "Glitch", Delay = 0.5, Amount = 10},
            {Name = "Error", Delay = 0.3, Amount = 6},
            {Name = "Giant Boss", Delay = 1, Amount = 6},
            {Name = "Shadow Boss", Delay = 1, Amount = 2},
            {Name = "Hazard", Delay = 0.5, Amount = 6},
            {Name = "Error", Delay = 0.3, Amount = 6},
            {Name = "Fallen", Delay = 0.5, Amount = 6},
            {Name = "Templar", Delay = 3, Amount = 1},
            {Name = "Summoner Boss", Delay = 3, Amount = 2},
            {Name = "Error", Delay = 0.3, Amount = 6},
        },
        {
            {Name = "Boomer", Delay = 1.6, Amount = 1},
            {Name = "Glitch", Delay = 0.5, Amount = 10},
            {Name = "Error", Delay = 0.3, Amount = 6},
            {Name = "Giant Boss", Delay = 1, Amount = 6},
            {Name = "Shadow Boss", Delay = 1, Amount = 2},
            {Name = "Hazard", Delay = 0.5, Amount = 6},
            {Name = "Error", Delay = 0.3, Amount = 6},
            {Name = "Fallen", Delay = 0.5, Amount = 6},
            {Name = "Templar", Delay = 3, Amount = 1},
            {Name = "Summoner Boss", Delay = 3, Amount = 2},
            {Name = "Error", Delay = 0.3, Amount = 6},
        },
        {
            {Name = "Boomer", Delay = 0.8, Amount = 2},
            {Name = "Tank", Delay = 2.5, Amount = 2},
            {Name = "Error", Delay = 0.3, Amount = 6},
            {Name = "Glitch", Delay = 0.1, Amount = 10},
            {Name = "Templar", Delay = 3, Amount = 1},
            {Name = "Hazard", Delay = 0.5, Amount = 10},
            {Name = "Error", Delay = 0.3, Amount = 2},
            {Name = "Fallen", Delay = 0.4, Amount = 15},
            {Name = "Error", Delay = 0.4, Amount = 9},
            {Name = "Fallen Hero", Delay = 1.5, Amount = 7},
            {Name = "Fallen", Delay = 0.4, Amount = 5},
            {Name = "Summoner Boss", Delay = 2, Amount = 1},
            {Name = "Error", Delay = 0.4, Amount = 9},
        },
        {
            {Name = "Fallen Hero", Delay = 1.3, Amount = 3},
            {Name = "Templar", Delay = 4, Amount = 1},
            {Name = "Glitch", Delay = 0.1, Amount = 6},
            {Name = "Error", Delay = 0.3, Amount = 9},
            {Name = "Fallen", Delay = 0.35, Amount = 10},
            {Name = "Giant Boss", Delay = 1, Amount = 5},
            {Name = "Error", Delay = 0.4, Amount = 6},
            {Name = "Fallen Guardian", Delay = 2, Amount = 4},
            {Name = "Fallen King", Delay = 2, Amount = 1},
            {Name = "Fallen Hero", Delay = 1, Amount = 2},
            {Name = "Giant Boss", Delay = 1, Amount = 4},
            {Name = "Mystery Boss", Delay = 0.8, Amount = 7},
            {Name = "Error", Delay = 0.4, Amount = 1},
        },
    },
}