-- Script path: ReplicatedStorage.Content.NewEnemies.Golden Mystery.Stats
-- Decompile time: 0.92 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    Scale = 1.5,
    Speed = 1,
    MaxHealth = 15000,
    Reward = 100,
    Description = "GOLDENNNNN MYSTERYYYY",
    Attributes = {Enum.Modifier.FreezeImmune, Enum.Modifier.StunImmune},
    SpawnPools = {
        {
            {enemy = "Korblox Deathwalker", amount = 1},
            {enemy = "Conserver", amount = 1},
            {enemy = "Corrupted Conserver", amount = 1},
            {enemy = "Nuclear Monster", amount = 1},
            {enemy = "Kronus", amount = 1},
            {enemy = "Corrupted Commander", amount = 1},
            {enemy = "Frost Spirit", amount = 1},
            {enemy = "Producer", amount = 1},
            {enemy = "Narrator", amount = 1},
            {enemy = "Titus", amount = 1},
            {enemy = "Corrupted Titus", amount = 1},
            {enemy = "Null Guardian", amount = 1},
            {enemy = "Brute", amount = 1},
            {enemy = "Patient Zero", amount = 1},
            {enemy = "Hazem Boss", amount = 1},
            {enemy = "Fallen King", amount = 1},
            {enemy = "Wox", amount = 1},
            {enemy = "Ducky D00M 3", amount = 1},
            {enemy = "Nerd Duck", amount = 1},
            {enemy = "Molten Warlord", amount = 1},
            {enemy = "Executioner Plush", amount = 1},
            {enemy = "Jackobot", amount = 1},
            {enemy = "Mechanical Rot", amount = 1},
            {enemy = "Gunslinger", amount = 1},
            {enemy = "Gravedigger", amount = 1},
            {enemy = "Void Reaver", amount = 1},
            {enemy = "Void Caster", amount = 1},
            {enemy = "Void Brute", amount = 1},
            {enemy = "Void Grave Digger", amount = 1},
            {enemy = "Void Swordmaster", amount = 1},
            {enemy = "Soul Stealer", amount = 1},
            {enemy = "Vindicator", amount = 1},
            {enemy = "Fallen Honor Guard", amount = 1},
            {enemy = "Champion Templar", amount = 1},
            {enemy = "Necromancer King", amount = 1},
            {enemy = "Warden", amount = 1},
            {enemy = "Rift Walker", amount = 1},
            {enemy = "Siege Engine", amount = 1},
        },
    },
    Summon = {Amount = 100, Spawns = {}, Modifiers = {{Chance = 100, Modifier = Enum.Modifier.Boss}}},
}