-- Script path: ReplicatedStorage.Content.Crate.Premium
-- Decompile time: 1.01 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    Description = "A premium skincrate used to unbox more complex skins.",
    Animation = 111026290509264,
    MasterSound = 103688094879354,
    MusicName = "Premium Crate",
    Rarity = Enum.SkinRarity.Uncommon,
    Category = Enum.CrateCategory.Robux,
    Price = {Id = 785567507, Type = Enum.CurrencyType.Robux},
    Daily = {
        CurrencyType = Enum.CurrencyType.Robux,
        Prices = {
            Rarities = {
                [Enum.SkinRarity.Common] = 1083359574,
                [Enum.SkinRarity.Uncommon] = 1083359603,
                [Enum.SkinRarity.Rare] = 1083359629,
                [Enum.SkinRarity.Legendary] = 1083359655,
            },
        },
    },
    Preview = {
        Time = 1.15,
        FieldOfView = 50,
        Icon = 5798487154,
        CameraOffset = CFrame.new(0, 0, 0),
        CrateRotation = CFrame.Angles(0, 0, 0),
    },
    Contents = {
        ["Stealth Ops"] = {"Soldier"},
        Blazing = {"Brawler"},
        Green = {"Paintballer"},
        Clown = {"Jester"},
        Steampunk = {"Ranger", "Rocketeer"},
        Cyber = {"Medic"},
        Partisan = {"Ranger"},
        General = {"Commander"},
        XR300 = {"Turret"},
        Redemption = {"Cowboy", "Sniper"},
        ["Black Ops"] = {"Minigunner", "Ranger", "Scout"},
        Cop = {"Cowboy"},
        Hazmat = {"Minigunner", "Militant", "Pyromancer", "Electroshocker"},
        Checker = {"Crook Boss"},
        Fortress = {"Demoman", "Rocketeer"},
        ["Dark Matter"] = {"Ranger", "Rocketeer"},
        Slugger = {"Gladiator"},
        ["Mint Choco"] = {"Freezer"},
        Liberator = {"Soldier"},
        ["Cold Soldier"] = {"Soldier"},
        Doughboy = {"Soldier"},
        Victorian = {"Commander"},
        Classic = {"Military Base", "Ranger", "Shotgunner"},
        Galactic = {"Commander"},
        Heavy = {"Minigunner"},
        Arcade = {"Farm"},
        Kasodus = {"Cowboy"},
        ["Deep Freeze"] = {"Freezer"},
        XR500 = {"Turret"},
        Bandit = {"Cowboy"},
        Bosanka = {"Rocketeer"},
        Wraith = {"Minigunner", "Ranger"},
        Acidic = {"Pyromancer"},
        ["Space Elite"] = {"Minigunner"},
        Mage = {"Pyromancer"},
        Agent = {"Cowboy"},
        Lumberjack = {"Militant"},
        Intern = {"Scout"},
        Baseball = {"Warden"},
        DRKSHDW = {"Crook Boss"},
        Pattern = {"Commander"},
        Dragon = {"Warlock"},
        Pumpkin = {"Assassin"},
        ["Most Wanted"] = {"Cowboy"},
        ["Black Cat"] = {"Electroshocker"},
    },
    Sounds = {Drop = 5446304208, Open = 5446304444, Fling = 5446304771, Unlock = 5446303907},
}