-- Script path: ReplicatedStorage.Content.NewEnemies.Void Reaver.Stats
-- Decompile time: 1.41 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Enum_2 = require(ReplicatedStorage.Shared.Modules.Enum)
local GameState = require(ReplicatedStorage.Shared.Modules.GameState)
return {
    Description = "Being the right hand and most prized giant created by the Void Caster and enhanced by Lord Exo, the Void Reaver is the epitome of the Void. Its power alone makes it one of the strongest creatures conceived. As it crossed the battlefield alongside Void Caster during the battle of the Old World, the Void Reaver slew countless Two X’s warriors. Many of the giants fell during the battle, making them incredibly rare to find. As it walks, it contaminates the ground for the Void flora to grow. Where the Void Reaver walks, the Void takes root, the soil blooming with the pale, quiet flowers that mark land the eternal nothing has claimed. No one has ever seen the limit of its strength, because nothing has ever come close to using it. The battle of the Old World ended before the Void Reaver was truly tested, and Void Caster has not since found someone worthy for it to target. What it is truly capable of still remains a question. Above all, the Void Reaver answers only to her, and it falls still the moment her song reaches it.",
    MaxHealth = 1200000,
    Scale = 1.4,
    Speed = 0.9,
    RewardThreshold = 0.1,
    Phase2Threshold = 0.6,
    EasyModeLastStandThreshold = 0.15,
    FinalStandSpeed = 4.5,
    SpeedByMode = {Hardcore = {Easy = 0.85, Hard = 0.68}},
    HealthPerDifficulty = {Hard = 1200000, Easy = 1200000},
    Attributes = {Enum_2.Modifier.Boss},
    Reward = {Hard = 1500000, Easy = 2400000},
    HealthMarkers = {
        EasyModeLastStandThreshold = {
            value = 0.15,
            color = Color3.fromRGB(255, 170, 0),
            shouldShow = function() -- Line: 38 -- upvalues: GameState (val)
                local v1 = false
                if GameState.GameMode == "Hardcore" then
                    v1 = GameState.Difficulty == "Easy"
                end
                return v1
            end,
        },
    },
    VoidCasterModeSpawn = {Hardcore = {"Hard"}},
    RageModeData = {SpeedBoost = 1.25, DifficultyToDoSpeedBoost = {"Hard", "Easy"}},
    SoundEmitter = {
        RollOffMaxDistance = 300,
        RollOffMinDistance = 20,
        Volume = 0.25,
        RollOffMode = Enum.RollOffMode.LinearSquare,
    },
    Sounds = {
        death_scream = {id = 124958866313755},
        death = {id = 98979836268041},
        stomp1 = {id = 130517702839388},
        stomp2 = {id = 100599242998863},
        rupture_intro = {id = 121196315277629},
        rupture_charge_up = {id = 95899451783111},
        rupture_cancel = {id = 133793089833138},
        rupture_outro = {id = 100091612259563},
        cursed_blade = {id = 113100856702207},
        void_judgement = {id = 116112285501510},
        unnerving_gaze = {id = 118896336984412},
        portal_spawn = {id = 80667487903367},
        revive = {id = 88519515863373},
        rage_mode = {id = 95823856719397, volume = 0.125},
        healing = {id = 75317512986216, looped = true},
    },
    Moveset = {
        ["Cursed Blade"] = {
            Cooldown = 17.5,
            Range = 10,
            SwordFOV = 60,
            ProjectileTime = 50,
            SwordProjectileRange = 60,
            StunLength = 5,
            UnitDamage = 1500,
            Rest = 2,
            DelayProjectile = 0.5,
            SwingDelayDamage = 0.8,
            ProjectileHitRange = 5,
            ProjectileDamage = 150,
            ProjectileDebuffCooldown = 100,
            ProjectileRangeDebuff = 20,
            ProjectileDebuffDuration = 8,
            CooldownDebuff = 100,
            RangeDebuff = 20,
            DebuffDuration = 8,
            SoalTargetSpawnThreshold = 1,
            EnemySpawns = {
                {
                    enemy = "Soul",
                    spawnAmount = NumberRange.new(6, 6),
                    randomModifiers = {Enum_2.Modifier.Blessed},
                },
            },
        },
        ["Void Judgement"] = {
            Cooldown = 50,
            Range = 200,
            Rest = 0.1,
            UnitDamage = 10000,
            BeamsToSummon = 6,
            BeamRadius = 3,
            DebuffDuration = 17.5,
            RangeDebuff = 20,
            CooldownDebuff = 25,
            BeamChargeTime = 2,
        },
        ["Unnerving Gaze"] = {
            Cooldown = 35,
            Range = 200,
            Rest = 2,
            ChargeUpTime = 1.25,
            BeamSpeedTime = 0.85,
            PortalDelaySpawn = 2,
            RandomOffset = NumberRange.new(2, 5),
            AmountEyesToSummonData = {-10, -4, 20},
        },
        ["Void Rupture"] = {
            Cooldown = 50,
            Range = 12.5,
            Rest = 3,
            FOV = 61,
            NeededTargets = 3,
            finalSpinDelay = 0.49,
            StunTime = 5,
            DebuffCooldown = 25,
            DebuffDuration = 5,
            FinalStunTime = 12,
            DamageThreashold = 300000,
            SwordFinalRange = 1000,
            ChargeUpTime = 5,
            UnitDamage = 1500,
            RuptureSize = Vector3.new(20, 2, 8),
            RuptureStunTime = 2.5,
            RuptureRange = 10,
            RuptureDamage = 250,
            RuptureDebuffCooldown = 100,
            RuptureDebuffDuration = 5,
            RuptureMinRangeFromBoss = 10,
            phase2 = true,
            swingWaitTimes = {1.13, 1.54, 1.1},
            RuptureRandomOffset = Vector2.new(-10, 10),
        },
    },
}