-- Script path: ReplicatedStorage.Content.NewEnemies.Void Swordmaster.Stats
-- Decompile time: 0.55 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    Description = "The Void Sword Master is the commander of the Void Knights. Guided by the Void, he is deadly in his art. Void Caster, surprisingly, did not create the Void Sword Master. She found him. He’s a remnant of the Old World who had already made a name for himself, but he had no purpose to achieve. Seeing an opportunity, the Void Caster gave him one. The Void Sword Master does not speak often, and there is no record of him losing a fight. (Until today.) Void Caster trusts him completely, but even she does not know the extent of what he is capable of. Instead, she has decided there is not a need to.",
    AwardBadgeOnDeath = {id = 648906810873817, modes = {mode = "Hardcore", difficulty = "Hard"}},
    Scale = 2.5,
    Speed = 1.75,
    MaxHealth = 500000,
    HealthPerDifficulty = {Hard = 700000, Easy = 350000},
    Attributes = {Enum.Modifier.Boss, Enum.Modifier.StunImmune},
    Reward = {Hard = 300000, Easy = 200000},
    RewardThreshold = 0.5,
    AttackInitialCooldown = 5,
    AttackCooldown = 4,
    VoidTearRange = 15,
    VoidTearSlashAngles = {45, -45},
    VoidTearHitbox = Vector3.new(10, 20, 50),
    VoidTearExplosionCount = 4,
    VoidTearStunTime = 10,
    VoidTearDamage = 150,
    VoidTearCD = 25,
    VoidTearTelegraphTime = 2,
    VoidTearAnimDuration = 5.67,
    VoidTearHealTime = 5.67,
    ImpalingSwordRange = 30,
    ImpalingSwordBlades = 25,
    ImpalingSwordBladeRadius = 1.5,
    ImpalingSwordBladeDelay = 0.15,
    ImpalingSwordFatigueDebuff = 150,
    ImpalingSwordFatigueDuration = 17.5,
    ImpalingSwordScaredDebuff = 12.5,
    ImpalingSwordScaredDuration = 17.5,
    ImpalingSwordDamage = 500,
    ImpalingSwordCD = 35,
    ImpalingSwordAnimDuration = 4.67,
    ImpalingSwordStartDelay = 1.7,
    RageHealthThreshold = 0.5,
    RageSpeedMultiplier = 1.5,
    RageImpalingSwordCooldownReduction = 20,
    RageShield = 150000,
}