-- Script path: ReplicatedStorage.Content.Gamemodes.PVP.Difficulties.PVP_midRanks.SpawnableEnemies
-- Decompile time: 0.61 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Enum = require(ReplicatedStorage.Shared.Modules.Enum)
require(ReplicatedStorage.Shared.Types.PVPConstantTypes)
return {
    Normal = {
        Cost = 50,
        Eco = 4,
        PurchaseAmount = 3,
        SpawnTimer = 1.2,
        PurchaseDebounceTime = 0,
        StartWave = 2,
        Icon = "rbxassetid://17514280373",
    },
    Speedy = {
        Cost = 65,
        Eco = 5,
        PurchaseAmount = 2,
        SpawnTimer = 1,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280012",
        StartWave = 3,
    },
    Slow = {
        Cost = 90,
        Eco = 8,
        PurchaseAmount = 3,
        SpawnTimer = 1.2,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280271",
        StartWave = 5,
    },
    Hidden = {
        Cost = 105,
        Eco = 10,
        PurchaseAmount = 2,
        SpawnTimer = 0.8,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280740",
        StartWave = 8,
    },
    ["Elite Abnormal"] = {
        Health = 120,
        Cost = 200,
        Eco = 15,
        PurchaseAmount = 1,
        SpawnTimer = 2,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280886",
        StartWave = 10,
    },
    Molten = {
        Cost = 210,
        Eco = 12,
        PurchaseAmount = 1,
        SpawnTimer = 1.2,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514281040",
        StartWave = 12,
    },
    ["Molten Hazmat"] = {
        Health = 300,
        Cost = 300,
        Eco = 20,
        PurchaseAmount = 1,
        SpawnTimer = 1.4,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280956",
        StartWave = 15,
    },
    Reaver = {
        Health = 1000,
        Cost = 600,
        Eco = 0,
        PurchaseAmount = 1,
        SpawnTimer = 1.75,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280635",
        StartWave = 18,
    },
    ["Molten Necromancer"] = {
        Health = 2000,
        Cost = 800,
        Eco = 0,
        PurchaseAmount = 1,
        SpawnTimer = 3,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280487",
        StartWave = 20,
    },
    ["Molten Golem"] = {
        Health = 3000,
        Cost = 1000,
        Eco = -25,
        PurchaseAmount = 1,
        SpawnTimer = 4,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280160",
        StartWave = 22,
    },
    ["Failed Experiment"] = {
        Health = 5000,
        Cost = 2000,
        Eco = -60,
        PurchaseAmount = 1,
        SpawnTimer = 5,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514279832",
        StartWave = 24,
    },
    ["Molten Titan"] = {
        Health = 6000,
        Cost = 4000,
        Eco = -150,
        PurchaseAmount = 1,
        SpawnTimer = 7,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280804",
        StartWave = 26,
        Modifiers = {[Enum.Modifier.HealthRegen] = true},
    },
}