-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.Autumn
-- Decompile time: 1.94 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("Beam", {
        Name = "Beam",
        FaceCamera = true,
        LightEmission = 1,
        Texture = "rbxassetid://119895054864943",
        TextureLength = 0.5,
        TextureSpeed = 0.2,
        Width0 = 1.3,
        Width1 = 1.3,
        ZOffset = -0.5,
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.503, 0.45),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("Attachment", {Name = "BeamEnd", CFrame = CFrame.new(-3, 0, 0)}),
    Create("Attachment", {Name = "BeamStart", CFrame = CFrame.new(3, 0, 0)}),
    Create("ParticleEmitter", {
        Name = "Leaf",
        Acceleration = Vector3.new(1, -2, -1),
        Brightness = 0.6,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 6,
        Texture = "rbxassetid://134690691456048",
        ZOffset = -1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
            ColorSequenceKeypoint.new(0.491, Color3.fromRGB(234, 234, 234)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(66, 66, 66))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        Lifetime = NumberRange.new(1, 2),
        RotSpeed = NumberRange.new(-66, 66),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.5, 0.25),
            NumberSequenceKeypoint.new(0.1, 0.386, 0.25),
            NumberSequenceKeypoint.new(0.2, 0.299, 0.25),
            NumberSequenceKeypoint.new(0.3, 0.226, 0.25),
            NumberSequenceKeypoint.new(0.4, 0.166, 0.25),
            NumberSequenceKeypoint.new(0.5, 0.115, 0.25),
            NumberSequenceKeypoint.new(0.6, 0.0741, 0.25),
            NumberSequenceKeypoint.new(0.7, 0.042, 0.25),
            NumberSequenceKeypoint.new(0.8, 0.0189, 0.25),
            NumberSequenceKeypoint.new(0.9, 0.00478, 0.25),
            NumberSequenceKeypoint.new(1, 0, 0.25),
            (NumberSequenceKeypoint.new(1, 0, 0.25)),
        }),
        Speed = NumberRange.new(-1, 1),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.302, 0),
            NumberSequenceKeypoint.new(0.897, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "Leaf2",
        Acceleration = Vector3.new(1, -2, -1),
        Brightness = 0.6,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 6,
        Texture = "rbxassetid://117514356976769",
        ZOffset = -0.9,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
            ColorSequenceKeypoint.new(0.491, Color3.fromRGB(234, 234, 234)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(66, 66, 66))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(1, 2),
        RotSpeed = NumberRange.new(-66, 66),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.5, 0.25),
            NumberSequenceKeypoint.new(0.1, 0.386, 0.25),
            NumberSequenceKeypoint.new(0.2, 0.299, 0.25),
            NumberSequenceKeypoint.new(0.3, 0.226, 0.25),
            NumberSequenceKeypoint.new(0.4, 0.166, 0.25),
            NumberSequenceKeypoint.new(0.5, 0.115, 0.25),
            NumberSequenceKeypoint.new(0.6, 0.0741, 0.25),
            NumberSequenceKeypoint.new(0.7, 0.042, 0.25),
            NumberSequenceKeypoint.new(0.8, 0.0189, 0.25),
            NumberSequenceKeypoint.new(0.9, 0.00478, 0.25),
            NumberSequenceKeypoint.new(1, 0, 0.25),
            (NumberSequenceKeypoint.new(1, 0, 0.25)),
        }),
        Speed = NumberRange.new(-1, 1),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.302, 0),
            NumberSequenceKeypoint.new(0.897, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    })),
}