-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.Binary
-- Decompile time: 2.04 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "Cloud1",
        LightInfluence = 1,
        LockedToPart = true,
        Rate = 4,
        Texture = "rbxassetid://10848625536",
        ZOffset = -0.147,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 0, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))),
        }),
        Lifetime = NumberRange.new(2, 2.6),
        RotSpeed = NumberRange.new(-25, 25),
        Rotation = NumberRange.new(0, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.392, 0.245),
            NumberSequenceKeypoint.new(0.5, 0.3, 0.245),
            (NumberSequenceKeypoint.new(1, 0.392, 0.245)),
        }),
        Speed = NumberRange.new(0.167, 0.225),
        SpreadAngle = Vector2.new(360, -360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.2, 0.9, 0.05),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Cloud2",
        Brightness = 5,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 4,
        Texture = "rbxassetid://10848625536",
        ZOffset = -0.147,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(180, 89, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(165, 101, 255))),
        }),
        Lifetime = NumberRange.new(2, 2.6),
        RotSpeed = NumberRange.new(-25, 25),
        Rotation = NumberRange.new(0, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.441, 0.245),
            NumberSequenceKeypoint.new(0.5, 0.4, 0.245),
            (NumberSequenceKeypoint.new(1, 0.441, 0.245)),
        }),
        Speed = NumberRange.new(0.167, 0.225),
        SpreadAngle = Vector2.new(360, -360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.2, 0.8, 0.07),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Lightning1",
        Brightness = 5,
        LockedToPart = true,
        LightEmission = 0.15,
        Rate = 5,
        Texture = "rbxassetid://13170413132",
        ZOffset = 0.1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(144, 88, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(144, 88, 255))),
        }),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
        Lifetime = NumberRange.new(0.4, 0.75),
        Orientation = Enum.ParticleOrientation.VelocityPerpendicular,
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.4), (NumberSequenceKeypoint.new(1, 0.4))}),
        Speed = NumberRange.new(0.00214),
        SpreadAngle = Vector2.new(-360, 360),
    }),
    Create("ParticleEmitter", {
        Name = "Lightning",
        Brightness = 5,
        LockedToPart = true,
        LightEmission = 0.15,
        Rate = 3,
        Texture = "rbxassetid://13889964143",
        ZOffset = 0.1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(212, 142, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(212, 142, 255))),
        }),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
        Lifetime = NumberRange.new(0.4, 0.75),
        Orientation = Enum.ParticleOrientation.VelocityPerpendicular,
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.4), (NumberSequenceKeypoint.new(1, 0.4))}),
        Speed = NumberRange.new(0.00214),
        SpreadAngle = Vector2.new(-360, 360),
    }),
    (Create("ParticleEmitter", {
        Name = "Numbers",
        Acceleration = Vector3.new(0, 1, 0),
        Drag = 5,
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 10,
        Texture = "rbxassetid://13283439452",
        ZOffset = 0.1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(184, 112, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(184, 112, 255))),
        }),
        EmissionDirection = Enum.NormalId.Bottom,
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        FlipbookMode = Enum.ParticleFlipbookMode.PingPong,
        Lifetime = NumberRange.new(1),
        RotSpeed = NumberRange.new(10),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.2, 0.2),
            (NumberSequenceKeypoint.new(1, 0.1)),
        }),
        Speed = NumberRange.new(0.5, 1),
        SpreadAngle = Vector2.new(0, 45),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.3, 0),
            NumberSequenceKeypoint.new(0.5, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    })),
}