-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.Blizzard
-- Decompile time: 3.36 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "BaseSmoke",
        Acceleration = Vector3.new(0, -0.6050000190734863, 0),
        Brightness = 2,
        Drag = 3,
        FlipbookStartRandom = true,
        LightEmission = 0.3,
        LockedToPart = true,
        Rate = 12,
        ShapePartial = 0.4,
        Texture = "rbxassetid://16815669870",
        ZOffset = -0.4,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(164, 200, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(164, 200, 255))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(2),
        RotSpeed = NumberRange.new(-33, 33),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.735, 0.49),
            NumberSequenceKeypoint.new(0.1, 0.882, 0.49),
            NumberSequenceKeypoint.new(0.2, 0.958, 0.49),
            NumberSequenceKeypoint.new(0.3, 1.02, 0.49),
            NumberSequenceKeypoint.new(0.4, 1.07, 0.49),
            NumberSequenceKeypoint.new(0.5, 1.11, 0.49),
            NumberSequenceKeypoint.new(0.6, 1.15, 0.49),
            NumberSequenceKeypoint.new(0.7, 1.18, 0.49),
            NumberSequenceKeypoint.new(0.8, 1.2, 0.49),
            NumberSequenceKeypoint.new(0.9, 1.22, 0.49),
            NumberSequenceKeypoint.new(1, 1.22, 0.49),
            (NumberSequenceKeypoint.new(1, 1.22, 0.49)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.499, 0.612, 0.1),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Flakes",
        Acceleration = Vector3.new(0, -9, 0),
        Brightness = 11,
        Drag = 9,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 8,
        Texture = "rbxassetid://92655746950496",
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(153, 214, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 60, 255))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        Lifetime = NumberRange.new(2, 3),
        RotSpeed = NumberRange.new(-234, 234),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.192, 0),
            NumberSequenceKeypoint.new(0.2, 0.294, 0.139),
            NumberSequenceKeypoint.new(0.3, 0.268, 0.139),
            NumberSequenceKeypoint.new(0.4, 0.241, 0.139),
            NumberSequenceKeypoint.new(0.5, 0.212, 0.139),
            NumberSequenceKeypoint.new(0.6, 0.18, 0.139),
            NumberSequenceKeypoint.new(0.7, 0.146, 0.139),
            NumberSequenceKeypoint.new(0.8, 0.106, 0.106),
            NumberSequenceKeypoint.new(0.9, 0.0591, 0.0591),
            NumberSequenceKeypoint.new(1, 3.86e-17, 3.86e-17),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(5, 10),
        SpreadAngle = Vector2.new(11, 11),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.191, 1),
            NumberSequenceKeypoint.new(0.464, 0),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Flakes",
        Acceleration = Vector3.new(0, -9, 0),
        Brightness = 11,
        Drag = 9,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 10,
        Texture = "rbxassetid://121336108859764",
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(153, 214, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 60, 255))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(2, 3),
        RotSpeed = NumberRange.new(-55, 55),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.5),
            NumberSequenceKeypoint.new(0.1, 0.617),
            NumberSequenceKeypoint.new(0.2, 0.707),
            NumberSequenceKeypoint.new(0.3, 0.78),
            NumberSequenceKeypoint.new(0.4, 0.84),
            NumberSequenceKeypoint.new(0.5, 0.89),
            NumberSequenceKeypoint.new(0.6, 0.929),
            NumberSequenceKeypoint.new(0.7, 0.96),
            NumberSequenceKeypoint.new(0.8, 0.982),
            NumberSequenceKeypoint.new(0.9, 0.995),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
        Speed = NumberRange.new(1, 2),
        SpreadAngle = Vector2.new(11, 11),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.5, 0.762, 0.113),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "BrighttSwirl",
        Acceleration = Vector3.new(0, -1, 0),
        Brightness = 5,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 11,
        Texture = "rbxassetid://80397661829393",
        ZOffset = -2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(143, 188, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 89, 255))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(1, 2),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Cylinder,
        ShapeStyle = Enum.ParticleEmitterShapeStyle.Surface,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.499, 0.125),
            NumberSequenceKeypoint.new(0.1, 0.622, 0.125),
            NumberSequenceKeypoint.new(0.2, 0.717, 0.125),
            NumberSequenceKeypoint.new(0.3, 0.794, 0.125),
            NumberSequenceKeypoint.new(0.4, 0.854, 0.125),
            NumberSequenceKeypoint.new(0.5, 0.902, 0.125),
            NumberSequenceKeypoint.new(0.6, 0.939, 0.125),
            NumberSequenceKeypoint.new(0.7, 0.966, 0.125),
            NumberSequenceKeypoint.new(0.8, 0.985, 0.125),
            NumberSequenceKeypoint.new(0.9, 0.996, 0.125),
            NumberSequenceKeypoint.new(1, 0.999, 0.125),
            (NumberSequenceKeypoint.new(1, 0.999, 0.125)),
        }),
        Speed = NumberRange.new(0),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.5, 0.744),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "ColdSparkles",
        Brightness = 3,
        Drag = 4,
        LightEmission = 1,
        Rate = 16,
        Texture = "rbxassetid://16797040962",
        ZOffset = 2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(96, 195, 249)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(96, 195, 249))),
        }),
        Lifetime = NumberRange.new(0.3, 0.6),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.347, 0.125, 0.0417),
            NumberSequenceKeypoint.new(0.501, 0.0209, 0.00186),
            NumberSequenceKeypoint.new(0.645, 0.125, 0.0417),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(-360, 360),
    })),
}