-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.CircuitHacker
-- Decompile time: 4.66 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Create = require(ReplicatedStorage.Shared.Modules.Standalone.Create)
local Children = Create.Children
local v1 = {}
local v2 = Create("ParticleEmitter", {
    Name = "TriangleFlip",
    Brightness = 4,
    Drag = 12,
    FlipbookStartRandom = true,
    LightEmission = 1,
    LockedToPart = true,
    Rate = 9,
    Texture = "rbxassetid://17417997036",
    ZOffset = 1,
    Color = ColorSequence.new({
        ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 255, 115)),
        (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 255, 115))),
    }),
    FlipbookFramerate = NumberRange.new(0),
    FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
    Lifetime = NumberRange.new(0.5, 1),
    Rotation = NumberRange.new(-360, 360),
    Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.127, 0.0633), (NumberSequenceKeypoint.new(1, 0))}),
    Speed = NumberRange.new(1.27, 5.7),
    SpreadAngle = Vector2.new(-360, 360),
    Transparency = NumberSequence.new({
        NumberSequenceKeypoint.new(0, 0.5, 0.2),
        NumberSequenceKeypoint.new(0.502, 0.494, 0.2),
        NumberSequenceKeypoint.new(0.504, 1),
        NumberSequenceKeypoint.new(0.638, 1),
        NumberSequenceKeypoint.new(0.641, 0.494, 0.2),
        NumberSequenceKeypoint.new(0.67, 0.5, 0.2),
        NumberSequenceKeypoint.new(0.671, 1),
        NumberSequenceKeypoint.new(0.752, 1),
        NumberSequenceKeypoint.new(0.754, 0.731, 0.2),
        NumberSequenceKeypoint.new(0.819, 0.75, 0.2),
        NumberSequenceKeypoint.new(0.823, 1),
        NumberSequenceKeypoint.new(0.885, 1),
        NumberSequenceKeypoint.new(0.892, 0.75, 0.2),
        NumberSequenceKeypoint.new(0.912, 0.756, 0.2),
        NumberSequenceKeypoint.new(0.919, 1),
        (NumberSequenceKeypoint.new(1, 1)),
    }),
})
local v3 = Create("ParticleEmitter", {
    Name = "TriangleFlip2",
    Brightness = 4,
    Drag = 12,
    FlipbookStartRandom = true,
    LightEmission = 1,
    LockedToPart = true,
    Rate = 9,
    Texture = "rbxassetid://17417997036",
    ZOffset = 1,
    Color = ColorSequence.new({
        ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 140, 0)),
        (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 140, 0))),
    }),
    FlipbookFramerate = NumberRange.new(0),
    FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
    Lifetime = NumberRange.new(0.5, 1),
    Rotation = NumberRange.new(-360, 360),
    Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.127, 0.0633), (NumberSequenceKeypoint.new(1, 0))}),
    Speed = NumberRange.new(1.27, 5.7),
    SpreadAngle = Vector2.new(-360, 360),
    Transparency = NumberSequence.new({
        NumberSequenceKeypoint.new(0, 0.5, 0.2),
        NumberSequenceKeypoint.new(0.502, 0.494, 0.2),
        NumberSequenceKeypoint.new(0.504, 1),
        NumberSequenceKeypoint.new(0.638, 1),
        NumberSequenceKeypoint.new(0.641, 0.494, 0.2),
        NumberSequenceKeypoint.new(0.67, 0.5, 0.2),
        NumberSequenceKeypoint.new(0.671, 1),
        NumberSequenceKeypoint.new(0.752, 1),
        NumberSequenceKeypoint.new(0.754, 0.731, 0.2),
        NumberSequenceKeypoint.new(0.819, 0.75, 0.2),
        NumberSequenceKeypoint.new(0.823, 1),
        NumberSequenceKeypoint.new(0.885, 1),
        NumberSequenceKeypoint.new(0.892, 0.75, 0.2),
        NumberSequenceKeypoint.new(0.912, 0.756, 0.2),
        NumberSequenceKeypoint.new(0.919, 1),
        (NumberSequenceKeypoint.new(1, 1)),
    }),
})
local v4 = Create("Attachment", {Name = "2", CFrame = CFrame.new(-2.0803833, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1)})
local v5 = {Name = "1", CFrame = CFrame.new(2.01098633, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1)}
v5[Children] = {
    Create("Beam", {
        Name = "BaseColor",
        FaceCamera = true,
        Texture = "rbxassetid://82101317617559",
        TextureLength = 6,
        TextureSpeed = 1.5,
        ZOffset = -0.2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 70, 44)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 70, 44))),
        }),
        TextureMode = Enum.TextureMode.Static,
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.0996, 0.737),
            NumberSequenceKeypoint.new(0.5, 0.489),
            NumberSequenceKeypoint.new(0.9, 0.742),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("Beam", {
        Name = "GlowBaseCircuoit",
        FaceCamera = true,
        LightEmission = 1,
        Texture = "rbxassetid://136819026347087",
        TextureLength = 6,
        TextureSpeed = 2.5,
        Width0 = 1.17,
        Width1 = 1.17,
        ZOffset = -0.5,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 193, 87)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 193, 87))),
        }),
        TextureMode = Enum.TextureMode.Static,
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.0996, 0.737),
            NumberSequenceKeypoint.new(0.5, 0.174),
            NumberSequenceKeypoint.new(0.9, 0.742),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("Beam", {
        Name = "DarkBaseCircuit",
        FaceCamera = true,
        Texture = "rbxassetid://89407921440654",
        TextureLength = 6,
        TextureSpeed = 1.5,
        Width0 = 0.876,
        Width1 = 0.876,
        ZOffset = -0.5,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 70, 44)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 70, 44))),
        }),
        TextureMode = Enum.TextureMode.Static,
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.0996, 0.737),
            NumberSequenceKeypoint.new(0.5, 0.174),
            NumberSequenceKeypoint.new(0.9, 0.742),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("Beam", {
        Name = "DarkOrangCircuit",
        FaceCamera = true,
        LightEmission = 1,
        Texture = "rbxassetid://124950043053181",
        TextureLength = 6,
        TextureSpeed = 1.22,
        Width0 = 0.6,
        Width1 = 0.6,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 64, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 64, 0))),
        }),
        TextureMode = Enum.TextureMode.Static,
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.0416, 0),
            NumberSequenceKeypoint.new(0.201, 0),
            NumberSequenceKeypoint.new(0.303, 1),
            NumberSequenceKeypoint.new(0.7, 1),
            NumberSequenceKeypoint.new(0.798, 0),
            NumberSequenceKeypoint.new(0.961, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("Beam", {
        Name = "GreenBaseCircuitStart",
        FaceCamera = true,
        LightEmission = 0.2,
        Texture = "rbxassetid://132662482058269",
        TextureLength = 6,
        TextureSpeed = 0.25,
        ZOffset = -0.5,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 47, 14)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 47, 14))),
        }),
        TextureMode = Enum.TextureMode.Static,
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.0461, 0),
            NumberSequenceKeypoint.new(0.958, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    })),
}
v1[1] = v2
v1[2] = v3
v1[3] = v4
v1[4] = Create("Attachment", v5)
return v1