-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.Conserver
-- Decompile time: 2.62 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("Beam", {
        Name = "Beam",
        Brightness = 2,
        FaceCamera = true,
        LightEmission = 1,
        Segments = 5,
        Texture = "rbxassetid://117273868487089",
        TextureLength = 0.3,
        TextureSpeed = 0.12,
        Width0 = 2,
        Width1 = 2,
        ZOffset = -0.95,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(47, 0, 18)),
            ColorSequenceKeypoint.new(0.517, Color3.fromRGB(255, 0, 144)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(47, 0, 18))),
        }),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.503, 0.45),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("Beam", {
        Name = "Beam",
        FaceCamera = true,
        Segments = 12,
        Texture = "rbxassetid://88155700208463",
        TextureLength = 0.12,
        TextureSpeed = 0.2,
        Width0 = 2.5,
        Width1 = 2.5,
        ZOffset = -1.2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(27, 0, 10)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(27, 0, 10))),
        }),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.504, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("Attachment", {Name = "BeamEnd", CFrame = CFrame.new(-3, 0, 0)}),
    Create("Attachment", {Name = "BeamStart", CFrame = CFrame.new(3, 0, 0)}),
    Create("ParticleEmitter", {
        Name = "BgSmoke",
        Drag = 2,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 12,
        Texture = "rbxassetid://80397661829393",
        WindAffectsDrag = true,
        ZOffset = -1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 0, 76)),
            ColorSequenceKeypoint.new(0.119, Color3.fromRGB(42, 0, 8)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.6, 1.2),
        RotSpeed = NumberRange.new(-22, 22),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.1, 1.08),
            NumberSequenceKeypoint.new(0.2, 1.15),
            NumberSequenceKeypoint.new(0.3, 1.23),
            NumberSequenceKeypoint.new(0.4, 1.31),
            NumberSequenceKeypoint.new(0.5, 1.39),
            NumberSequenceKeypoint.new(0.6, 1.48),
            NumberSequenceKeypoint.new(0.7, 1.58),
            NumberSequenceKeypoint.new(0.8, 1.69),
            NumberSequenceKeypoint.new(0.9, 1.83),
            NumberSequenceKeypoint.new(1, 2),
            (NumberSequenceKeypoint.new(1, 2)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(11, 1),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.0349, 0.45),
            NumberSequenceKeypoint.new(0.0624, 0.144),
            NumberSequenceKeypoint.new(0.111, 0.0437),
            NumberSequenceKeypoint.new(0.2, 0.0706),
            NumberSequenceKeypoint.new(0.3, 0.169),
            NumberSequenceKeypoint.new(0.4, 0.314),
            NumberSequenceKeypoint.new(0.5, 0.492),
            NumberSequenceKeypoint.new(0.6, 0.672),
            NumberSequenceKeypoint.new(0.7, 0.822),
            NumberSequenceKeypoint.new(0.8, 0.926),
            NumberSequenceKeypoint.new(0.9, 0.983),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "DarkBits",
        Acceleration = Vector3.new(0, -6.369999885559082, 0),
        Drag = 8,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 12,
        Texture = "rbxassetid://122163870704403",
        ZOffset = -1.1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 0, 157)),
            ColorSequenceKeypoint.new(0.0744, Color3.fromRGB(241, 0, 108)),
            ColorSequenceKeypoint.new(0.164, Color3.fromRGB(212, 0, 57)),
            ColorSequenceKeypoint.new(0.24, Color3.fromRGB(106, 0, 24)),
            ColorSequenceKeypoint.new(0.524, Color3.fromRGB(60, 0, 9)),
            ColorSequenceKeypoint.new(0.697, Color3.fromRGB(34, 0, 4)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(11, 0, 0))),
        }),
        EmissionDirection = Enum.NormalId.Front,
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.4, 2),
        RotSpeed = NumberRange.new(-222, 222),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.45),
            NumberSequenceKeypoint.new(0.1, 0.336),
            NumberSequenceKeypoint.new(0.2, 0.256),
            NumberSequenceKeypoint.new(0.3, 0.193),
            NumberSequenceKeypoint.new(0.4, 0.14),
            NumberSequenceKeypoint.new(0.5, 0.0973),
            NumberSequenceKeypoint.new(0.6, 0.0625),
            NumberSequenceKeypoint.new(0.7, 0.0354),
            NumberSequenceKeypoint.new(0.8, 0.0159),
            NumberSequenceKeypoint.new(0.9, 0.00403),
            NumberSequenceKeypoint.new(1, 0),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(-3, 3),
        SpreadAngle = Vector2.new(-360, 360),
    })),
}