-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.Curse
-- Decompile time: 2.57 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "BaseSmoke",
        Acceleration = Vector3.new(0, -0.125, 0),
        Drag = 3,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 11,
        Texture = "rbxassetid://14449330724",
        ZOffset = -1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 6, 22)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 6, 22))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(2, 4),
        RotSpeed = NumberRange.new(-44, 44),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Cylinder,
        ShapeStyle = Enum.ParticleEmitterShapeStyle.Surface,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.5),
            NumberSequenceKeypoint.new(0.1, 0.525),
            NumberSequenceKeypoint.new(0.2, 0.602),
            NumberSequenceKeypoint.new(0.3, 0.731),
            NumberSequenceKeypoint.new(0.4, 0.898),
            NumberSequenceKeypoint.new(0.5, 1.07),
            NumberSequenceKeypoint.new(0.6, 1.23),
            NumberSequenceKeypoint.new(0.7, 1.36),
            NumberSequenceKeypoint.new(0.8, 1.44),
            NumberSequenceKeypoint.new(0.9, 1.49),
            NumberSequenceKeypoint.new(1, 1.5),
            (NumberSequenceKeypoint.new(1, 1.5)),
        }),
        Speed = NumberRange.new(-1, 1),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.499, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "CommonSparkle",
        Acceleration = Vector3.new(0, 1, 0),
        Brightness = 3,
        Drag = 4,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 16,
        Texture = "rbxassetid://16797358538",
        ZOffset = 2.5,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(249, 24, 111)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(249, 24, 111))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.3, 0.6),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.345, 0.264),
            NumberSequenceKeypoint.new(0.501, 0.34),
            NumberSequenceKeypoint.new(0.648, 0.245),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(-360, 360),
    }),
    Create("ParticleEmitter", {
        Name = "Dots",
        Brightness = 4,
        Drag = 3,
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 4,
        ShapePartial = 0.4,
        Texture = "rbxassetid://11800717040",
        ZOffset = 1.2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 0, 4)),
            ColorSequenceKeypoint.new(0.427, Color3.fromRGB(255, 0, 98)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(128, 0, 255))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        Lifetime = NumberRange.new(3, 6),
        RotSpeed = NumberRange.new(-33, 33),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.13, 0.479, 0.0771),
            NumberSequenceKeypoint.new(0.3, 0.258, 0.107),
            NumberSequenceKeypoint.new(0.4, 0.884, 0.146),
            NumberSequenceKeypoint.new(0.5, 0.663, 0.184),
            NumberSequenceKeypoint.new(0.6, 0.147, 0.146),
            NumberSequenceKeypoint.new(0.698, 0.295, 0.11),
            NumberSequenceKeypoint.new(0.799, 0.811, 0.15),
            NumberSequenceKeypoint.new(0.895, 0.553, 0.19),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(-4, 4),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.497, 0.462, 0.137),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "GlowSmoke",
        Acceleration = Vector3.new(0, -0.125, 0),
        Drag = 3,
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 3,
        Texture = "rbxassetid://14449330724",
        ZOffset = 1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(134, 0, 47)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(134, 0, 47))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(2, 4),
        RotSpeed = NumberRange.new(-44, 44),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Cylinder,
        ShapeStyle = Enum.ParticleEmitterShapeStyle.Surface,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.5),
            NumberSequenceKeypoint.new(0.1, 0.525),
            NumberSequenceKeypoint.new(0.2, 0.602),
            NumberSequenceKeypoint.new(0.3, 0.731),
            NumberSequenceKeypoint.new(0.4, 0.898),
            NumberSequenceKeypoint.new(0.5, 1.07),
            NumberSequenceKeypoint.new(0.6, 1.23),
            NumberSequenceKeypoint.new(0.7, 1.36),
            NumberSequenceKeypoint.new(0.8, 1.44),
            NumberSequenceKeypoint.new(0.9, 1.49),
            NumberSequenceKeypoint.new(1, 1.5),
            (NumberSequenceKeypoint.new(1, 1.5)),
        }),
        Speed = NumberRange.new(-1, 1),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.499, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    })),
}