-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.d3bugf
-- Decompile time: 3.11 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "BackGlitch",
        Brightness = 12,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 8,
        Texture = "rbxassetid://116292496855722",
        ZOffset = -1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 0, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))),
        }),
        FlipbookFramerate = NumberRange.new(14),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.2, 0.6),
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.709), (NumberSequenceKeypoint.new(1, 0.709))}),
        Speed = NumberRange.new(0.000945),
    }),
    Create("ParticleEmitter", {
        Name = "BackgroundSmoke",
        Acceleration = Vector3.new(0, 8.180000305175781, 0),
        Drag = 3,
        FlipbookStartRandom = true,
        LightEmission = 0.1,
        LockedToPart = true,
        Rate = 16,
        Texture = "rbxassetid://122423485973951",
        ZOffset = -1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(243, 243, 243)),
            ColorSequenceKeypoint.new(0.354, Color3.fromRGB(89, 88, 117)),
            ColorSequenceKeypoint.new(0.459, Color3.fromRGB(65, 64, 97)),
            ColorSequenceKeypoint.new(0.725, Color3.fromRGB(1, 0, 45)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
        Lifetime = NumberRange.new(0.4, 0.8),
        RotSpeed = NumberRange.new(-33, 33),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Sphere,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.681),
            NumberSequenceKeypoint.new(0.1, 0.69),
            NumberSequenceKeypoint.new(0.2, 0.72),
            NumberSequenceKeypoint.new(0.3, 0.784),
            NumberSequenceKeypoint.new(0.4, 0.895),
            NumberSequenceKeypoint.new(0.5, 1.05),
            NumberSequenceKeypoint.new(0.6, 1.19),
            NumberSequenceKeypoint.new(0.7, 1.28),
            NumberSequenceKeypoint.new(0.8, 1.33),
            NumberSequenceKeypoint.new(0.9, 1.36),
            NumberSequenceKeypoint.new(1, 1.36),
            (NumberSequenceKeypoint.new(1, 1.36)),
        }),
        Speed = NumberRange.new(0.681, 1.36),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.497, 0),
            NumberSequenceKeypoint.new(0.703, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "BigGlitch",
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 4,
        Texture = "rbxassetid://89946513141185",
        ZOffset = 1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(76, 0, 163)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(76, 0, 163))),
        }),
        FlipbookFramerate = NumberRange.new(14),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        Lifetime = NumberRange.new(0.2, 0.6),
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 1.21), (NumberSequenceKeypoint.new(1, 1.21))}),
        Speed = NumberRange.new(0.00161),
        Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.5), (NumberSequenceKeypoint.new(1, 0.5))}),
    }),
    Create("ParticleEmitter", {
        Name = "FgSmoke",
        Acceleration = Vector3.new(0, 9.869999885559082, 0),
        Brightness = 2,
        Drag = 3,
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 12,
        Texture = "rbxassetid://80397661829393",
        ZOffset = 1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 166, 255)),
            ColorSequenceKeypoint.new(0.1, Color3.fromRGB(220, 47, 255)),
            ColorSequenceKeypoint.new(0.206, Color3.fromRGB(170, 0, 255)),
            ColorSequenceKeypoint.new(0.314, Color3.fromRGB(83, 0, 184)),
            ColorSequenceKeypoint.new(0.595, Color3.fromRGB(3, 0, 42)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 8, 43))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.5, 1),
        RotSpeed = NumberRange.new(-33, 33),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Sphere,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.822),
            NumberSequenceKeypoint.new(0.1, 0.832),
            NumberSequenceKeypoint.new(0.2, 0.869),
            NumberSequenceKeypoint.new(0.3, 0.946),
            NumberSequenceKeypoint.new(0.4, 1.08),
            NumberSequenceKeypoint.new(0.5, 1.27),
            NumberSequenceKeypoint.new(0.6, 1.43),
            NumberSequenceKeypoint.new(0.7, 1.54),
            NumberSequenceKeypoint.new(0.8, 1.61),
            NumberSequenceKeypoint.new(0.9, 1.64),
            NumberSequenceKeypoint.new(1, 1.64),
            (NumberSequenceKeypoint.new(1, 1.64)),
        }),
        Speed = NumberRange.new(0.822, 1.64),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.499, 0.244, 0.113),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "Pixels",
        Acceleration = Vector3.new(0, -2.6600000858306885, 0),
        Brightness = 32,
        Drag = 10,
        FlipbookStartRandom = true,
        Rate = 32,
        Texture = "rbxassetid://17255941017",
        ZOffset = 0.6,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(217, 0, 255)),
            ColorSequenceKeypoint.new(0.629, Color3.fromRGB(4, 0, 34)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        Lifetime = NumberRange.new(0.3, 0.6),
        Shape = Enum.ParticleEmitterShape.Disc,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.0988, 0),
            NumberSequenceKeypoint.new(0.2, 0.366, 0.366),
            NumberSequenceKeypoint.new(0.3, 0.278, 0.278),
            NumberSequenceKeypoint.new(0.4, 0.206, 0.206),
            NumberSequenceKeypoint.new(0.5, 0.145, 0.145),
            NumberSequenceKeypoint.new(0.6, 0.0954, 0.0954),
            NumberSequenceKeypoint.new(0.7, 0.0554, 0.0554),
            NumberSequenceKeypoint.new(0.8, 0.0257, 0.0257),
            NumberSequenceKeypoint.new(0.9, 0.00673, 0.00673),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(5, 15),
        SpreadAngle = Vector2.new(11, 11),
    })),
}