-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.DarkMist
-- Decompile time: 3.39 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "SpookySmokeDetail",
        Drag = 3,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 12,
        Texture = "rbxassetid://123101764181758",
        ZOffset = -0.8,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 0, 234)),
            ColorSequenceKeypoint.new(0.0467, Color3.fromRGB(149, 0, 241)),
            ColorSequenceKeypoint.new(0.106, Color3.fromRGB(95, 0, 212)),
            ColorSequenceKeypoint.new(0.22, Color3.fromRGB(44, 0, 106)),
            ColorSequenceKeypoint.new(0.384, Color3.fromRGB(19, 0, 60)),
            ColorSequenceKeypoint.new(0.5, Color3.fromRGB(14, 0, 34)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(11, 0, 0))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(3, 5),
        RotSpeed = NumberRange.new(-33, 33),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Cylinder,
        ShapeStyle = Enum.ParticleEmitterShapeStyle.Surface,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.333, 0.166),
            NumberSequenceKeypoint.new(0.1, 0.496, 0.166),
            NumberSequenceKeypoint.new(0.2, 0.623, 0.166),
            NumberSequenceKeypoint.new(0.3, 0.725, 0.166),
            NumberSequenceKeypoint.new(0.4, 0.806, 0.166),
            NumberSequenceKeypoint.new(0.5, 0.87, 0.166),
            NumberSequenceKeypoint.new(0.6, 0.919, 0.166),
            NumberSequenceKeypoint.new(0.7, 0.956, 0.166),
            NumberSequenceKeypoint.new(0.8, 0.98, 0.166),
            NumberSequenceKeypoint.new(0.9, 0.994, 0.166),
            NumberSequenceKeypoint.new(1, 0.999, 0.166),
            (NumberSequenceKeypoint.new(1, 0.999, 0.166)),
        }),
        Speed = NumberRange.new(0.666, 1.33),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.501, 0.294, 0.0625),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "LightningSmoke",
        Drag = 3,
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 2,
        Texture = "rbxassetid://123101764181758",
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(205, 106, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(183, 0, 255))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(1, 3),
        RotSpeed = NumberRange.new(-33, 33),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Cylinder,
        ShapeStyle = Enum.ParticleEmitterShapeStyle.Surface,
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.901), (NumberSequenceKeypoint.new(1, 0.901))}),
        Speed = NumberRange.new(0.375, 0.749),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.121, 1),
            NumberSequenceKeypoint.new(0.158, 0),
            NumberSequenceKeypoint.new(0.195, 1),
            NumberSequenceKeypoint.new(0.325, 1),
            NumberSequenceKeypoint.new(0.342, 0),
            NumberSequenceKeypoint.new(0.36, 1),
            NumberSequenceKeypoint.new(0.641, 1),
            NumberSequenceKeypoint.new(0.666, 0),
            NumberSequenceKeypoint.new(0.692, 1),
            NumberSequenceKeypoint.new(0.876, 1),
            NumberSequenceKeypoint.new(0.898, 0),
            NumberSequenceKeypoint.new(0.912, 1),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "BrighttSwirl",
        Acceleration = Vector3.new(0.7490000128746033, 0, 0),
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 11,
        Texture = "rbxassetid://80397661829393",
        ZOffset = 0.13,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 0, 234)),
            ColorSequenceKeypoint.new(0.567, Color3.fromRGB(149, 0, 241)),
            ColorSequenceKeypoint.new(0.818, Color3.fromRGB(19, 0, 60)),
            ColorSequenceKeypoint.new(0.926, Color3.fromRGB(14, 0, 34)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(11, 0, 0))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(1, 2),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Cylinder,
        ShapeStyle = Enum.ParticleEmitterShapeStyle.Surface,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.499, 0.125),
            NumberSequenceKeypoint.new(0.1, 0.622, 0.125),
            NumberSequenceKeypoint.new(0.2, 0.717, 0.125),
            NumberSequenceKeypoint.new(0.3, 0.794, 0.125),
            NumberSequenceKeypoint.new(0.4, 0.854, 0.125),
            NumberSequenceKeypoint.new(0.5, 0.902, 0.125),
            NumberSequenceKeypoint.new(0.6, 0.939, 0.125),
            NumberSequenceKeypoint.new(0.7, 0.966, 0.125),
            NumberSequenceKeypoint.new(0.8, 0.985, 0.125),
            NumberSequenceKeypoint.new(0.9, 0.996, 0.125),
            NumberSequenceKeypoint.new(1, 0.999, 0.125),
            (NumberSequenceKeypoint.new(1, 0.999, 0.125)),
        }),
        Speed = NumberRange.new(0),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.5, 0.744),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "LightntingMid",
        Brightness = 12,
        Drag = 2,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 4,
        Texture = "rbxassetid://74029571283102",
        ZOffset = 2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(135, 55, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(135, 55, 255))),
        }),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
        Lifetime = NumberRange.new(0.3, 0.65),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 1.42), (NumberSequenceKeypoint.new(1, 1.42))}),
        Speed = NumberRange.new(0.173),
        SpreadAngle = Vector2.new(60, 60),
    })),
}