-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.FrozenS
-- Decompile time: 4.56 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
local Children = Create.Children
return {
    Create("ParticleEmitter", {
        Name = "Snowflakes",
        Brightness = 4,
        Drag = 2,
        FlipbookStartRandom = true,
        LightEmission = 3,
        LockedToPart = true,
        Rate = 4,
        Texture = "rbxassetid://87720461929018",
        ZOffset = 2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 132, 255)),
            ColorSequenceKeypoint.new(0.526, Color3.fromRGB(138, 185, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 132, 255))),
        }),
        FlipbookFramerate = NumberRange.new(18, 28),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        Lifetime = NumberRange.new(2, 4),
        Orientation = Enum.ParticleOrientation.VelocityParallel,
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.499, 0.249, 0.065),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(-1.62, 1.62),
        SpreadAngle = Vector2.new(-360, 360),
    }),
    Create("ParticleEmitter", {
        Name = "Snow",
        Acceleration = Vector3.new(0, -3.8499999046325684, 0),
        Brightness = 3,
        Drag = 9,
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 18,
        ShapePartial = 0.4,
        Texture = "rbxassetid://17696603161",
        ZOffset = 0.2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(158, 205, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(21, 91, 255))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        Lifetime = NumberRange.new(1, 2),
        RotSpeed = NumberRange.new(-22, 22),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.405),
            NumberSequenceKeypoint.new(0.1, 0.595),
            NumberSequenceKeypoint.new(0.2, 0.726),
            NumberSequenceKeypoint.new(0.3, 0.818),
            NumberSequenceKeypoint.new(0.4, 0.884),
            NumberSequenceKeypoint.new(0.5, 0.931),
            NumberSequenceKeypoint.new(0.6, 0.964),
            NumberSequenceKeypoint.new(0.7, 0.987),
            NumberSequenceKeypoint.new(0.8, 1),
            NumberSequenceKeypoint.new(0.9, 1.01),
            NumberSequenceKeypoint.new(1, 1.01),
            (NumberSequenceKeypoint.new(1, 1.01)),
        }),
        Speed = NumberRange.new(0.5, 1),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.208, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Glow",
        LightEmission = 1,
        LockedToPart = true,
        Rate = 4,
        Texture = "rbxassetid://16788448905",
        ZOffset = 2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(84, 161, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(84, 161, 255))),
        }),
        Lifetime = NumberRange.new(2),
        Shape = Enum.ParticleEmitterShape.Sphere,
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 1.28), (NumberSequenceKeypoint.new(1, 1.28))}),
        Speed = NumberRange.new(0),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.2), (NumberSequenceKeypoint.new(1, 0.2))}),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.498, 0.762),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Flakes",
        Acceleration = Vector3.new(0, -11.899999618530273, 0),
        Brightness = 22,
        Drag = 4,
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 12,
        Texture = "rbxassetid://86955303191069",
        ZOffset = 2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(78, 172, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(78, 172, 255))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(1, 2),
        RotSpeed = NumberRange.new(-66, 66),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.192, 0),
            NumberSequenceKeypoint.new(0.291, 0),
            NumberSequenceKeypoint.new(0.3, 0.196, 0.102),
            NumberSequenceKeypoint.new(0.4, 0.176, 0.102),
            NumberSequenceKeypoint.new(0.5, 0.155, 0.102),
            NumberSequenceKeypoint.new(0.6, 0.132, 0.102),
            NumberSequenceKeypoint.new(0.7, 0.107, 0.102),
            NumberSequenceKeypoint.new(0.8, 0.0775, 0.0775),
            NumberSequenceKeypoint.new(0.9, 0.0433, 0.0433),
            NumberSequenceKeypoint.new(1, 2.83e-17, 2.83e-17),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(3, 6),
        SpreadAngle = Vector2.new(11, 11),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.191, 1),
            NumberSequenceKeypoint.new(0.464, 0),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "BrighttSwirl",
        Acceleration = Vector3.new(0, -1, 0),
        Brightness = 5,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 11,
        Texture = "rbxassetid://80397661829393",
        ZOffset = -2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(143, 188, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 89, 255))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(1, 2),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Cylinder,
        ShapeStyle = Enum.ParticleEmitterShapeStyle.Surface,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.499, 0.125),
            NumberSequenceKeypoint.new(0.1, 0.622, 0.125),
            NumberSequenceKeypoint.new(0.2, 0.717, 0.125),
            NumberSequenceKeypoint.new(0.3, 0.794, 0.125),
            NumberSequenceKeypoint.new(0.4, 0.854, 0.125),
            NumberSequenceKeypoint.new(0.5, 0.902, 0.125),
            NumberSequenceKeypoint.new(0.6, 0.939, 0.125),
            NumberSequenceKeypoint.new(0.7, 0.966, 0.125),
            NumberSequenceKeypoint.new(0.8, 0.985, 0.125),
            NumberSequenceKeypoint.new(0.9, 0.996, 0.125),
            NumberSequenceKeypoint.new(1, 0.999, 0.125),
            (NumberSequenceKeypoint.new(1, 0.999, 0.125)),
        }),
        Speed = NumberRange.new(0),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.5, 0.744),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "BaseSmoke",
        Acceleration = Vector3.new(0, -0.8849999904632568, 0),
        LightEmission = 0.1,
        LockedToPart = true,
        Rate = 22,
        ShapePartial = 0.4,
        Texture = "rbxassetid://138210092362719",
        ZOffset = -0.6,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 11, 35)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 11, 35))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
        Lifetime = NumberRange.new(2),
        RotSpeed = NumberRange.new(-33, 33),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Sphere,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1, 0.5),
            NumberSequenceKeypoint.new(0.1, 1.04, 0.5),
            NumberSequenceKeypoint.new(0.2, 1.08, 0.5),
            NumberSequenceKeypoint.new(0.3, 1.12, 0.5),
            NumberSequenceKeypoint.new(0.4, 1.16, 0.5),
            NumberSequenceKeypoint.new(0.5, 1.2, 0.5),
            NumberSequenceKeypoint.new(0.6, 1.25, 0.5),
            NumberSequenceKeypoint.new(0.7, 1.3, 0.5),
            NumberSequenceKeypoint.new(0.8, 1.35, 0.5),
            NumberSequenceKeypoint.new(0.9, 1.42, 0.5),
            NumberSequenceKeypoint.new(1, 1.5, 0.5),
            (NumberSequenceKeypoint.new(1, 1.5, 0.5)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.499, 0.119, 0.0687),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    })),
}