-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.GraveDigger
-- Decompile time: 1.34 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "Skulls",
        Acceleration = Vector3.new(0, 1, 0),
        Brightness = 1.8,
        Drag = 5,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 2,
        Texture = "rbxassetid://9666309147",
        ZOffset = -0.05,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 0, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 0, 0))),
        }),
        EmissionDirection = Enum.NormalId.Bottom,
        Lifetime = NumberRange.new(1),
        RotSpeed = NumberRange.new(10),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.2, 0.2),
            (NumberSequenceKeypoint.new(1, 0.1)),
        }),
        Speed = NumberRange.new(0.5, 1),
        SpreadAngle = Vector2.new(0, 45),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.3, 0),
            NumberSequenceKeypoint.new(0.5, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "Embers",
        Brightness = 3,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 4,
        Texture = "rbxassetid://11820939189",
        VelocityInheritance = 0.2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 0, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 0, 0))),
        }),
        Lifetime = NumberRange.new(2),
        Orientation = Enum.ParticleOrientation.VelocityParallel,
        RotSpeed = NumberRange.new(100),
        Rotation = NumberRange.new(-90, 50),
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.375), (NumberSequenceKeypoint.new(1, 0.1))}),
        Speed = NumberRange.new(0.5, 1),
        SpreadAngle = Vector2.new(360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.0773, 0.075, 0.075),
            NumberSequenceKeypoint.new(0.135, 0.9, 0.1),
            NumberSequenceKeypoint.new(0.224, 0.0875, 0.0875),
            NumberSequenceKeypoint.new(0.323, 0.881, 0.119),
            NumberSequenceKeypoint.new(0.419, 0.125, 0.125),
            NumberSequenceKeypoint.new(0.484, 0.856, 0.144),
            NumberSequenceKeypoint.new(0.567, 0.106, 0.106),
            NumberSequenceKeypoint.new(0.627, 0.894, 0.106),
            NumberSequenceKeypoint.new(0.709, 0.125, 0.125),
            NumberSequenceKeypoint.new(0.779, 0.906, 0.0938),
            NumberSequenceKeypoint.new(0.862, 0.0687, 0.0687),
            NumberSequenceKeypoint.new(0.906, 0.906, 0.0359),
            NumberSequenceKeypoint.new(0.958, 0.0625, 0.0168),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    })),
}