-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.GreenPoison
-- Decompile time: 3.22 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "DarkSmoke",
        Acceleration = Vector3.new(0, 1.0499999523162842, 0),
        FlipbookStartRandom = true,
        LightEmission = 0.2,
        LockedToPart = true,
        Rate = 25,
        Texture = "rbxassetid://16815653373",
        ZOffset = -1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(42, 74, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(21, 36, 0))),
        }),
        EmissionDirection = Enum.NormalId.Back,
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.8, 1.6),
        RotSpeed = NumberRange.new(-22, 22),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.524),
            NumberSequenceKeypoint.new(0.1, 0.665),
            NumberSequenceKeypoint.new(0.2, 0.752),
            NumberSequenceKeypoint.new(0.3, 0.82),
            NumberSequenceKeypoint.new(0.4, 0.875),
            NumberSequenceKeypoint.new(0.5, 0.921),
            NumberSequenceKeypoint.new(0.6, 0.959),
            NumberSequenceKeypoint.new(0.7, 0.991),
            NumberSequenceKeypoint.new(0.8, 1.02),
            NumberSequenceKeypoint.new(0.9, 1.04),
            NumberSequenceKeypoint.new(1, 1.05),
            (NumberSequenceKeypoint.new(1, 1.05)),
        }),
        Speed = NumberRange.new(0, 0.2),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.5, 0.244, 0.144),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Dots",
        Acceleration = Vector3.new(0, 6.869999885559082, 0),
        Brightness = 3,
        Drag = 6,
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 11,
        Texture = "rbxassetid://11800717040",
        ZOffset = 2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(221, 255, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 255, 42))),
        }),
        EmissionDirection = Enum.NormalId.Left,
        FlipbookFramerate = NumberRange.new(0),
        Lifetime = NumberRange.new(0.4, 1.5),
        RotSpeed = NumberRange.new(-321, 321),
        Rotation = NumberRange.new(-360, 360),
        ShapeInOut = Enum.ParticleEmitterShapeInOut.InAndOut,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.5, 0.389, 0.146),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(-1.64, 1.64),
        SpreadAngle = Vector2.new(25, 180),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.195, 0.188, 0.0483),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Fly",
        Acceleration = Vector3.new(0, 0.19200000166893005, 0),
        Brightness = 0,
        Drag = 2,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 4,
        Texture = "rbxassetid://14967557488",
        ZOffset = 1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(223, 223, 223)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(223, 223, 223))),
        }),
        FlipbookFramerate = NumberRange.new(16),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(1, 4),
        ShapeInOut = Enum.ParticleEmitterShapeInOut.Inward,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.5, 0.16, 0.096),
            NumberSequenceKeypoint.new(0.9, 0.08, 0.0352),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(0.64, 3.2),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.5, 0),
            NumberSequenceKeypoint.new(0.8, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "GlowStuff",
        Acceleration = Vector3.new(0, 1.0499999523162842, 0),
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 25,
        Texture = "rbxassetid://71424211461657",
        ZOffset = 0.1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(42, 74, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(21, 36, 0))),
        }),
        EmissionDirection = Enum.NormalId.Back,
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.8, 1.6),
        RotSpeed = NumberRange.new(-22, 22),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.524),
            NumberSequenceKeypoint.new(0.1, 0.665),
            NumberSequenceKeypoint.new(0.2, 0.752),
            NumberSequenceKeypoint.new(0.3, 0.82),
            NumberSequenceKeypoint.new(0.4, 0.875),
            NumberSequenceKeypoint.new(0.5, 0.921),
            NumberSequenceKeypoint.new(0.6, 0.959),
            NumberSequenceKeypoint.new(0.7, 0.991),
            NumberSequenceKeypoint.new(0.8, 1.02),
            NumberSequenceKeypoint.new(0.9, 1.04),
            NumberSequenceKeypoint.new(1, 1.05),
            (NumberSequenceKeypoint.new(1, 1.05)),
        }),
        Speed = NumberRange.new(0, 0.2),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.5, 0.244, 0.144),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "Goo",
        Acceleration = Vector3.new(0, -2.0199999809265137, 0),
        Brightness = 2,
        FlipbookStartRandom = true,
        LightEmission = 0.2,
        LockedToPart = true,
        Rate = 12,
        Texture = "rbxassetid://80114250436548",
        ZOffset = -1.1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(42, 74, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(21, 36, 0))),
        }),
        EmissionDirection = Enum.NormalId.Back,
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.4, 1.2),
        RotSpeed = NumberRange.new(-22, 22),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.425),
            NumberSequenceKeypoint.new(0.1, 0.539),
            NumberSequenceKeypoint.new(0.2, 0.609),
            NumberSequenceKeypoint.new(0.3, 0.664),
            NumberSequenceKeypoint.new(0.4, 0.709),
            NumberSequenceKeypoint.new(0.5, 0.746),
            NumberSequenceKeypoint.new(0.6, 0.777),
            NumberSequenceKeypoint.new(0.7, 0.803),
            NumberSequenceKeypoint.new(0.8, 0.824),
            NumberSequenceKeypoint.new(0.9, 0.839),
            NumberSequenceKeypoint.new(1, 0.849),
            (NumberSequenceKeypoint.new(1, 0.849)),
        }),
        Speed = NumberRange.new(0, 0.162),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.5, 0.244, 0.144),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    })),
}