-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.GreenSlime
-- Decompile time: 1.97 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "Drops",
        Acceleration = Vector3.new(0, -3.9600000381469727, 0),
        Brightness = 2,
        Drag = 1,
        LightEmission = 0.2,
        Rate = 5,
        Texture = "rbxassetid://70479317841342",
        ZOffset = 1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(200, 255, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 61, 2))),
        }),
        Lifetime = NumberRange.new(1),
        Orientation = Enum.ParticleOrientation.VelocityParallel,
        Rotation = NumberRange.new(-90),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.199, 0.441, 0.0498),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(-0.981, -0.196),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, 1), (NumberSequenceKeypoint.new(1, 1))}),
        Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.3), (NumberSequenceKeypoint.new(1, 0.3))}),
    }),
    Create("ParticleEmitter", {
        Name = "Goo",
        Acceleration = Vector3.new(0, -2.0199999809265137, 0),
        Brightness = 2,
        FlipbookStartRandom = true,
        LightEmission = 0.2,
        LockedToPart = true,
        Rate = 22,
        Texture = "rbxassetid://80114250436548",
        ZOffset = -1.1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(153, 255, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 36, 0))),
        }),
        EmissionDirection = Enum.NormalId.Back,
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.4, 1.2),
        RotSpeed = NumberRange.new(-22, 22),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.425),
            NumberSequenceKeypoint.new(0.1, 0.539),
            NumberSequenceKeypoint.new(0.2, 0.609),
            NumberSequenceKeypoint.new(0.3, 0.664),
            NumberSequenceKeypoint.new(0.4, 0.709),
            NumberSequenceKeypoint.new(0.5, 0.746),
            NumberSequenceKeypoint.new(0.6, 0.777),
            NumberSequenceKeypoint.new(0.7, 0.803),
            NumberSequenceKeypoint.new(0.8, 0.824),
            NumberSequenceKeypoint.new(0.9, 0.839),
            NumberSequenceKeypoint.new(1, 0.849),
            (NumberSequenceKeypoint.new(1, 0.849)),
        }),
        Speed = NumberRange.new(0, 0.162),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.5, 0.244, 0.144),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "GoopFlip",
        Brightness = 4,
        Drag = 2,
        LightEmission = 0.3,
        LockedToPart = true,
        Rate = 8,
        Texture = "rbxassetid://17135771189",
        ZOffset = -1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(153, 255, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(153, 255, 0))),
        }),
        EmissionDirection = Enum.NormalId.Bottom,
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
        Lifetime = NumberRange.new(0.5, 0.7),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.651, 0.326),
            NumberSequenceKeypoint.new(0.1, 0.955, 0.326),
            NumberSequenceKeypoint.new(0.2, 1.17, 0.326),
            NumberSequenceKeypoint.new(0.3, 1.32, 0.326),
            NumberSequenceKeypoint.new(0.4, 1.43, 0.326),
            NumberSequenceKeypoint.new(0.5, 1.5, 0.326),
            NumberSequenceKeypoint.new(0.6, 1.55, 0.326),
            NumberSequenceKeypoint.new(0.7, 1.59, 0.326),
            NumberSequenceKeypoint.new(0.8, 1.61, 0.326),
            NumberSequenceKeypoint.new(0.9, 1.62, 0.326),
            NumberSequenceKeypoint.new(1, 1.63, 0.326),
            (NumberSequenceKeypoint.new(1, 1.63, 0.326)),
        }),
        Speed = NumberRange.new(-3.26, 3.26),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0), (NumberSequenceKeypoint.new(1, 1))}),
    })),
}