-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.Molten
-- Decompile time: 1.63 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "Pixel Fire",
        Brightness = 5,
        LightEmission = 0.55,
        LightInfluence = 0.45,
        LockedToPart = true,
        Rate = 3,
        Texture = "rbxassetid://11844402871",
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 128, 44)),
            ColorSequenceKeypoint.new(0.567, Color3.fromRGB(255, 61, 27)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 74, 29))),
        }),
        FlipbookFramerate = NumberRange.new(32),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
        Lifetime = NumberRange.new(0.8),
        Orientation = Enum.ParticleOrientation.FacingCameraWorldUp,
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.35), (NumberSequenceKeypoint.new(1, 0.35))}),
        Speed = NumberRange.new(0.5),
        SpreadAngle = Vector2.new(15, 15),
    }),
    Create("ParticleEmitter", {
        Name = "Smoke",
        Acceleration = Vector3.new(0, 0.5, 0),
        Drag = 4,
        LockedToPart = true,
        Rate = 8,
        Texture = "rbxassetid://1084987899",
        ZOffset = -0.12,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(29, 29, 29)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(29, 29, 29))),
        }),
        Lifetime = NumberRange.new(1.5),
        Rotation = NumberRange.new(-180, 180),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.375, 0.15),
            (NumberSequenceKeypoint.new(1, 0.375, 0.225)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(10, 10),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.5, 0.744),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "Embers",
        LightEmission = 1,
        LightInfluence = 1,
        LockedToPart = true,
        Rate = 4,
        Texture = "rbxassetid://11820939189",
        VelocityInheritance = 0.2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 94, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 94, 0))),
        }),
        Lifetime = NumberRange.new(2),
        Orientation = Enum.ParticleOrientation.VelocityParallel,
        RotSpeed = NumberRange.new(100),
        Rotation = NumberRange.new(-90, 50),
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.375), (NumberSequenceKeypoint.new(1, 0.1))}),
        Speed = NumberRange.new(0.5, 1),
        SpreadAngle = Vector2.new(90, 90),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.0773, 0.075, 0.075),
            NumberSequenceKeypoint.new(0.135, 0.9, 0.1),
            NumberSequenceKeypoint.new(0.224, 0.0875, 0.0875),
            NumberSequenceKeypoint.new(0.323, 0.881, 0.119),
            NumberSequenceKeypoint.new(0.419, 0.125, 0.125),
            NumberSequenceKeypoint.new(0.484, 0.856, 0.144),
            NumberSequenceKeypoint.new(0.567, 0.106, 0.106),
            NumberSequenceKeypoint.new(0.627, 0.894, 0.106),
            NumberSequenceKeypoint.new(0.709, 0.125, 0.125),
            NumberSequenceKeypoint.new(0.779, 0.906, 0.0938),
            NumberSequenceKeypoint.new(0.862, 0.0687, 0.0687),
            NumberSequenceKeypoint.new(0.906, 0.906, 0.0359),
            NumberSequenceKeypoint.new(0.958, 0.0625, 0.0168),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    })),
}