-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.Northstar
-- Decompile time: 5.13 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
local Children = Create.Children
local v1 = {}
local v2 = Create("ParticleEmitter", {
    Name = "CommonSparkle",
    Acceleration = Vector3.new(0, -4, 0),
    Brightness = 12,
    Drag = 2,
    FlipbookStartRandom = true,
    LightEmission = 1,
    LockedToPart = true,
    Rate = 12,
    Texture = "rbxassetid://77117853056841",
    ZOffset = 0.5,
    Color = ColorSequence.new({
        ColorSequenceKeypoint.new(0, Color3.fromRGB(207, 0, 249)),
        ColorSequenceKeypoint.new(0.303, Color3.fromRGB(58, 0, 249)),
        (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 249, 17))),
    }),
    EmissionDirection = Enum.NormalId.Bottom,
    FlipbookFramerate = NumberRange.new(6),
    FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
    Lifetime = NumberRange.new(0.6, 1.5),
    RotSpeed = NumberRange.new(-123, 123),
    Rotation = NumberRange.new(-360, 360),
    Size = NumberSequence.new({
        NumberSequenceKeypoint.new(0, 0),
        NumberSequenceKeypoint.new(0.351, 0.113, 0.019),
        NumberSequenceKeypoint.new(0.498, 0.0258, 0.0134),
        NumberSequenceKeypoint.new(0.654, 0.114, 0.0224),
        NumberSequenceKeypoint.new(0.8, 0.0382, 0.013),
        NumberSequenceKeypoint.new(0.9, 0.0651, 0.00651),
        (NumberSequenceKeypoint.new(1, 0)),
    }),
    Speed = NumberRange.new(0.403, 1.21),
    Squash = NumberSequence.new({
        NumberSequenceKeypoint.new(0, 0.5),
        NumberSequenceKeypoint.new(0.1, 0.336),
        NumberSequenceKeypoint.new(0.2, 0.224),
        NumberSequenceKeypoint.new(0.3, 0.149),
        NumberSequenceKeypoint.new(0.4, 0.0981),
        NumberSequenceKeypoint.new(0.5, 0.0619),
        NumberSequenceKeypoint.new(0.6, 0.0364),
        NumberSequenceKeypoint.new(0.7, 0.019),
        NumberSequenceKeypoint.new(0.8, 0.00792),
        NumberSequenceKeypoint.new(0.9, 0.00186),
        NumberSequenceKeypoint.new(1, 0),
        (NumberSequenceKeypoint.new(1, 0)),
    }),
})
local v3 = Create("Attachment", {Name = "Attachment2", CFrame = CFrame.new(0, -1.47128391, 0)})
local v4 = {Name = "Attachment1", CFrame = CFrame.new(0, 1.13297033, 0)}
v4[Children] = {
    Create("ParticleEmitter", {
        Name = "Glow",
        Brightness = 3,
        LockedToPart = true,
        Rate = 2,
        Texture = "rbxassetid://97481598461081",
        ZOffset = -1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(21, 0, 75)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(21, 0, 75))),
        }),
        Lifetime = NumberRange.new(2),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 1.41), (NumberSequenceKeypoint.new(1, 1.41))}),
        Speed = NumberRange.new(0),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.499, 0.562),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "StarOutter",
        Brightness = 3,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 2,
        Texture = "rbxassetid://104142349724316",
        ZOffset = 2.11,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 255, 179)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 255, 179))),
        }),
        Lifetime = NumberRange.new(2),
        Rotation = NumberRange.new(90),
        Speed = NumberRange.new(0),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.501, 0.719),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "StarCore",
        Brightness = 12,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 2,
        Texture = "rbxassetid://91799157309882",
        ZOffset = 2.11,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(99, 182, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(99, 182, 255))),
        }),
        Lifetime = NumberRange.new(2),
        Rotation = NumberRange.new(90),
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.4), (NumberSequenceKeypoint.new(1, 0.4))}),
        Speed = NumberRange.new(0),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.499, 0.606),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Rays",
        LightEmission = 1,
        LockedToPart = true,
        Rate = 4,
        Texture = "rbxassetid://136543323132598",
        ZOffset = -1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 255, 136)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(115, 0, 255))),
        }),
        Lifetime = NumberRange.new(1),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.512, 0.256),
            NumberSequenceKeypoint.new(0.1, 0.609, 0.256),
            NumberSequenceKeypoint.new(0.2, 0.691, 0.256),
            NumberSequenceKeypoint.new(0.3, 0.762, 0.256),
            NumberSequenceKeypoint.new(0.4, 0.823, 0.256),
            NumberSequenceKeypoint.new(0.5, 0.878, 0.256),
            NumberSequenceKeypoint.new(0.6, 0.925, 0.256),
            NumberSequenceKeypoint.new(0.7, 0.964, 0.256),
            NumberSequenceKeypoint.new(0.8, 0.995, 0.256),
            NumberSequenceKeypoint.new(0.9, 1.02, 0.256),
            NumberSequenceKeypoint.new(1, 1.02, 0.256),
            (NumberSequenceKeypoint.new(1, 1.02, 0.256)),
        }),
        Speed = NumberRange.new(0),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.499, 0.119, 0.119),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("Beam", {
        Name = "BeamDarkSwirls",
        Brightness = 3,
        FaceCamera = true,
        Texture = "rbxassetid://86920120384352",
        TextureLength = 0.25,
        TextureSpeed = 0.5,
        Width1 = 0,
        ZOffset = -0.1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 255, 191)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 76, 255))),
        }),
    }),
    Create("Beam", {
        Name = "CoreSwirl1",
        Brightness = 12,
        FaceCamera = true,
        Texture = "rbxassetid://71382903252205",
        TextureLength = 0.25,
        TextureSpeed = 0.5,
        Width0 = 0.4,
        Width1 = 0,
        ZOffset = -0.04,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(140, 211, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(140, 211, 255))),
        }),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.4, 0),
            NumberSequenceKeypoint.new(0.573, 1),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "BaseSmoke",
        Acceleration = Vector3.new(0, -6.360000133514404, 0),
        Drag = 5,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 6,
        ShapePartial = 0.4,
        Texture = "rbxassetid://111406574946592",
        ZOffset = -2.5,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 13, 31)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(43, 0, 81))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        Lifetime = NumberRange.new(2),
        RotSpeed = NumberRange.new(-33, 33),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1.92),
            NumberSequenceKeypoint.new(0.1, 2.34),
            NumberSequenceKeypoint.new(0.2, 2.63),
            NumberSequenceKeypoint.new(0.3, 2.82),
            NumberSequenceKeypoint.new(0.4, 2.95),
            NumberSequenceKeypoint.new(0.5, 3.04),
            NumberSequenceKeypoint.new(0.6, 3.11),
            NumberSequenceKeypoint.new(0.7, 3.15),
            NumberSequenceKeypoint.new(0.8, 3.18),
            NumberSequenceKeypoint.new(0.9, 3.2),
            NumberSequenceKeypoint.new(1, 3.2),
            (NumberSequenceKeypoint.new(1, 3.2)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.531, 0.575),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("Beam", {
        Name = "CoreSwirl2",
        Brightness = 12,
        FaceCamera = true,
        Texture = "rbxassetid://105152138075688",
        TextureLength = 0.12,
        TextureSpeed = 0.3,
        Width0 = 0.2,
        Width1 = 2,
        ZOffset = -0.6,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(140, 211, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 255, 157))),
        }),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.0892, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    })),
}
v1[1] = v2
v1[2] = v3
v1[3] = Create("Attachment", v4)
return v1