-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.Snowflakes
-- Decompile time: 1.18 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "Smoke",
        Acceleration = Vector3.new(0, -0.10000000149011612, 0),
        Brightness = 0.5,
        LockedToPart = true,
        Texture = "rbxassetid://1084987899",
        ZOffset = -0.2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(199, 255, 243)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(199, 255, 243))),
        }),
        FlipbookFramerate = NumberRange.new(0.7),
        Lifetime = NumberRange.new(1, 2),
        RotSpeed = NumberRange.new(-20, 20),
        Rotation = NumberRange.new(-180, 180),
        Shape = Enum.ParticleEmitterShape.Sphere,
        ShapeInOut = Enum.ParticleEmitterShapeInOut.Inward,
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.3), (NumberSequenceKeypoint.new(1, 0.3))}),
        Speed = NumberRange.new(0),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.0511, 0.913),
            NumberSequenceKeypoint.new(0.146, 0.856),
            NumberSequenceKeypoint.new(0.401, 0.85),
            NumberSequenceKeypoint.new(0.522, 0.887),
            NumberSequenceKeypoint.new(0.66, 0.919),
            NumberSequenceKeypoint.new(0.833, 0.967),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Snowflakes",
        Acceleration = Vector3.new(0, -2, 0),
        Drag = 5,
        LightEmission = 0.5,
        LockedToPart = true,
        Rate = 10,
        ShapePartial = 0.35,
        Texture = "rbxassetid://10636027087",
        Lifetime = NumberRange.new(1, 2),
        RotSpeed = NumberRange.new(-90, 90),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Disc,
        ShapeInOut = Enum.ParticleEmitterShapeInOut.InAndOut,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.1),
            NumberSequenceKeypoint.new(0.103, 0.1, 0.1),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(0.1, 0.2),
        SpreadAngle = Vector2.new(45, 45),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.143, 0.0437),
            NumberSequenceKeypoint.new(0.47, 0.0562),
            NumberSequenceKeypoint.new(0.647, 0.219),
            NumberSequenceKeypoint.new(0.761, 0.706),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "Sparkles",
        LightEmission = 1,
        LockedToPart = true,
        Rate = 10,
        ShapePartial = 0.25,
        Texture = "rbxassetid://1084970835",
        ZOffset = 0.002,
        Lifetime = NumberRange.new(0.4, 0.6),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Disc,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.5, 0.09, 0.03),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(0),
    })),
}