-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.Spirits
-- Decompile time: 3.23 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "BgSmoke",
        Drag = 2,
        FlipbookStartRandom = true,
        LightEmission = -2,
        LockedToPart = true,
        Rate = 18,
        Texture = "rbxassetid://80397661829393",
        WindAffectsDrag = true,
        ZOffset = -1.1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 7, 16)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 7, 16))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.6, 1.2),
        RotSpeed = NumberRange.new(-22, 22),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.656),
            NumberSequenceKeypoint.new(0.1, 0.707),
            NumberSequenceKeypoint.new(0.2, 0.756),
            NumberSequenceKeypoint.new(0.3, 0.805),
            NumberSequenceKeypoint.new(0.4, 0.856),
            NumberSequenceKeypoint.new(0.5, 0.911),
            NumberSequenceKeypoint.new(0.6, 0.97),
            NumberSequenceKeypoint.new(0.7, 1.04),
            NumberSequenceKeypoint.new(0.8, 1.11),
            NumberSequenceKeypoint.new(0.9, 1.2),
            NumberSequenceKeypoint.new(1, 1.31),
            (NumberSequenceKeypoint.new(1, 1.31)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(11, 1),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.0349, 0.45),
            NumberSequenceKeypoint.new(0.0624, 0.144),
            NumberSequenceKeypoint.new(0.111, 0.0437),
            NumberSequenceKeypoint.new(0.2, 0.0706),
            NumberSequenceKeypoint.new(0.3, 0.169),
            NumberSequenceKeypoint.new(0.4, 0.314),
            NumberSequenceKeypoint.new(0.5, 0.492),
            NumberSequenceKeypoint.new(0.6, 0.672),
            NumberSequenceKeypoint.new(0.7, 0.822),
            NumberSequenceKeypoint.new(0.8, 0.926),
            NumberSequenceKeypoint.new(0.9, 0.983),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "FireSwipeBright",
        Brightness = 3,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 4,
        Texture = "rbxassetid://109355234635405",
        ZOffset = 0.113,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(125, 162, 240)),
            ColorSequenceKeypoint.new(0.19, Color3.fromRGB(0, 242, 255)),
            ColorSequenceKeypoint.new(0.731, Color3.fromRGB(16, 26, 58)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(12, 15, 46))),
        }),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
        Lifetime = NumberRange.new(1.6, 2.4),
        Orientation = Enum.ParticleOrientation.VelocityPerpendicular,
        RotSpeed = NumberRange.new(11, 22),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1.23),
            NumberSequenceKeypoint.new(0.1, 1.65),
            NumberSequenceKeypoint.new(0.2, 1.89),
            NumberSequenceKeypoint.new(0.3, 2.06),
            NumberSequenceKeypoint.new(0.4, 2.18),
            NumberSequenceKeypoint.new(0.5, 2.28),
            NumberSequenceKeypoint.new(0.6, 2.35),
            NumberSequenceKeypoint.new(0.7, 2.4),
            NumberSequenceKeypoint.new(0.8, 2.44),
            NumberSequenceKeypoint.new(0.9, 2.46),
            NumberSequenceKeypoint.new(1, 2.47),
            (NumberSequenceKeypoint.new(1, 2.47)),
        }),
        Speed = NumberRange.new(0.000508),
        SpreadAngle = Vector2.new(-360, 360),
    }),
    Create("ParticleEmitter", {
        Name = "FrontSwirl",
        Acceleration = Vector3.new(0, 0.3869999945163727, 0),
        Brightness = 3,
        Drag = 6,
        FlipbookStartRandom = true,
        LightEmission = 0.1,
        LockedToPart = true,
        Rate = 12,
        Texture = "rbxassetid://100913017683060",
        WindAffectsDrag = true,
        ZOffset = -1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 211, 244)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 211, 244))),
        }),
        EmissionDirection = Enum.NormalId.Front,
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        Lifetime = NumberRange.new(0.6, 1.5),
        RotSpeed = NumberRange.new(-6, 6),
        Rotation = NumberRange.new(-360, 360),
        Speed = NumberRange.new(2.91, 4.72),
        SpreadAngle = Vector2.new(22, 180),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.509, 0.678, 0.114),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "GhostWisps",
        Acceleration = Vector3.new(0, 1.0199999809265137, 0),
        Brightness = 128,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 2,
        Texture = "rbxassetid://139368910832865",
        VelocityInheritance = 1,
        ZOffset = 1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(2, 234, 255)),
            ColorSequenceKeypoint.new(0.19, Color3.fromRGB(0, 203, 244)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 15, 83))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
        Lifetime = NumberRange.new(1, 2),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1.36, 0.34),
            (NumberSequenceKeypoint.new(1, 1.36, 0.34)),
        }),
        Speed = NumberRange.new(5.42e-05),
        SpreadAngle = Vector2.new(-360, 360),
    }),
    (Create("ParticleEmitter", {
        Name = "RotDots",
        Acceleration = Vector3.new(0, 2.809999942779541, 0),
        Brightness = 6,
        Drag = 7,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 12,
        Texture = "rbxassetid://11800717040",
        ZOffset = 2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 255, 234)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 255, 234))),
        }),
        Lifetime = NumberRange.new(0.4, 2.5),
        RotSpeed = NumberRange.new(-66, 66),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.102, 0.404, 0.214),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(4.11, 7.54),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, -2, 1),
            NumberSequenceKeypoint.new(0.1, -1.41, 1),
            NumberSequenceKeypoint.new(0.2, -1.01, 1),
            NumberSequenceKeypoint.new(0.3, -0.715, 1),
            NumberSequenceKeypoint.new(0.4, -0.492, 1),
            NumberSequenceKeypoint.new(0.5, -0.323, 1),
            NumberSequenceKeypoint.new(0.6, -0.196, 1),
            NumberSequenceKeypoint.new(0.7, -0.105, 1),
            NumberSequenceKeypoint.new(0.8, -0.0448, 1),
            NumberSequenceKeypoint.new(0.9, -0.0108, 1),
            NumberSequenceKeypoint.new(1, 0, 1),
            (NumberSequenceKeypoint.new(1, 0, 1)),
        }),
    })),
}