-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.StarryNight
-- Decompile time: 2.28 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "BackgroundSmokeGlowing",
        Acceleration = Vector3.new(0, -0.1340000033378601, 0),
        Drag = 3,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 12,
        Texture = "rbxassetid://133355140520916",
        ZOffset = -2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(112, 0, 67)),
            ColorSequenceKeypoint.new(0.567, Color3.fromRGB(19, 0, 56)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(1, 0, 21))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(2, 4),
        RotSpeed = NumberRange.new(-11, 11),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Sphere,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.268),
            NumberSequenceKeypoint.new(0.1, 0.471),
            NumberSequenceKeypoint.new(0.2, 0.594),
            NumberSequenceKeypoint.new(0.3, 0.686),
            NumberSequenceKeypoint.new(0.4, 0.758),
            NumberSequenceKeypoint.new(0.5, 0.815),
            NumberSequenceKeypoint.new(0.6, 0.86),
            NumberSequenceKeypoint.new(0.7, 0.895),
            NumberSequenceKeypoint.new(0.8, 0.919),
            NumberSequenceKeypoint.new(0.9, 0.934),
            NumberSequenceKeypoint.new(1, 0.94),
            (NumberSequenceKeypoint.new(1, 0.94)),
        }),
        Speed = NumberRange.new(0, 0.134),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.499, 0.412, 0.156),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "TinyDots",
        Acceleration = Vector3.new(0, -2.880000114440918, 0),
        Brightness = 4,
        Drag = 6,
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 6,
        Texture = "rbxassetid://11800717040",
        ZOffset = 2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 81, 255)),
            ColorSequenceKeypoint.new(0.467, Color3.fromRGB(136, 0, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(151, 191, 255))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        Lifetime = NumberRange.new(1, 6),
        RotSpeed = NumberRange.new(-222, 222),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.201, 0.308, 0.126),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(0, 1.05),
        SpreadAngle = Vector2.new(111, 111),
    }),
    Create("ParticleEmitter", {
        Name = "Stars",
        Brightness = 4,
        Drag = 6,
        LockedToPart = true,
        Rate = 14,
        Texture = "rbxassetid://100235720010709",
        ZOffset = 0.1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(88, 191, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(88, 191, 255))),
        }),
        FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
        Lifetime = NumberRange.new(2, 3),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.3, 0),
            NumberSequenceKeypoint.new(0.4, 0.0555, 0.0277),
            NumberSequenceKeypoint.new(0.5, 0),
            NumberSequenceKeypoint.new(0.7, 0),
            NumberSequenceKeypoint.new(0.8, 0.0277, 0.0166),
            NumberSequenceKeypoint.new(0.9, 0),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(0.333, 0.888),
        SpreadAngle = Vector2.new(-360, 360),
    }),
    (Create("ParticleEmitter", {
        Name = "TinySparkles(44)",
        Acceleration = Vector3.new(0, -6, 0),
        Brightness = 4,
        Drag = 5,
        FlipbookStartRandom = true,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 6,
        Texture = "rbxassetid://128565162449108",
        ZOffset = 2,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 179, 0)),
            ColorSequenceKeypoint.new(0.514, Color3.fromRGB(255, 168, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 81, 0))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(1, 4),
        RotSpeed = NumberRange.new(-234, 234),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.206, 0),
            NumberSequenceKeypoint.new(0.401, 0),
            NumberSequenceKeypoint.new(0.799, 0.629, 0.397),
            NumberSequenceKeypoint.new(0.9, 0.5, 0.4),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(-5, 11),
        SpreadAngle = Vector2.new(45, 45),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, 0, 0.2), (NumberSequenceKeypoint.new(1, 0))}),
    })),
}