-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.The32
-- Decompile time: 2.87 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("Beam", {
        Name = "Beam",
        FaceCamera = true,
        LightEmission = 1,
        Texture = "rbxassetid://119895054864943",
        TextureLength = 0.5,
        TextureSpeed = 0.2,
        Width0 = 1.3,
        Width1 = 1.3,
        ZOffset = -0.5,
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.503, 0.45),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("Attachment", {Name = "BeamEnd", CFrame = CFrame.new(-3, 0, 0)}),
    Create("Attachment", {Name = "BeamStart", CFrame = CFrame.new(3, 0, 0)}),
    Create("ParticleEmitter", {
        Name = "BigGlitch",
        Brightness = 2,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 12,
        Texture = "rbxassetid://116292496855722",
        ZOffset = -0.9,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(216, 186, 14)),
            ColorSequenceKeypoint.new(0.247, Color3.fromRGB(216, 186, 14)),
            ColorSequenceKeypoint.new(0.253, Color3.fromRGB(72, 0, 216)),
            ColorSequenceKeypoint.new(0.59, Color3.fromRGB(216, 186, 14)),
            ColorSequenceKeypoint.new(0.592, Color3.fromRGB(72, 0, 216)),
            ColorSequenceKeypoint.new(0.869, Color3.fromRGB(216, 186, 14)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(216, 186, 14))),
        }),
        FlipbookFramerate = NumberRange.new(14),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.2, 0.6),
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.561), (NumberSequenceKeypoint.new(1, 0.561))}),
        Speed = NumberRange.new(0.000374),
    }),
    Create("ParticleEmitter", {
        Name = "GlitchBlack",
        Brightness = 0,
        FlipbookStartRandom = true,
        LockedToPart = true,
        Rate = 12,
        Texture = "rbxassetid://126548307611360",
        ZOffset = -1,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 0, 166)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 0, 166))),
        }),
        FlipbookFramerate = NumberRange.new(14),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(1, 2),
        Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.56), (NumberSequenceKeypoint.new(1, 0.56))}),
        Speed = NumberRange.new(-0.2, 0.2),
        SpreadAngle = Vector2.new(-360, 360),
    }),
    (Create("ParticleEmitter", {
        Name = "Warning",
        Brightness = 2,
        LockedToPart = true,
        Rate = 6,
        Texture = "rbxassetid://127644259607218",
        ZOffset = -0.87,
        FlipbookFramerate = NumberRange.new(12),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(0.3, 0.6),
        Rotation = NumberRange.new(-3, 3),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.24),
            NumberSequenceKeypoint.new(0.1, 0.363),
            NumberSequenceKeypoint.new(0.2, 0.402),
            NumberSequenceKeypoint.new(0.3, 0.427),
            NumberSequenceKeypoint.new(0.4, 0.444),
            NumberSequenceKeypoint.new(0.421, 0.462),
            NumberSequenceKeypoint.new(0.451, 0.592),
            NumberSequenceKeypoint.new(0.461, 0.355),
            NumberSequenceKeypoint.new(0.477, 0.462),
            NumberSequenceKeypoint.new(0.5, 0.457),
            NumberSequenceKeypoint.new(0.585, 0.462),
            NumberSequenceKeypoint.new(0.588, 0.899),
            NumberSequenceKeypoint.new(0.6, 0.466),
            NumberSequenceKeypoint.new(0.687, 0.497),
            NumberSequenceKeypoint.new(0.695, 0.237),
            NumberSequenceKeypoint.new(0.7, 0.473),
            NumberSequenceKeypoint.new(0.8, 0.477),
            NumberSequenceKeypoint.new(0.9, 0.479),
            NumberSequenceKeypoint.new(1, 0.48),
            (NumberSequenceKeypoint.new(1, 0.48)),
        }),
        Speed = NumberRange.new(0),
        Squash = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.227, -0.0173),
            NumberSequenceKeypoint.new(0.259, -0.971),
            NumberSequenceKeypoint.new(0.276, 0.607),
            NumberSequenceKeypoint.new(0.303, 0.0173),
            NumberSequenceKeypoint.new(0.491, 0),
            NumberSequenceKeypoint.new(0.515, -0.382),
            NumberSequenceKeypoint.new(0.529, 0.572),
            NumberSequenceKeypoint.new(0.557, 0.0347),
            NumberSequenceKeypoint.new(0.84, 0.0173),
            NumberSequenceKeypoint.new(0.857, -0.382),
            NumberSequenceKeypoint.new(0.895, 0.277),
            NumberSequenceKeypoint.new(0.911, -0.0173),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.117, 0),
            NumberSequenceKeypoint.new(0.143, 1),
            NumberSequenceKeypoint.new(0.184, 0),
            NumberSequenceKeypoint.new(0.341, 0),
            NumberSequenceKeypoint.new(0.406, 1),
            NumberSequenceKeypoint.new(0.434, 0),
            NumberSequenceKeypoint.new(0.516, 0),
            NumberSequenceKeypoint.new(0.545, 1),
            NumberSequenceKeypoint.new(0.587, 0),
            NumberSequenceKeypoint.new(0.704, 0),
            NumberSequenceKeypoint.new(0.721, 1),
            NumberSequenceKeypoint.new(0.776, 0),
            NumberSequenceKeypoint.new(0.879, 0),
            NumberSequenceKeypoint.new(0.913, 1),
            NumberSequenceKeypoint.new(0.941, 0),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
    })),
}