-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.Tropical
-- Decompile time: 2.62 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
local Children = Create.Children
return {
    Create("ParticleEmitter", {
        Name = "RotPalm",
        Brightness = 2.5,
        FlipbookStartRandom = true,
        LightEmission = 0.1,
        LockedToPart = true,
        Rate = 5,
        Texture = "rbxassetid://87296587876181",
        ZOffset = -0.5,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(110, 168, 34)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(118, 168, 1))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        Lifetime = NumberRange.new(2, 4),
        RotSpeed = NumberRange.new(-6, 6),
        Rotation = NumberRange.new(-66, 66),
        Shape = Enum.ParticleEmitterShape.Sphere,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1.29, 0.536),
            (NumberSequenceKeypoint.new(1, 1.5, 0.536)),
        }),
        Speed = NumberRange.new(-0.0643, 0.0643),
        SpreadAngle = Vector2.new(-66, 66),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.137, 0.131, 0.1),
            NumberSequenceKeypoint.new(0.799, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Monstera",
        FlipbookStartRandom = true,
        LightEmission = 0.1,
        LockedToPart = true,
        Rate = 5,
        Texture = "rbxassetid://92964707338857",
        ZOffset = -0.55,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(110, 168, 34)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(118, 168, 1))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(2, 4),
        RotSpeed = NumberRange.new(-6, 6),
        Rotation = NumberRange.new(-99, 99),
        Shape = Enum.ParticleEmitterShape.Sphere,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.299, 1.44, 0.648),
            (NumberSequenceKeypoint.new(1, 1.82, 0.648)),
        }),
        Speed = NumberRange.new(-0.0778, 0.0778),
        SpreadAngle = Vector2.new(-66, 66),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.137, 0.131, 0.1),
            NumberSequenceKeypoint.new(0.799, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    Create("ParticleEmitter", {
        Name = "Leaves",
        Acceleration = Vector3.new(0, -1.309999942779541, 0.21899999678134918),
        Drag = 2,
        FlipbookStartRandom = true,
        LightEmission = 0.2,
        LockedToPart = true,
        Rate = 9,
        Texture = "rbxassetid://90602941072847",
        ZOffset = -1.12,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
            ColorSequenceKeypoint.new(0.268, Color3.fromRGB(217, 250, 179)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(67, 207, 57))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(1, 3),
        RotSpeed = NumberRange.new(-111, 111),
        Rotation = NumberRange.new(-360, 360),
        Shape = Enum.ParticleEmitterShape.Sphere,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.046, 0.254, 0.0693),
            (NumberSequenceKeypoint.new(1, 0)),
        }),
        Speed = NumberRange.new(1.2, 2.41),
        SpreadAngle = Vector2.new(88, 88),
    }),
    Create("ParticleEmitter", {
        Name = "Foiliage",
        Brightness = 2.5,
        FlipbookStartRandom = true,
        LightEmission = 0.1,
        LockedToPart = true,
        Rate = 5,
        Texture = "rbxassetid://133356960069574",
        ZOffset = -0.45,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(110, 168, 34)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(110, 168, 34))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(2, 4),
        RotSpeed = NumberRange.new(-12, 12),
        Rotation = NumberRange.new(-66, 66),
        Shape = Enum.ParticleEmitterShape.Sphere,
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.878, 0.366),
            (NumberSequenceKeypoint.new(1, 1.02, 0.366)),
        }),
        Speed = NumberRange.new(-0.0439, 0.0439),
        SpreadAngle = Vector2.new(-66, 66),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.137, 0.131, 0.1),
            NumberSequenceKeypoint.new(0.799, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    }),
    (Create("ParticleEmitter", {
        Name = "Flowers",
        Acceleration = Vector3.new(0, 0, 0.01209999993443489),
        Brightness = 2.2,
        FlipbookStartRandom = true,
        LightEmission = 0.1,
        LockedToPart = true,
        Rate = 3,
        Texture = "rbxassetid://74139089022134",
        ZOffset = -0.43,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(239, 230, 197)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(239, 230, 197))),
        }),
        FlipbookFramerate = NumberRange.new(0),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid2x2,
        Lifetime = NumberRange.new(2, 4),
        RotSpeed = NumberRange.new(-33, 33),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.0999, 0.275, 0.131),
            (NumberSequenceKeypoint.new(1, 0.211, 0.0504)),
        }),
        Speed = NumberRange.new(-0.0302, 0.0302),
        SpreadAngle = Vector2.new(-360, 360),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.137, 0.131, 0.1),
            NumberSequenceKeypoint.new(0.799, 0),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    })),
}