-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.UnholyFire
-- Decompile time: 3.84 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
local v1 = {}
local v2 = {Name = "Attachment"}
v2[Create.Children] = {
    Create("ParticleEmitter", {
        Name = "RadialBurstDark",
        Brightness = 3,
        LockedToPart = true,
        Rate = 2,
        Texture = "rbxassetid://135637135133107",
        ZOffset = -0.5,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(132, 255, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(132, 255, 0))),
        }),
        FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
        FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
        Lifetime = NumberRange.new(2.2),
        RotSpeed = NumberRange.new(0, 22),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.62),
            NumberSequenceKeypoint.new(0.1, 1.05),
            NumberSequenceKeypoint.new(0.2, 1.31),
            NumberSequenceKeypoint.new(0.3, 1.53),
            NumberSequenceKeypoint.new(0.4, 1.71),
            NumberSequenceKeypoint.new(0.5, 1.86),
            NumberSequenceKeypoint.new(0.6, 1.99),
            NumberSequenceKeypoint.new(0.7, 2.08),
            NumberSequenceKeypoint.new(0.8, 2.16),
            NumberSequenceKeypoint.new(0.9, 2.2),
            NumberSequenceKeypoint.new(1, 2.22),
            (NumberSequenceKeypoint.new(1, 2.22)),
        }),
        Speed = NumberRange.new(0),
    }),
    (Create("ParticleEmitter", {
        Name = "ParticleEmitter",
        Brightness = 2,
        LightEmission = 1,
        LockedToPart = true,
        Rate = 5,
        Texture = "rbxassetid://74789878804652",
        ZOffset = 0.5,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(60, 255, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(60, 255, 0))),
        }),
        Lifetime = NumberRange.new(1),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0),
            NumberSequenceKeypoint.new(0.1, 0.58),
            NumberSequenceKeypoint.new(0.2, 0.928),
            NumberSequenceKeypoint.new(0.3, 1.19),
            NumberSequenceKeypoint.new(0.4, 1.39),
            NumberSequenceKeypoint.new(0.5, 1.55),
            NumberSequenceKeypoint.new(0.6, 1.68),
            NumberSequenceKeypoint.new(0.7, 1.78),
            NumberSequenceKeypoint.new(0.8, 1.85),
            NumberSequenceKeypoint.new(0.9, 1.9),
            NumberSequenceKeypoint.new(1, 1.91),
            (NumberSequenceKeypoint.new(1, 1.91)),
        }),
        Speed = NumberRange.new(0),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, -1), (NumberSequenceKeypoint.new(1, -1))}),
        Transparency = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 1),
            NumberSequenceKeypoint.new(0.499, 0.758, 0.152),
            (NumberSequenceKeypoint.new(1, 1)),
        }),
    })),
}
local v3 = Create("Attachment", v2)
local v4 = Create("ParticleEmitter", {
    Name = "FrontFlipbook",
    Acceleration = Vector3.new(0, 12, 0),
    Brightness = 3,
    Drag = 6,
    LightEmission = 0.1,
    LockedToPart = true,
    Rate = 22,
    Texture = "rbxassetid://100414309979862",
    ZOffset = -1,
    Color = ColorSequence.new({
        ColorSequenceKeypoint.new(0, Color3.fromRGB(136, 255, 0)),
        (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 255, 38))),
    }),
    FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
    FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
    Lifetime = NumberRange.new(0.4, 0.8),
    RotSpeed = NumberRange.new(-111, 111),
    Rotation = NumberRange.new(-360, 360),
    ShapeStyle = Enum.ParticleEmitterShapeStyle.Surface,
    Size = NumberSequence.new({
        NumberSequenceKeypoint.new(0, 0.161),
        NumberSequenceKeypoint.new(0.1, 0.373),
        NumberSequenceKeypoint.new(0.2, 0.567),
        NumberSequenceKeypoint.new(0.3, 0.73),
        NumberSequenceKeypoint.new(0.4, 0.854),
        NumberSequenceKeypoint.new(0.5, 0.941),
        NumberSequenceKeypoint.new(0.6, 0.999),
        NumberSequenceKeypoint.new(0.7, 1.04),
        NumberSequenceKeypoint.new(0.8, 1.06),
        NumberSequenceKeypoint.new(0.9, 1.07),
        NumberSequenceKeypoint.new(1, 1.07),
        (NumberSequenceKeypoint.new(1, 1.07)),
    }),
    Speed = NumberRange.new(-2),
})
v2 = Create("ParticleEmitter", {
    Name = "FrontFlipbook",
    Acceleration = Vector3.new(0, 12, 0),
    Drag = 6,
    LockedToPart = true,
    Rate = 22,
    Texture = "rbxassetid://100414309979862",
    ZOffset = -1.2,
    Color = ColorSequence.new({
        ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 27, 19)),
        (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 27, 19))),
    }),
    FlipbookLayout = Enum.ParticleFlipbookLayout.Grid4x4,
    FlipbookMode = Enum.ParticleFlipbookMode.OneShot,
    Lifetime = NumberRange.new(0.4, 0.8),
    RotSpeed = NumberRange.new(-111, 111),
    Rotation = NumberRange.new(-360, 360),
    ShapeStyle = Enum.ParticleEmitterShapeStyle.Surface,
    Size = NumberSequence.new({
        NumberSequenceKeypoint.new(0, 0.161),
        NumberSequenceKeypoint.new(0.1, 0.373),
        NumberSequenceKeypoint.new(0.2, 0.567),
        NumberSequenceKeypoint.new(0.3, 0.73),
        NumberSequenceKeypoint.new(0.4, 0.854),
        NumberSequenceKeypoint.new(0.5, 0.941),
        NumberSequenceKeypoint.new(0.6, 0.999),
        NumberSequenceKeypoint.new(0.7, 1.04),
        NumberSequenceKeypoint.new(0.8, 1.06),
        NumberSequenceKeypoint.new(0.9, 1.07),
        NumberSequenceKeypoint.new(1, 1.07),
        (NumberSequenceKeypoint.new(1, 1.07)),
    }),
    Speed = NumberRange.new(-2),
})
local v5 = {
    Name = "NormalDots",
    Acceleration = Vector3.new(0, 0.1340000033378601, 0),
    Brightness = 4,
    Drag = 6,
    FlipbookStartRandom = true,
    LightEmission = 1,
    LockedToPart = true,
    Rate = 33,
    ShapePartial = 0,
    Texture = "rbxassetid://83191224553551",
    ZOffset = 1,
    Color = ColorSequence.new({
        ColorSequenceKeypoint.new(0, Color3.fromRGB(38, 255, 0)),
        (ColorSequenceKeypoint.new(1, Color3.fromRGB(38, 255, 0))),
    }),
    FlipbookFramerate = NumberRange.new(0),
    Lifetime = NumberRange.new(0.3, 1),
    Orientation = Enum.ParticleOrientation.VelocityParallel,
    Shape = Enum.ParticleEmitterShape.Disc,
    Size = NumberSequence.new({
        NumberSequenceKeypoint.new(0, 0.331, 0.11),
        NumberSequenceKeypoint.new(0.1, 0.221, 0.11),
        NumberSequenceKeypoint.new(0.2, 0.158, 0.11),
        NumberSequenceKeypoint.new(0.3, 0.114, 0.11),
        NumberSequenceKeypoint.new(0.4, 0.0798, 0.0798),
        NumberSequenceKeypoint.new(0.5, 0.0536, 0.0536),
        NumberSequenceKeypoint.new(0.6, 0.0334, 0.0334),
        NumberSequenceKeypoint.new(0.7, 0.0184, 0.0184),
        NumberSequenceKeypoint.new(0.8, 0.00807, 0.00807),
        NumberSequenceKeypoint.new(0.9, 0.002, 0.002),
        NumberSequenceKeypoint.new(1, 4.89e-17, 4.89e-17),
        (NumberSequenceKeypoint.new(1, 0)),
    }),
    Speed = NumberRange.new(2.42, 12.1),
    Squash = NumberSequence.new({
        NumberSequenceKeypoint.new(0, -1, 0.2),
        NumberSequenceKeypoint.new(0.1, -0.668, 0.2),
        NumberSequenceKeypoint.new(0.2, -0.479, 0.2),
        NumberSequenceKeypoint.new(0.3, -0.344, 0.2),
        NumberSequenceKeypoint.new(0.4, -0.242, 0.2),
        NumberSequenceKeypoint.new(0.5, -0.162, 0.2),
        NumberSequenceKeypoint.new(0.6, -0.101, 0.2),
        NumberSequenceKeypoint.new(0.7, -0.0557, 0.2),
        NumberSequenceKeypoint.new(0.8, -0.0244, 0.2),
        NumberSequenceKeypoint.new(0.9, -0.00604, 0.2),
        NumberSequenceKeypoint.new(1, -1.11e-16, 0.2),
        (NumberSequenceKeypoint.new(1, 0, 0.2)),
    }),
    Transparency = NumberSequence.new({
        NumberSequenceKeypoint.new(0, 1),
        NumberSequenceKeypoint.new(0.0908, 0.412),
        (NumberSequenceKeypoint.new(1, 1)),
    }),
}
v1[1] = v3
v1[2] = v4
v1[3] = v2
v1[4] = Create("ParticleEmitter", v5)
return v1