-- Script path: ReplicatedStorage.Shared.UI.Components.RichText.Particles.Effects.XmasLights
-- Decompile time: 2.82 ms

local Create = require(game:GetService("ReplicatedStorage").Shared.Modules.Standalone.Create)
return {
    Create("ParticleEmitter", {
        Name = "Red",
        LightEmission = 1,
        LightInfluence = 1,
        LockedToPart = true,
        Rate = 10,
        Texture = "rbxassetid://9462952014",
        ZOffset = -0.4,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 0, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 0, 0))),
        }),
        Lifetime = NumberRange.new(0.3),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.05, 0.05),
            (NumberSequenceKeypoint.new(1, 0.05, 0.05)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(90, 90),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.2), (NumberSequenceKeypoint.new(1, 0.2))}),
    }),
    Create("ParticleEmitter", {
        Name = "Green",
        LightEmission = 1,
        LightInfluence = 1,
        LockedToPart = true,
        Rate = 10,
        Texture = "rbxassetid://9462952014",
        ZOffset = -0.4,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 128, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 128, 0))),
        }),
        Lifetime = NumberRange.new(0.3),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.05, 0.05),
            (NumberSequenceKeypoint.new(1, 0.05, 0.05)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(90, 90),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.2), (NumberSequenceKeypoint.new(1, 0.2))}),
    }),
    Create("ParticleEmitter", {
        Name = "Blue",
        LightEmission = 1,
        LightInfluence = 1,
        LockedToPart = true,
        Rate = 10,
        Texture = "rbxassetid://9462952014",
        ZOffset = -0.4,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 0, 255)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 255))),
        }),
        Lifetime = NumberRange.new(0.3),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.05, 0.05),
            (NumberSequenceKeypoint.new(1, 0.05, 0.05)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(90, 90),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.2), (NumberSequenceKeypoint.new(1, 0.2))}),
    }),
    Create("ParticleEmitter", {
        Name = "Yellow",
        LightEmission = 1,
        LightInfluence = 1,
        LockedToPart = true,
        Rate = 10,
        Texture = "rbxassetid://9462952014",
        ZOffset = -0.4,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 255, 0))),
        }),
        Lifetime = NumberRange.new(0.3),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.05, 0.05),
            (NumberSequenceKeypoint.new(1, 0.05, 0.05)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(90, 90),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.2), (NumberSequenceKeypoint.new(1, 0.2))}),
    }),
    Create("ParticleEmitter", {
        Name = "Orange",
        LightEmission = 1,
        LightInfluence = 1,
        LockedToPart = true,
        Rate = 10,
        Texture = "rbxassetid://9462952014",
        ZOffset = -0.4,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 165, 0)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 165, 0))),
        }),
        Lifetime = NumberRange.new(0.3),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.05, 0.05),
            (NumberSequenceKeypoint.new(1, 0.05, 0.05)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(90, 90),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.2), (NumberSequenceKeypoint.new(1, 0.2))}),
    }),
    Create("ParticleEmitter", {
        Name = "Purple",
        LightEmission = 1,
        LightInfluence = 1,
        LockedToPart = true,
        Rate = 10,
        Texture = "rbxassetid://9462952014",
        ZOffset = -0.4,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(128, 0, 128)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(128, 0, 128))),
        }),
        Lifetime = NumberRange.new(0.3),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.05, 0.05),
            (NumberSequenceKeypoint.new(1, 0.05, 0.05)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(90, 90),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.2), (NumberSequenceKeypoint.new(1, 0.2))}),
    }),
    Create("ParticleEmitter", {
        Name = "Pink",
        LightEmission = 1,
        LightInfluence = 1,
        LockedToPart = true,
        Rate = 10,
        Texture = "rbxassetid://9462952014",
        ZOffset = -0.4,
        Color = ColorSequence.new({
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 192, 203)),
            (ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 192, 203))),
        }),
        Lifetime = NumberRange.new(0.3),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.05, 0.05),
            (NumberSequenceKeypoint.new(1, 0.05, 0.05)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(90, 90),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.2), (NumberSequenceKeypoint.new(1, 0.2))}),
    }),
    (Create("ParticleEmitter", {
        Name = "White",
        LightEmission = 1,
        LightInfluence = 1,
        LockedToPart = true,
        Rate = 10,
        Texture = "rbxassetid://9462952014",
        ZOffset = -0.4,
        Lifetime = NumberRange.new(0.3),
        Rotation = NumberRange.new(-360, 360),
        Size = NumberSequence.new({
            NumberSequenceKeypoint.new(0, 0.05, 0.05),
            (NumberSequenceKeypoint.new(1, 0.05, 0.05)),
        }),
        Speed = NumberRange.new(0),
        SpreadAngle = Vector2.new(90, 90),
        Squash = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.2), (NumberSequenceKeypoint.new(1, 0.2))}),
    })),
}