-- Script path: ReplicatedStorage.Client.Controllers.Shared.SettingsController.Modules.Game.Properties
-- Decompile time: 5.41 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Enum_2 = require(ReplicatedStorage.Shared.Modules.Enum)
return {
    SettingOrder = {
        "Towers",
        "Music",
        "Emotes",
        "Ambience",
        "Communication",
        "DJ",
        "Stickers",
        "Cutscene",
        "Yapping",
        "Skills Enabled",
        "Auto Skip",
        "Health Bar Color",
        "Dialog",
        "Hide suggestions",
        "Hide Tower Rings",
        "Show Nametags",
        "Show Flair",
        "Show Tower Pets",
        "Show Currency Drops",
        "Show Shadows",
        "Equip Tower Pets",
        "HQ Explosions",
        "HQ Effects",
        "Particle LOD",
        "Show Tower Options",
        "Always Display Tower Buffs",
        "Prefer Vertical Upgrades",
        "Camera Shake",
        "Bullet Trails",
        "Low Quality Paths",
        "Low Quality Rings",
        "Character Scale",
        "UI Scale",
        "Sprint",
        "Emote Wheel",
        "Sticker Wheel",
        "Communication Wheel",
        "Tower 1",
        "Tower 2",
        "Tower 3",
        "Tower 4",
        "Tower 5",
        "Tower 6",
        "Upgrade Tower",
        "Upgrade Bottom Path",
        "Sell Tower",
        "Rotate Tower",
        "Cancel Placement",
        "Switch Hotbar",
        "Toggle Enemy Spawner",
        "Toggle Admin Panel",
        "Ability 1",
        "Ability 2",
        "Ability 3",
        "Ability 4",
        "Ability 5",
        "Ability 6",
        "Ability 7",
    },
    SettingTypes = {
        Towers = {
            Type = "Sound",
            Category = "Sound",
            Description = "Adjust the volume of towers",
            Icon = 13127954140,
            Default = 1,
        },
        Music = {
            Type = "Sound",
            Category = "Sound",
            Description = "Adjust the volume of the game soundtracks",
            Icon = 13127954140,
            Default = 1,
        },
        Emotes = {
            Type = "Sound",
            Category = "Sound",
            Description = "Adjust the volume of emote sounds",
            Icon = 13127954140,
            Default = 1,
        },
        Ambience = {
            Type = "Sound",
            Category = "Sound",
            Description = "Adjust the volume of ambience sounds",
            Icon = 13127954140,
            Default = 1,
        },
        Communication = {
            Type = "Sound",
            Category = "Sound",
            DisplayName = "Communications",
            Description = "Adjust the volume of communication sounds",
            Icon = 13127954140,
            Default = 1,
        },
        DJ = {
            Type = "Sound",
            Category = "Sound",
            Description = "Adjust the volume of DJ Booth sounds",
            Icon = 13127954140,
            Default = 1,
        },
        Stickers = {
            Type = "Sound",
            Category = "Sound",
            Description = "Adjust the volume of sticker sounds",
            Icon = 13127954140,
            Default = 1,
        },
        Cutscene = {
            Type = "Sound",
            Category = "Sound",
            Description = "Adjust the volume of cutscenes",
            Icon = 13127954140,
            Default = 1,
        },
        Yapping = {
            Type = "Sound",
            Category = "Sound",
            DisplayName = "Dialog",
            Description = "Adjust the volume of dialog",
            Icon = 13127954140,
            Default = 1,
        },
        ["Skills Enabled"] = {
            Type = "SkillsEnabled",
            Category = "Gameplay",
            Description = "Turn off/on all of your skills",
            Icon = 13175199287,
            Default = true,
        },
        ["Auto Skip"] = {
            Type = "AutoSkip",
            Category = "Gameplay",
            Description = "Automatically skip waves",
            Icon = 13175199287,
            Default = false,
        },
        Dialog = {
            Type = "Switch",
            Category = "Gameplay",
            Description = "In-game dialog and tips",
            Icon = 13127053224,
            Default = true,
        },
        ["Hide suggestions"] = {
            Type = "Switch",
            Category = "Gameplay",
            Description = "Hide suggestions made by other players",
            Icon = 13127053224,
            Default = false,
        },
        ["Camera Shake"] = {
            Type = "Switch",
            Category = "Gameplay",
            Description = "Shake camera to environment",
            Icon = 13126940343,
            Default = true,
        },
        ["Health Bar Color"] = {
            Type = "HealthColor",
            Category = "Gameplay",
            Group = "Graphics",
            Description = "Adjust the base health color",
            Icon = 125206964150470,
            Default = "Auto",
        },
        ["Hide Tower Rings"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Display which towers are yours",
            Icon = 13126938932,
            Default = false,
        },
        ["Show Nametags"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Display local name tags",
            Icon = 13126939116,
            Default = true,
        },
        ["Show Flair"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Display group rank status",
            Icon = 13126939704,
            Default = true,
        },
        ["Show Tower Pets"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Show all tower pets",
            Icon = 90413550082319,
            Default = true,
        },
        ["Show Currency Drops"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Show all currency drops",
            Icon = 13127015600,
            Default = true,
        },
        ["Show Shadows"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Toggles all the games shadows",
            Icon = 77632880321992,
            Default = true,
        },
        ["Equip Tower Pets"] = {
            Type = "EquipTowerPets",
            Category = "Graphics",
            Description = "Equip your own tower pets",
            Icon = 90413550082319,
            Default = true,
        },
        ["HQ Explosions"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Detailed explosion particles",
            Icon = 13126939304,
            Default = true,
        },
        ["HQ Effects"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Detailed particle effects",
            Icon = 107905952160411,
            Default = true,
        },
        ["Particle LOD"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Reduce particle effects at distance",
            Icon = 107905952160411,
            Default = true,
        },
        ["Show Tower Options"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Always show tower options",
            Icon = 13127015600,
            Default = true,
        },
        ["Always Display Tower Buffs"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Always show active tower buff percentages",
            Icon = 115949944044634,
            Default = false,
        },
        ["Prefer Vertical Upgrades"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Vertically stack upgrade GUI",
            Icon = 13126938571,
            Default = false,
        },
        ["Bullet Trails"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Leave trail particles behind bullets",
            Icon = 13126940519,
            Default = true,
        },
        ["Low Quality Paths"] = {
            Type = "EnemyPaths",
            Category = "Graphics",
            Group = "Graphics",
            Description = "Adjust the quality of enemy paths",
            Icon = 13175199177,
            Default = "Auto",
        },
        ["Low Quality Rings"] = {
            Type = "Switch",
            Category = "Graphics",
            Description = "Use the lower quality range rings!",
            Icon = 81221935232644,
            Default = true,
        },
        ["UI Scale"] = {
            Type = "UIScale",
            Category = "Graphics",
            Group = "Scales",
            Description = "Adjust the size of your user inteface",
            Icon = 13127015600,
            Default = Enum_2.UIScale.Default,
        },
        ["Character Scale"] = {
            Type = "CharacterScale",
            Category = "Gameplay",
            Group = "Scales",
            Description = "Change your character's size.",
            Icon = 13126940137,
            Default = Enum_2.CharacterScale.Normal,
        },
        Sprint = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Actions",
            Default = Enum.KeyCode.LeftShift.Name,
        },
        ["Emote Wheel"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Actions",
            Default = Enum.KeyCode.G.Name,
        },
        ["Sticker Wheel"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Actions",
            Default = Enum.KeyCode.H.Name,
        },
        ["Communication Wheel"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Actions",
            Default = Enum.KeyCode.N.Name,
        },
        ["Tower 1"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Hotbar",
            Default = Enum.KeyCode.One.Name,
        },
        ["Tower 2"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Hotbar",
            Default = Enum.KeyCode.Two.Name,
        },
        ["Tower 3"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Hotbar",
            Default = Enum.KeyCode.Three.Name,
        },
        ["Tower 4"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Hotbar",
            Default = Enum.KeyCode.Four.Name,
        },
        ["Tower 5"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Hotbar",
            Default = Enum.KeyCode.Five.Name,
        },
        ["Tower 6"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Hotbar",
            Default = Enum.KeyCode.Six.Name,
        },
        ["Upgrade Tower"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Placement",
            Default = Enum.KeyCode.E.Name,
        },
        ["Upgrade Bottom Path"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Placement",
            Default = Enum.KeyCode.Z.Name,
        },
        ["Sell Tower"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Placement",
            Default = Enum.KeyCode.X.Name,
        },
        ["Rotate Tower"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Placement",
            Default = Enum.KeyCode.R.Name,
        },
        ["Cancel Placement"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Placement",
            Default = Enum.KeyCode.Q.Name,
        },
        ["Switch Hotbar"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Placement",
            Default = Enum.KeyCode.Q.Name,
        },
        ["Toggle Admin Panel"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Placement",
            Default = Enum.KeyCode.C.Name,
        },
        ["Toggle Enemy Spawner"] = {
            Type = "Hotkey",
            Category = "Keybinds",
            Group = "Placement",
            Default = Enum.KeyCode.Y.Name,
        },
        ["Ability 1"] = {
            Type = "AbilityHotkey",
            Category = "Keybinds",
            Group = "Abilities",
            Default = Enum.KeyCode.F.Name,
        },
        ["Ability 2"] = {
            Type = "AbilityHotkey",
            Category = "Keybinds",
            Group = "Abilities",
            Default = Enum.KeyCode.B.Name,
        },
        ["Ability 3"] = {
            Type = "AbilityHotkey",
            Category = "Keybinds",
            Group = "Abilities",
            Default = Enum.KeyCode.H.Name,
        },
        ["Ability 4"] = {
            Type = "AbilityHotkey",
            Category = "Keybinds",
            Group = "Abilities",
            Default = Enum.KeyCode.J.Name,
        },
        ["Ability 5"] = {
            Type = "AbilityHotkey",
            Category = "Keybinds",
            Group = "Abilities",
            Default = Enum.KeyCode.K.Name,
        },
        ["Ability 6"] = {
            Type = "AbilityHotkey",
            Category = "Keybinds",
            Group = "Abilities",
            Default = Enum.KeyCode.L.Name,
        },
        ["Ability 7"] = {
            Type = "AbilityHotkey",
            Category = "Keybinds",
            Group = "Abilities",
            Default = Enum.KeyCode.O.Name,
        },
    },
}