-- Script path: ReplicatedStorage.Content.Gamemodes.PVP.Difficulties.PVP_lowRanks.SpawnableEnemies
-- Decompile time: 0.53 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
require(ReplicatedStorage.Shared.Types.PVPConstantTypes)
return {
    Normal = {
        Cost = 45,
        Eco = 3,
        PurchaseAmount = 3,
        SpawnTimer = 1.2,
        PurchaseDebounceTime = 0,
        StartWave = 2,
        Icon = "rbxassetid://17514280373",
    },
    Speedy = {
        Cost = 65,
        Eco = 4,
        PurchaseAmount = 2,
        SpawnTimer = 1,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280012",
        StartWave = 3,
    },
    Slow = {
        Cost = 75,
        Eco = 5,
        PurchaseAmount = 3,
        SpawnTimer = 1.2,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280271",
        StartWave = 5,
    },
    Hidden = {
        Cost = 100,
        Eco = 8,
        PurchaseAmount = 2,
        SpawnTimer = 0.8,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280740",
        StartWave = 8,
    },
    Breaker2 = {
        Cost = 120,
        Eco = 10,
        PurchaseAmount = 2,
        SpawnTimer = 1.2,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280886",
        StartWave = 10,
    },
    ["Normal Boss"] = {
        Cost = 150,
        Eco = 12,
        PurchaseAmount = 1,
        SpawnTimer = 2,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514281040",
        StartWave = 12,
    },
    Hazmat = {
        Cost = 210,
        Eco = 15,
        PurchaseAmount = 2,
        SpawnTimer = 1,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280956",
        StartWave = 15,
    },
    Necromancer = {
        Health = 500,
        Cost = 260,
        Eco = 0,
        PurchaseAmount = 1,
        SpawnTimer = 1.5,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280487",
        StartWave = 18,
    },
    ["Hidden Boss"] = {
        Cost = 480,
        Eco = 0,
        PurchaseAmount = 1,
        SpawnTimer = 3,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280635",
        StartWave = 20,
    },
    ["Slow Boss"] = {
        Health = 2800,
        Cost = 750,
        Eco = -10,
        PurchaseAmount = 1,
        SpawnTimer = 2,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280160",
        StartWave = 23,
    },
    ["Speedy Boss"] = {
        Health = 4000,
        Cost = 3000,
        Eco = -25,
        PurchaseAmount = 1,
        SpawnTimer = 4,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280804",
        StartWave = 26,
    },
    Brute = {
        Health = 10000,
        Cost = 6000,
        Eco = -50,
        PurchaseAmount = 1,
        SpawnTimer = 5,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514279832",
        StartWave = 30,
    },
}