-- Script path: ReplicatedStorage.Content.Gamemodes.PVP.Difficulties.PVP_highRanks.SpawnableEnemies
-- Decompile time: 0.68 ms

local ReplicatedStorage = game:GetService("ReplicatedStorage")
require(ReplicatedStorage.Shared.Types.PVPConstantTypes)
return {
    Abnormal = {
        Cost = 50,
        Eco = 4,
        PurchaseAmount = 3,
        SpawnTimer = 1.2,
        PurchaseDebounceTime = 0,
        StartWave = 2,
        Icon = "rbxassetid://17514280373",
    },
    Quick = {
        Cost = 65,
        Eco = 5,
        PurchaseAmount = 2,
        SpawnTimer = 1,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280012",
        StartWave = 3,
    },
    Heavy = {
        Cost = 90,
        Eco = 8,
        PurchaseAmount = 2,
        SpawnTimer = 1.6,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280271",
        StartWave = 5,
    },
    ["Fallen Soul"] = {
        Cost = 150,
        Eco = 10,
        PurchaseAmount = 1,
        SpawnTimer = 1.5,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280740",
        StartWave = 9,
    },
    ["Fallen Hazmat"] = {
        Cost = 250,
        Eco = 16,
        PurchaseAmount = 1,
        SpawnTimer = 1.4,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280956",
        StartWave = 11,
    },
    Fallen = {
        Cost = 350,
        Eco = 20,
        PurchaseAmount = 1,
        SpawnTimer = 2,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280886",
        StartWave = 14,
    },
    ["Fallen Necromancer"] = {
        Cost = 1650,
        Eco = 0,
        PurchaseAmount = 1,
        SpawnTimer = 5,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280487",
        StartWave = 17,
    },
    ["Possessed Armor"] = {
        Cost = 1000,
        Eco = 20,
        PurchaseAmount = 2,
        SpawnTimer = 3,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514281040",
        StartWave = 18,
    },
    ["Fallen Hero"] = {
        Cost = 1250,
        Eco = 5,
        PurchaseAmount = 1,
        SpawnTimer = 3,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280635",
        StartWave = 20,
    },
    ["Fallen Tank"] = {
        Cost = 1500,
        Eco = -10,
        PurchaseAmount = 1,
        SpawnTimer = 5,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280160",
        StartWave = 23,
    },
    ["Fallen Shield"] = {
        Cost = 5000,
        Eco = -40,
        PurchaseAmount = 1,
        SpawnTimer = 7,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514280804",
        StartWave = 26,
    },
    ["Fallen Guardian"] = {
        Cost = 5000,
        Eco = -75,
        PurchaseAmount = 1,
        SpawnTimer = 7.5,
        PurchaseDebounceTime = 0,
        Icon = "rbxassetid://17514279832",
        StartWave = 27,
    },
}