-- Script path: ReplicatedStorage.Content.Tower.Mercenary Base.TowerInformation
-- Decompile time: 3.27 ms

return {
    ToolTip = {
        "A unit summoning tower that releases an endless stream of mercenary units.",
        "Player can choose between a Rifleman, Grenadier, Riot Guard, or Field Medic; each unit has its own strengths and weaknesses.",
        "Units can detect hidden, flying, and lead enemies.",
    },
    [0] = {
        ["Tower Ability"] = {
            {
                Header = "Ground Intelligence",
                Icon = 17202640474,
                Description = "Mercenary Base can only summon units when placed close to the path.",
                Content = {{Text = ""}},
            },
        },
        ["Tower Options"] = {
            {
                Header = "Riflemen",
                Icon = "Rifleman",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Standard Infantry unit that fires in burst"},
                    {Text = "Spawn Time: 30s"},
                    {Text = "Health: 40"},
                    {Text = "Damage: 5"},
                    {Text = "Range: 20"},
                    {Text = "Cooldown: 0.15s"},
                    {Text = "Burst: 6"},
                    {Text = "Burst Cooldown: 1.0s"},
                    {Text = "Lifetime: 150s"},
                },
            },
        },
    },
    {
        ["Tower Ability"] = {
            {
                Header = "Ground Intelligence",
                Icon = 17202640474,
                Description = "Mercenary Base can only summon units when placed close to the path.",
                Content = {{Text = ""}},
            },
        },
        ["Tower Options"] = {
            {
                Header = "Riflemen",
                Icon = "Rifleman",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Standard Infantry unit that fires in burst"},
                    {Text = "Spawn Time: 30s"},
                    {Text = "Health: 40"},
                    {Text = "Damage: 5"},
                    {Text = "Range: 20"},
                    {Text = "Cooldown: 0.15s"},
                    {Text = "Burst: 6"},
                    {Text = "Burst Cooldown: 1.0s"},
                    {Text = "Lifetime: 150s"},
                },
            },
            {
                Header = "Grenadier",
                Icon = "Grenadier",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Demolitions expert that fires grenades"},
                    {Text = "Spawn Time: 25s"},
                    {Text = "Health: 50"},
                    {Text = "Explosion Damage: 20"},
                    {Text = "Range: 19"},
                    {Text = "Cooldown: 1.4s"},
                    {Text = "Explosion Radius: 4.5"},
                    {Text = "Lifetime: 150s"},
                    {Text = "Detection: Lead"},
                },
            },
        },
    },
    {
        ["Tower Ability"] = {
            {
                Header = "Ground Intelligence",
                Icon = 17202640474,
                Description = "Mercenary Base can only summon units when placed close to the path.",
                Content = {{Text = ""}},
            },
        },
        ["Tower Options"] = {
            {
                Header = "Riflemen",
                Icon = "Rifleman",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Standard Infantry unit that fires in burst"},
                    {Text = "Spawn Time: 30s"},
                    {Text = "Health: 40"},
                    {Text = "Damage: 5"},
                    {Text = "Range: 20"},
                    {Text = "Cooldown: 0.15s"},
                    {Text = "Burst: 6"},
                    {Text = "Burst Cooldown: 1.0s"},
                    {Text = "Lifetime: 150s"},
                },
            },
            {
                Header = "Grenadier",
                Icon = "Grenadier",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Demolitions expert that fires grenades"},
                    {Text = "Spawn Time: 25s"},
                    {Text = "Health: 50"},
                    {Text = "Explosion Damage: 20"},
                    {Text = "Range: 19"},
                    {Text = "Cooldown: 1.4s"},
                    {Text = "Explosion Radius: 4.5"},
                    {Text = "Lifetime: 150s"},
                    {Text = "Detection: Lead"},
                },
            },
        },
    },
    {
        ["Tower Ability"] = {
            {
                Header = "Ground Intelligence",
                Icon = 17202640474,
                Description = "Mercenary Base can only summon units when placed close to the path.",
                Content = {{Text = ""}},
            },
            {
                Header = "Damage Buff",
                Icon = 17196819964,
                Description = "Provides a 10% damage buff to all towers within range.",
                Content = {{Text = ""}},
            },
        },
        ["Tower Options"] = {
            {
                Header = "Riflemen",
                Icon = "Rifleman",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Standard Infantry unit that fires in burst"},
                    {Text = "Spawn Time: 30s"},
                    {Text = "Health: 80"},
                    {Text = "Damage: 8"},
                    {Text = "Range: 24"},
                    {Text = "Cooldown: 0.15s"},
                    {Text = "Burst: 8"},
                    {Text = "Burst Cooldown: 1.0s"},
                    {Text = "Lifetime: 150s"},
                    {Text = "Detection: Flying, Hidden"},
                },
            },
            {
                Header = "Grenadier",
                Icon = "Grenadier",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Demolitions expert that fires grenades"},
                    {Text = "Spawn Time: 25s"},
                    {Text = "Health: 135"},
                    {Text = "Explosion Damage: 30"},
                    {Text = "Range: 20"},
                    {Text = "Cooldown: 1.3s"},
                    {Text = "Explosion Radius: 5"},
                    {Text = "Lifetime: 150s"},
                    {Text = "Detection: Lead"},
                },
            },
        },
    },
    {
        ["Tower Ability"] = {
            {
                Header = "Ground Intelligence",
                Icon = 17202640474,
                Description = "Mercenary Base can only summon units when placed close to the path.",
                Content = {{Text = ""}},
            },
            {
                Header = "Damage Buff",
                Icon = 17196819964,
                Description = "Provides a 10% damage buff to all towers within range.",
                Content = {{Text = ""}},
            },
        },
        ["Tower Options"] = {
            {
                Header = "Riflemen",
                Icon = "Rifleman",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Standard Infantry unit that fires in burst"},
                    {Text = "Spawn Time: 30s"},
                    {Text = "Health: 80"},
                    {Text = "Damage: 8"},
                    {Text = "Range: 24"},
                    {Text = "Cooldown: 0.15s"},
                    {Text = "Burst: 8"},
                    {Text = "Burst Cooldown: 1.0s"},
                    {Text = "Lifetime: 150s"},
                    {Text = "Detection: Flying, Hidden"},
                },
            },
            {
                Header = "Grenadier",
                Icon = "Grenadier",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Demolitions expert that fires grenades"},
                    {Text = "Spawn Time: 25s"},
                    {Text = "Health: 135"},
                    {Text = "Explosion Damage: 30"},
                    {Text = "Range: 20"},
                    {Text = "Cooldown: 1.3s"},
                    {Text = "Explosion Radius: 5"},
                    {Text = "Lifetime: 150s"},
                    {Text = "Detection: Lead"},
                },
            },
            {
                Header = "Riot Guard",
                Icon = "Riot Guard",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "A heavily armored unit that charges into enemies."},
                    {Text = "Spawn Time: 40s"},
                    {Text = "Health: 800"},
                    {Text = "Damage: 50"},
                    {Text = "Defense: 10"},
                    {Text = "Knockback Force: 15"},
                    {Text = "Lifetime: 75s"},
                    {Text = "Detection: Hidden"},
                },
            },
        },
    },
    {
        ["Tower Ability"] = {
            {
                Header = "Ground Intelligence",
                Icon = 17202640474,
                Description = "Mercenary Base can only summon units when placed close to the path.",
                Content = {{Text = ""}},
            },
            {
                Header = "Damage Buff",
                Icon = 17196819964,
                Description = "Provides a 12.5% damage buff to all towers within range.",
                Content = {{Text = ""}},
            },
            {
                Header = "Air Drop",
                Icon = 17196820108,
                Description = "Spend 2500 cash to call in an air drop of mercenaries.",
                Content = {{Text = "Cooldown: 50s"}},
            },
        },
        ["Tower Options"] = {
            {
                Header = "Riflemen",
                Icon = "Rifleman",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Standard Infantry unit that fires in burst"},
                    {Text = "Spawn Time: 30s"},
                    {Text = "Health: 80"},
                    {Text = "Damage: 8"},
                    {Text = "Range: 24"},
                    {Text = "Cooldown: 0.15s"},
                    {Text = "Burst: 8"},
                    {Text = "Burst Cooldown: 1.0s"},
                    {Text = "Lifetime: 150s"},
                    {Text = "Detection: Flying, Hidden"},
                },
            },
            {
                Header = "Grenadier",
                Icon = "Grenadier",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Demolitions expert that fires grenades"},
                    {Text = "Spawn Time: 25s"},
                    {Text = "Health: 135"},
                    {Text = "Explosion Damage: 30"},
                    {Text = "Range: 20"},
                    {Text = "Cooldown: 1.3s"},
                    {Text = "Explosion Radius: 5"},
                    {Text = "Lifetime: 150s"},
                    {Text = "Detection: Lead"},
                },
            },
            {
                Header = "Riot Guard",
                Icon = "Riot Guard",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "A heavily armored unit that charges into enemies."},
                    {Text = "Spawn Time: 40s"},
                    {Text = "Health: 800"},
                    {Text = "Defense: 10"},
                    {Text = "Damage: 50"},
                    {Text = "Cooldown: 1.5"},
                    {Text = "Knockback Force: 15"},
                    {Text = "Lifetime: 75s"},
                    {Text = "Detection: Hidden"},
                },
            },
            {
                Header = "Field Medic",
                Icon = "Field Medic",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "A support unit that heals nearby allies and gives them a shield."},
                    {Text = "Spawn Time: 30s"},
                    {Text = "Health: 300"},
                    {Text = "Range: 35"},
                    {Text = "Heal Per Second: 75"},
                    {Text = "Max Targets: 8"},
                    {Text = "Shield Cooldown: 15s"},
                    {Text = "Lifetime: 150s"},
                },
            },
        },
    },
    {
        ["Tower Ability"] = {
            {
                Header = "Ground Intelligence",
                Icon = 17202640474,
                Description = "Mercenary Base can only summon units when placed close to the path.",
                Content = {{Text = ""}},
            },
            {
                Header = "Damage Buff",
                Icon = 17196819964,
                Description = "Provides a 15% damage buff to all towers within range.",
                Content = {{Text = ""}},
            },
            {
                Header = "Air Drop",
                Icon = 17196820108,
                Description = "Spend 2500 cash to call in an air drop of mercenaries.",
                Content = {{Text = "Cooldown: 50s"}},
            },
        },
        ["Tower Options"] = {
            {
                Header = "Riflemen",
                Icon = "Rifleman",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Standard Infantry unit that fires in burst"},
                    {Text = "Spawn Time: 30s"},
                    {Text = "Health: 275"},
                    {Text = "Damage: 17"},
                    {Text = "Range: 30"},
                    {Text = "Cooldown: 0.15s"},
                    {Text = "Burst: 8"},
                    {Text = "Burst Cooldown: 1s"},
                    {Text = "Lifetime: 150s"},
                    {Text = "Detection: Flying, Hidden"},
                },
            },
            {
                Header = "Grenadier",
                Icon = "Grenadier",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "Demolitions expert that fires grenades"},
                    {Text = "Spawn Time: 25s"},
                    {Text = "Health: 325"},
                    {Text = "Explosion Damage: 40"},
                    {Text = "Range: 21.5"},
                    {Text = "Cooldown: 1.2s"},
                    {Text = "Explosion Radius: 6"},
                    {Text = "Lifetime: 150s"},
                    {Text = "Detection: Lead"},
                },
            },
            {
                Header = "Riot Guard",
                Icon = "Riot Guard",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "A heavily armored unit that charges into enemies."},
                    {Text = "Spawn Time: 40s"},
                    {Text = "Health: 2000"},
                    {Text = "Defense: 15"},
                    {Text = "Damage: 50"},
                    {Text = "Cooldown: 1"},
                    {Text = "Knockback Force: 25"},
                    {Text = "Lifetime: 75s"},
                    {Text = "Detection: Hidden"},
                },
            },
            {
                Header = "Field Medic",
                Icon = "Field Medic",
                Color = "rgb(255, 255, 255)",
                Content = {
                    {Text = "A support unit that heals nearby allies and gives them a shield."},
                    {Text = "Spawn Time: 30s"},
                    {Text = "Health: 600"},
                    {Text = "Range: 35"},
                    {Text = "Heal Per Second: 100"},
                    {Text = "Max Targets: 10"},
                    {Text = "Shield Cooldown: 15s"},
                    {Text = "Lifetime: 150s"},
                },
            },
        },
    },
}