-- Script path: ReplicatedStorage.Content.NewEnemies.Speedy.Stats
-- Decompile time: 0.16 ms

return {
    Speed = 5.5,
    MaxHealth = 6,
    HealthPerDifficulty = {
        Baby = 4,
        Easy = 4,
        Normal = 3,
        Casual = 4,
        Tutorial = 3,
        Intermediate = 6,
        Insane = 6,
        Fallen = 6,
        PVP_lowRanks = 6,
        PVP_midRanks = 8,
        PVP_highRanks = 10,
        SummerEasy = 8,
        SummerMedium = 12,
        Chapter1Mission1 = 6,
        Chapter1Mission2 = 6,
        Chapter1Mission3 = 8,
        Chapter1Mission4 = 8,
        Chapter1Mission5 = 8,
        Chapter1Mission6 = 10,
        Chapter1Mission7 = 10,
        Chapter1Mission8 = 12,
    },
    Reward = {
        Easy = 5,
        Casual = 5,
        Intermediate = 5,
        PizzaParty = 5,
        Badlands = 5,
        Molten = 5,
        Fallen = 5,
        PVP_lowRanks = 5,
        PVP_midRanks = 5,
        PVP_highRanks = 5,
        PlsDonateHard = 5,
        PollutedWasteland = 5,
        SummerEasy = 6,
        SummerMedium = 8,
        Chapter1Mission1 = 8,
        Chapter1Mission2 = 8,
        Chapter1Mission3 = 10,
        Chapter1Mission4 = 10,
        Chapter1Mission5 = 10,
        Chapter1Mission6 = 20,
        Chapter1Mission7 = 20,
        Chapter1Mission8 = 20,
    },
    Attributes = {},
}